// GENERATED BY GEMINI — Campus LMS Module
// Integration step: copy this file to src/components/lms/LMSActivityList.tsx

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  Search,
  ClipboardCheck,
  Filter,
  ArrowLeft,
  Clock,
  CheckCircle2,
  Award,
  AlertCircle,
  Sparkles,
} from 'lucide-react';
import { lmsService } from '../../services/lmsService';
import { LMSActivity, LMSCourse, ActivityStatus } from '../../types';
import ActivityItem from './shared/ActivityItem';

interface LMSActivityListProps {
  onSelectActivity?: (activityId: string) => void;
  onBack?: () => void;
}

export const LMSActivityList: React.FC<LMSActivityListProps> = ({
  onSelectActivity = (_activityId: string) => {},
  onBack = () => {},
}) => {
  const [activities, setActivities] = useState<LMSActivity[]>([]);
  const [courses, setCourses] = useState<LMSCourse[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | ActivityStatus>('all');
  const [selectedCourseId, setSelectedCourseId] = useState<string>('all');

  useEffect(() => {
    const loadData = () => {
      setActivities(lmsService.getActivities());
      setCourses(lmsService.getCourses());
    };
    loadData();
    const unsub = lmsService.subscribe(loadData);
    return () => unsub();
  }, []);

  const filteredActivities = activities.filter((act) => {
    const matchesSearch =
      act.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (act.courseName && act.courseName.toLowerCase().includes(searchQuery.toLowerCase()));

    if (!matchesSearch) return false;
    if (statusFilter !== 'all' && act.status !== statusFilter) return false;
    if (selectedCourseId !== 'all' && act.courseId !== selectedCourseId) return false;

    return true;
  });

  const countByStatus = (status: ActivityStatus) =>
    activities.filter((a) => a.status === status).length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={onBack}
            className="p-2 rounded-xl bg-white border border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-slate-50 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <h1 className="font-display font-bold text-2xl text-slate-900">
              Tareas y Actividades Evaluadas
            </h1>
            <p className="text-xs text-slate-500">
              {filteredActivities.length} actividad(es) encontrada(s)
            </p>
          </div>
        </div>

        {/* Search Input */}
        <div className="relative w-full sm:w-72">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Buscar actividad o materia..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-white border border-slate-200/90 rounded-full pl-9 pr-4 py-2 text-xs text-slate-800 focus:outline-none focus:border-[#25855A] transition-all"
          />
        </div>
      </div>

      {/* Filter Pills: Statuses */}
      <div className="flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={() => setStatusFilter('all')}
          className={`filter-pill ${statusFilter === 'all' ? 'filter-pill-active' : ''}`}
        >
          <span>Todas ({activities.length})</span>
        </button>

        <button
          type="button"
          onClick={() => setStatusFilter('pendiente')}
          className={`filter-pill ${statusFilter === 'pendiente' ? 'filter-pill-active' : ''}`}
        >
          <Clock className="w-3.5 h-3.5 text-amber-500" />
          <span>Pendientes ({countByStatus('pendiente')})</span>
        </button>

        <button
          type="button"
          onClick={() => setStatusFilter('entregada')}
          className={`filter-pill ${statusFilter === 'entregada' ? 'filter-pill-active' : ''}`}
        >
          <CheckCircle2 className="w-3.5 h-3.5 text-sky-500" />
          <span>Entregadas ({countByStatus('entregada')})</span>
        </button>

        <button
          type="button"
          onClick={() => setStatusFilter('calificada')}
          className={`filter-pill ${statusFilter === 'calificada' ? 'filter-pill-active' : ''}`}
        >
          <Award className="w-3.5 h-3.5 text-emerald-500" />
          <span>Calificadas ({countByStatus('calificada')})</span>
        </button>

        <button
          type="button"
          onClick={() => setStatusFilter('vencida')}
          className={`filter-pill ${statusFilter === 'vencida' ? 'filter-pill-active' : ''}`}
        >
          <AlertCircle className="w-3.5 h-3.5 text-red-500" />
          <span>Vencidas ({countByStatus('vencida')})</span>
        </button>
      </div>

      {/* Secondary Filter: By Course */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1 text-xs">
        <span className="text-slate-400 font-semibold uppercase text-[10px] tracking-wider shrink-0">
          Materia:
        </span>
        <button
          type="button"
          onClick={() => setSelectedCourseId('all')}
          className={`px-3 py-1 rounded-lg text-xs font-semibold shrink-0 transition-colors ${
            selectedCourseId === 'all'
              ? 'bg-slate-800 text-white'
              : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
          }`}
        >
          Todas las materias
        </button>
        {courses.map((c) => (
          <button
            key={c.id}
            type="button"
            onClick={() => setSelectedCourseId(c.id)}
            className={`px-3 py-1 rounded-lg text-xs font-semibold shrink-0 transition-colors ${
              selectedCourseId === c.id
                ? 'bg-[#25855A] text-white'
                : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
            }`}
          >
            {c.name}
          </button>
        ))}
      </div>

      {/* Activity Items List */}
      {filteredActivities.length === 0 ? (
        <div className="card-crema p-12 text-center">
          <ClipboardCheck className="w-10 h-10 text-slate-300 mx-auto mb-3" />
          <h3 className="font-display font-bold text-slate-700 text-base">
            No se encontraron actividades
          </h3>
          <p className="text-xs text-slate-500 mt-1">
            Prueba cambiando los filtros seleccionados o el criterio de búsqueda.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredActivities.map((activity, idx) => (
            <ActivityItem
              key={activity.id}
              activity={activity}
              index={idx}
              onSelect={() => onSelectActivity(activity.id)}
            />
          ))}
        </div>
      )}
    </div>
  );
};

export default LMSActivityList;
