// GENERATED BY GEMINI — Campus LMS Module
// Integration step: copy this file to src/components/lms/LMSActivityDetail.tsx

import React from 'react';
import LMSSubmissionForm from './LMSSubmissionForm';

interface LMSActivityDetailProps {
  activityId: string;
  onBack?: () => void;
}

export const LMSActivityDetail: React.FC<LMSActivityDetailProps> = ({
  activityId,
  onBack,
}) => {
  return <LMSSubmissionForm activityId={activityId} onBack={onBack} />;
};

export default LMSActivityDetail;
