// GENERATED BY GEMINI — Campus LMS Module
// Catálogo Oficial de Módulos del Bachillerato Técnico Vocacional en Diseño Gráfico

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  Search,
  BookOpen,
  Filter,
  GraduationCap,
  Layers,
  ArrowLeft,
  Sparkles,
  Palette,
  Layout,
  Megaphone,
  Printer,
  Briefcase,
} from 'lucide-react';
import { lmsService } from '../../services/lmsService';
import { LMSCourse, TechnicalYear } from '../../types';
import CourseCard from './shared/CourseCard';

interface LMSCourseListProps {
  onSelectCourse?: (courseId: string) => void;
  onBack?: () => void;
}

export const LMSCourseList: React.FC<LMSCourseListProps> = ({
  onSelectCourse = (_courseId: string) => {},
  onBack = () => {},
}) => {
  const [courses, setCourses] = useState<LMSCourse[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedYearFilter, setSelectedYearFilter] = useState<'all' | TechnicalYear>('all');
  const [selectedAreaFilter, setSelectedAreaFilter] = useState<string>('all');

  useEffect(() => {
    const loadCourses = () => {
      setCourses(lmsService.getCourses());
    };
    loadCourses();
    const unsub = lmsService.subscribe(loadCourses);
    return () => unsub();
  }, []);

  const affineAreas = [
    { key: 'all', label: 'Todas las Áreas' },
    { key: 'Estrategias conceptuales y artísticas', label: 'Conceptual & Artístico' },
    { key: 'Diseño y diagramación', label: 'Diseño & Diagramación' },
    { key: 'Publicidad y comunicación', label: 'Publicidad & Medios' },
    { key: 'Producción', label: 'Producción & Impresión' },
    { key: 'Emprendedurismo', label: 'Emprendedurismo' },
  ];

  // Filter logic
  const filteredCourses = courses.filter((course) => {
    const matchesSearch =
      course.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      course.code.toLowerCase().includes(searchQuery.toLowerCase()) ||
      course.teacherName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (course.affineArea && course.affineArea.toLowerCase().includes(searchQuery.toLowerCase()));

    if (!matchesSearch) return false;

    if (selectedYearFilter !== 'all' && course.technicalYear !== selectedYearFilter) {
      return false;
    }

    if (selectedAreaFilter !== 'all' && course.affineArea !== selectedAreaFilter) {
      return false;
    }

    return true;
  });

  return (
    <div className="space-y-6">
      {/* Top Header & Navigation */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={onBack}
            className="p-2.5 rounded-2xl bg-white border border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-slate-50 transition-colors shadow-sm"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-[#0D71B9] uppercase tracking-wider">
                Malla Curricular Oficial • BTV Diseño Gráfico
              </span>
            </div>
            <h1 className="font-display font-extrabold text-2xl md:text-3xl text-slate-900">
              Catálogo de Módulos Técnicos
            </h1>
            <p className="text-xs text-slate-500">
              {filteredCourses.length} de {courses.length} módulos técnicos (2,574 Horas Totales en 3 Años)
            </p>
          </div>
        </div>

        {/* Search Bar */}
        <div className="relative w-full sm:w-80">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Buscar por módulo, código (ej. BTVDG1.7) o docente..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-white border border-slate-200 rounded-full pl-9 pr-4 py-2.5 text-xs text-slate-800 focus:outline-none focus:border-[#0D71B9] shadow-sm transition-all"
          />
        </div>
      </div>

      {/* Year Filter Buttons (1°, 2°, 3° Año) */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white p-3 rounded-2xl border border-slate-200 shadow-sm">
        <div className="flex items-center gap-1.5 flex-wrap">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wide mr-1 flex items-center gap-1">
            <GraduationCap className="w-3.5 h-3.5" /> Año:
          </span>
          <button
            type="button"
            onClick={() => setSelectedYearFilter('all')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              selectedYearFilter === 'all'
                ? 'bg-slate-900 text-white shadow-sm'
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            Todos los Años ({courses.length})
          </button>
          <button
            type="button"
            onClick={() => setSelectedYearFilter('1')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              selectedYearFilter === '1'
                ? 'bg-[#0D71B9] text-white shadow-sm'
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            1° Año (720h • 9 Módulos)
          </button>
          <button
            type="button"
            onClick={() => setSelectedYearFilter('2')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              selectedYearFilter === '2'
                ? 'bg-[#0D71B9] text-white shadow-sm'
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            2° Año (720h • 9 Módulos)
          </button>
          <button
            type="button"
            onClick={() => setSelectedYearFilter('3')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              selectedYearFilter === '3'
                ? 'bg-purple-700 text-white shadow-sm'
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            3° Año (1,200h • 9 Módulos)
          </button>
        </div>

        {/* Total hours indicator */}
        <div className="text-[11px] font-bold text-slate-500 bg-slate-50 px-3 py-1.5 rounded-xl border border-slate-200 self-start sm:self-auto">
          {selectedYearFilter === 'all'
            ? 'Total Plan: 2,574 Horas Técnicas'
            : selectedYearFilter === '3'
            ? 'Especialización: 1,200 Horas'
            : 'Carga Anual: 720 Horas'}
        </div>
      </div>

      {/* Filter by Affine Area */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1 text-xs">
        <span className="text-slate-400 font-bold text-[11px] uppercase tracking-wide shrink-0">Área:</span>
        {affineAreas.map((area) => (
          <button
            key={area.key}
            type="button"
            onClick={() => setSelectedAreaFilter(area.key)}
            className={`px-3 py-1 rounded-full whitespace-nowrap font-medium transition-all ${
              selectedAreaFilter === area.key
                ? 'bg-[#0D71B9]/15 text-[#0D71B9] font-bold border border-[#0D71B9]/30'
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            {area.label}
          </button>
        ))}
      </div>

      {/* Empty State */}
      {filteredCourses.length === 0 ? (
        <div className="card-crema p-12 text-center border border-slate-200">
          <BookOpen className="w-10 h-10 text-slate-400 mx-auto mb-3" />
          <h3 className="font-display font-bold text-slate-800 text-lg">
            No se encontraron módulos
          </h3>
          <p className="text-xs text-slate-500 mt-1 mb-4">
            Intenta cambiar los filtros de año, área o término de búsqueda.
          </p>
          <button
            type="button"
            onClick={() => {
              setSearchQuery('');
              setSelectedYearFilter('all');
              setSelectedAreaFilter('all');
            }}
            className="btn-secondary !py-2 !px-4 text-xs"
          >
            Restablecer Filtros
          </button>
        </div>
      ) : (
        /* Courses Grid */
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredCourses.map((course, idx) => (
            <CourseCard
              key={course.id}
              course={course}
              index={idx}
              onClick={() => onSelectCourse(course.id)}
            />
          ))}
        </div>
      )}
    </div>
  );
};

export default LMSCourseList;
