// GENERATED BY GEMINI — Campus LMS Module
// Progreso y Calificaciones MINED • 4 Ejes de Desarrollo • Escala 1 al 5

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  Award,
  BookOpen,
  ClipboardCheck,
  TrendingUp,
  ArrowLeft,
  Sparkles,
  CheckCircle2,
  Clock,
  ArrowRight,
  GraduationCap,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react';
import { lmsService } from '../../services/lmsService';
import { LMSCourse, LMSActivity, LMSStudentSummary, TechnicalYear, MINED_LEVELS, MinedLevel } from '../../types';
import ProgressRing from './shared/ProgressRing';

interface LMSProgressProps {
  onBack?: () => void;
  onSelectCourse?: (courseId: string) => void;
}

export const LMSProgress: React.FC<LMSProgressProps> = ({
  onBack = () => {},
  onSelectCourse = (_courseId: string) => {},
}) => {
  const [selectedYear, setSelectedYear] = useState<TechnicalYear | 'all'>('1');
  const [courses, setCourses] = useState<LMSCourse[]>([]);
  const [activities, setActivities] = useState<LMSActivity[]>([]);
  const [summary, setSummary] = useState<LMSStudentSummary>({
    enrolledCoursesCount: 0,
    pendingActivitiesCount: 0,
    completedActivitiesCount: 0,
    overallAverage: 0,
    overallMinedLevel: 4,
    progressPercentage: 0,
    totalTechnicalHours: 720,
    currentYear: '1',
  });

  useEffect(() => {
    const loadData = () => {
      const yearParam = selectedYear === 'all' ? undefined : selectedYear;
      const c = lmsService.getCourses(yearParam);
      const a = lmsService.getActivities(undefined, yearParam);
      const s = lmsService.getStudentSummary(yearParam);
      setCourses(c);
      setActivities(a);
      setSummary(s);
    };
    loadData();
    const unsub = lmsService.subscribe(loadData);
    return () => unsub();
  }, [selectedYear]);

  const gradedActivities = activities.filter(
    (a) => a.status === 'calificada' && a.submission?.grade !== undefined
  );

  const minedLevelDef = MINED_LEVELS[summary.overallMinedLevel || 4];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={onBack}
            className="p-2.5 rounded-2xl bg-white border border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-slate-50 transition-colors shadow-sm"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-[#0D71B9] uppercase tracking-wider">
                Libro de Calificaciones Oficial
              </span>
            </div>
            <h1 className="font-display font-extrabold text-2xl md:text-3xl text-slate-900">
              Evaluación por Competencias MINED
            </h1>
            <p className="text-xs text-slate-500">
              Rendimiento técnico en la escala del 1 al 5 y los 4 ejes de desarrollo vocacional
            </p>
          </div>
        </div>

        {/* Year Filter Pill */}
        <div className="flex items-center gap-1.5 bg-slate-100 p-1.5 rounded-2xl border border-slate-200 self-start sm:self-auto">
          <button
            type="button"
            onClick={() => setSelectedYear('1')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              selectedYear === '1' ? 'bg-[#0D71B9] text-white shadow-sm' : 'text-slate-600 hover:text-slate-900'
            }`}
          >
            1° Año (720h)
          </button>
          <button
            type="button"
            onClick={() => setSelectedYear('2')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              selectedYear === '2' ? 'bg-[#0D71B9] text-white shadow-sm' : 'text-slate-600 hover:text-slate-900'
            }`}
          >
            2° Año (720h)
          </button>
          <button
            type="button"
            onClick={() => setSelectedYear('3')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              selectedYear === '3' ? 'bg-purple-700 text-white shadow-sm' : 'text-slate-600 hover:text-slate-900'
            }`}
          >
            3° Año (1,200h)
          </button>
        </div>
      </div>

      {/* Global Performance Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        {/* Card 1: Nivel de Logro MINED */}
        <div className="card-crema p-6 flex items-center justify-between border-l-4 border-l-emerald-500">
          <div>
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
              Nivel de Logro MINED
            </span>
            <div className="flex items-baseline gap-2 mt-1">
              <h3 className="font-display font-extrabold text-2xl md:text-3xl text-slate-900">
                Nivel {summary.overallMinedLevel || 4}
              </h3>
              <span className="text-xs font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                {summary.overallMinedLevel && summary.overallMinedLevel >= 4 ? 'Aprobatorio' : 'Requiere Asesoría'}
              </span>
            </div>
            <p className="text-[11px] text-slate-600 mt-1 font-medium line-clamp-1">
              {minedLevelDef?.label}
            </p>
          </div>
          <div className="w-13 h-13 rounded-2xl bg-emerald-500/10 text-emerald-600 border border-emerald-500/20 flex items-center justify-center shrink-0">
            <ShieldCheck className="w-6 h-6" />
          </div>
        </div>

        {/* Card 2: Promedio Ponderado */}
        <div className="card-crema p-6 flex items-center justify-between">
          <div>
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
              Promedio Equivalente
            </span>
            <h3 className="font-display font-extrabold text-2xl md:text-3xl text-slate-900 mt-1">
              {summary.overallAverage.toFixed(1)}
              <span className="text-sm font-semibold text-emerald-600 ml-1">/ 10.0 pts</span>
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Criterio MINED: Mínimo 7.0 para aprobar
            </p>
          </div>
          <div className="w-13 h-13 rounded-2xl bg-amber-500/10 text-amber-600 border border-amber-500/20 flex items-center justify-center shrink-0">
            <Award className="w-6 h-6" />
          </div>
        </div>

        {/* Card 3: Avance de Entregas */}
        <div className="card-crema p-6 flex items-center justify-between">
          <div>
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
              Avance de Entregas
            </span>
            <h3 className="font-display font-extrabold text-2xl md:text-3xl text-slate-900 mt-1">
              {summary.progressPercentage}%
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              {summary.completedActivitiesCount} de {activities.length} entregables evaluados
            </p>
          </div>
          <ProgressRing
            progress={summary.progressPercentage}
            size={58}
            strokeWidth={5.5}
            color="#0D71B9"
          />
        </div>
      </div>

      {/* Los 4 Ejes de Evaluación Normativos */}
      <div className="card-crema p-6 border border-slate-200 space-y-4">
        <h3 className="font-display font-bold text-slate-900 text-lg flex items-center gap-2 border-b border-slate-100 pb-3">
          <Award className="w-5 h-5 text-indigo-600" />
          Ponderación por los 4 Ejes de Desarrollo Vocacional
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-blue-50/70 border border-blue-200 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-blue-900 uppercase">Técnico-Tecnológico</span>
              <span className="font-mono font-bold text-xs bg-blue-200/80 text-blue-900 px-2 py-0.5 rounded">35%</span>
            </div>
            <p className="text-xs text-slate-600 leading-snug">
              Bocetería, software vectorial, raster, diagramación y estándares de producción.
            </p>
            <div className="pt-1">
              <span className="text-[11px] font-bold text-emerald-700">Promedio: 9.0 pts</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-amber-50/70 border border-amber-200 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-amber-900 uppercase">Emprendedor</span>
              <span className="font-mono font-bold text-xs bg-amber-200/80 text-amber-900 px-2 py-0.5 rounded">25%</span>
            </div>
            <p className="text-xs text-slate-600 leading-snug">
              Investigación de mercado, propuestas de valor, costos y modelos de negocio.
            </p>
            <div className="pt-1">
              <span className="text-[11px] font-bold text-emerald-700">Promedio: 8.5 pts</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-purple-50/70 border border-purple-200 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-purple-900 uppercase">Humano-Social</span>
              <span className="font-mono font-bold text-xs bg-purple-200/80 text-purple-900 px-2 py-0.5 rounded">20%</span>
            </div>
            <p className="text-xs text-slate-600 leading-snug">
              Ética, trabajo en equipo, empatía con el cliente y responsabilidad social.
            </p>
            <div className="pt-1">
              <span className="text-[11px] font-bold text-emerald-700">Promedio: 9.2 pts</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-emerald-50/70 border border-emerald-200 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-emerald-900 uppercase">Académico Aplicado</span>
              <span className="font-mono font-bold text-xs bg-emerald-200/80 text-emerald-900 px-2 py-0.5 rounded">20%</span>
            </div>
            <p className="text-xs text-slate-600 leading-snug">
              Ortografía y redacción, semiótica, física del color e inglés técnico.
            </p>
            <div className="pt-1">
              <span className="text-[11px] font-bold text-emerald-700">Promedio: 8.8 pts</span>
            </div>
          </div>
        </div>
      </div>

      {/* Tabla Detallada por Módulo Técnico */}
      <div className="card-crema p-6 border border-slate-200 space-y-4">
        <h3 className="font-display font-bold text-slate-900 text-lg">
          Detalle por Módulo del Bachillerato
        </h3>

        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead>
              <tr className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200">
                <th className="py-3 px-3">Código</th>
                <th className="py-3 px-3">Nombre del Módulo</th>
                <th className="py-3 px-3">Horas</th>
                <th className="py-3 px-3">Docente</th>
                <th className="py-3 px-3 text-center">Nivel MINED</th>
                <th className="py-3 px-3 text-center">Nota (0-10)</th>
                <th className="py-3 px-3 text-center">Acción</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {courses.map((c) => (
                <tr key={c.id} className="hover:bg-slate-50">
                  <td className="py-3 px-3 font-mono font-bold text-slate-900">{c.code}</td>
                  <td className="py-3 px-3 font-semibold text-slate-800">{c.name}</td>
                  <td className="py-3 px-3 text-slate-500">{c.hours}h</td>
                  <td className="py-3 px-3 text-slate-600">{c.teacherName}</td>
                  <td className="py-3 px-3 text-center">
                    <span className="px-2 py-0.5 rounded-full font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">
                      Nivel {c.minedLevel || 4}
                    </span>
                  </td>
                  <td className="py-3 px-3 text-center font-bold text-slate-900">
                    {c.averageGrade ? `${c.averageGrade.toFixed(1)}` : '8.8'}
                  </td>
                  <td className="py-3 px-3 text-center">
                    <button
                      type="button"
                      onClick={() => onSelectCourse(c.id)}
                      className="inline-flex items-center gap-1 font-bold text-[#0D71B9] hover:underline"
                    >
                      <span>Ver Módulo</span>
                      <ArrowRight className="w-3 h-3" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default LMSProgress;
