// GENERATED BY GEMINI — Campus LMS Module
// Integration step: copy this file to src/components/lms/LMSSubmissionForm.tsx

import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  ArrowLeft,
  Calendar,
  Clock,
  FileText,
  UploadCloud,
  File,
  X,
  CheckCircle2,
  AlertCircle,
  Award,
  Sparkles,
  Send,
  Download,
  Info,
} from 'lucide-react';
import { lmsService } from '../../services/lmsService';
import { LMSActivity, Rubric } from '../../types';
import RubricView from './shared/RubricView';
import { getStatusBadgeConfig } from './shared/ActivityItem';

interface LMSSubmissionFormProps {
  activityId: string;
  onBack?: () => void;
  onSubmittedSuccess?: () => void;
}

export const LMSSubmissionForm: React.FC<LMSSubmissionFormProps> = ({
  activityId,
  onBack = () => {},
  onSubmittedSuccess = () => {},
}) => {
  const [activity, setActivity] = useState<LMSActivity | undefined>(undefined);
  const [submissionText, setSubmissionText] = useState('');
  const [attachedFiles, setAttachedFiles] = useState<{ name: string; size: string }[]>([]);
  const [rubricScores, setRubricScores] = useState<Record<string, number>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccessBanner, setShowSuccessBanner] = useState(false);

  useEffect(() => {
    const loadAct = () => {
      const a = lmsService.getActivityById(activityId);
      setActivity(a);
      if (a?.submission) {
        setSubmissionText(a.submission.content || '');
        setAttachedFiles(a.submission.attachments || []);
        if (a.submission.criterionScores) {
          setRubricScores(a.submission.criterionScores);
        }
      }
    };
    loadAct();
    const unsub = lmsService.subscribe(loadAct);
    return () => unsub();
  }, [activityId]);

  if (!activity) {
    return (
      <div className="card-crema p-12 text-center">
        <AlertCircle className="w-10 h-10 text-amber-500 mx-auto mb-3" />
        <h3 className="font-display font-bold text-slate-800 text-lg">Actividad no encontrada</h3>
        <p className="text-xs text-slate-500 mt-1 mb-4">
          La tarea solicitada no existe o ha sido archivada.
        </p>
        <button type="button" onClick={onBack} className="btn-primary">
          Volver a actividades
        </button>
      </div>
    );
  }

  const isDelivered = activity.status === 'entregada' || activity.status === 'calificada';
  const statusConfig = getStatusBadgeConfig(activity.status);
  const StatusIcon = statusConfig.icon;

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files) return;
    const files: File[] = Array.from(e.target.files);
    const newFiles = files.map((f: File) => ({
      name: f.name,
      size: `${(f.size / (1024 * 1024)).toFixed(2)} MB`,
    }));
    setAttachedFiles((prev) => [...prev, ...newFiles]);
  };

  const handleRemoveFile = (idx: number) => {
    setAttachedFiles((prev) => prev.filter((_, i) => i !== idx));
  };

  const handleRubricScoreSelect = (criterionId: string, score: number) => {
    setRubricScores((prev) => ({
      ...prev,
      [criterionId]: score,
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!submissionText.trim() && attachedFiles.length === 0) {
      alert('Por favor ingrese una descripción, enlace o adjunte un archivo para su entrega.');
      return;
    }

    setIsSubmitting(true);
    setTimeout(() => {
      lmsService.submitActivity(activity.id, {
        content: submissionText,
        attachments: attachedFiles,
        criterionScores: rubricScores,
      });
      setIsSubmitting(false);
      setShowSuccessBanner(true);
      onSubmittedSuccess();
    }, 600);
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Header with back button */}
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={onBack}
            className="p-2.5 rounded-2xl bg-white border border-slate-200 text-slate-600 hover:text-slate-900 hover:bg-slate-50 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <div className="flex items-center gap-2">
              <span
                className="text-xs font-bold px-2 py-0.5 rounded-md border"
                style={{
                  borderColor: `${activity.courseColor || '#0D71B9'}40`,
                  color: activity.courseColor || '#0D71B9',
                  backgroundColor: `${activity.courseColor || '#0D71B9'}10`,
                }}
              >
                {activity.courseName}
              </span>
              {activity.moduleTitle && (
                <span className="text-xs text-slate-500 font-medium">
                  • {activity.moduleTitle}
                </span>
              )}
            </div>
            <h1 className="font-display font-bold text-2xl text-slate-900 mt-1">
              {activity.title}
            </h1>
          </div>
        </div>

        <span
          className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold border ${statusConfig.classes}`}
        >
          <StatusIcon className="w-4 h-4" />
          {statusConfig.label}
        </span>
      </div>

      {/* Success Notification Banner */}
      {showSuccessBanner && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-900 flex items-center justify-between gap-3 shadow-xs"
        >
          <div className="flex items-center gap-3">
            <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
            <div>
              <p className="font-display font-bold text-sm">
                ¡Entrega registrada exitosamente!
              </p>
              <p className="text-xs text-emerald-700">
                Tu tarea ha sido enviada al docente para su revisión y calificación.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={() => setShowSuccessBanner(false)}
            className="text-xs font-bold text-emerald-800 hover:underline"
          >
            Cerrar
          </button>
        </motion.div>
      )}

      {/* Main Details & Instructions Card */}
      <div className="card-crema p-6 md:p-8 space-y-6">
        {/* Meta stats bar */}
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 pb-6 border-b border-slate-100">
          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
              Fecha Límite
            </span>
            <div className="flex items-center gap-1.5 mt-1 text-slate-800 font-semibold text-xs md:text-sm">
              <Calendar className="w-4 h-4 text-[#25855A]" />
              <span>
                {new Date(activity.dueDate).toLocaleDateString('es-SV', {
                  weekday: 'short',
                  day: 'numeric',
                  month: 'long',
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </span>
            </div>
          </div>

          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
              Ponderación Máxima
            </span>
            <div className="flex items-center gap-1.5 mt-1 text-slate-800 font-semibold text-xs md:text-sm">
              <Award className="w-4 h-4 text-amber-500" />
              <span>{activity.maxScore} Puntos Oficiales</span>
            </div>
          </div>

          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
              Tipo de Evaluación
            </span>
            <div className="flex items-center gap-1.5 mt-1 text-slate-800 font-semibold text-xs md:text-sm">
              <FileText className="w-4 h-4 text-[#0D71B9]" />
              <span className="capitalize">
                {activity.type === 'rubric' ? 'Rúbrica Institucional' : activity.type}
              </span>
            </div>
          </div>
        </div>

        {/* Instructions */}
        <div>
          <h3 className="font-display font-bold text-slate-900 text-base mb-2">
            Instrucciones de la Actividad
          </h3>
          <p className="text-slate-700 text-sm leading-relaxed whitespace-pre-line bg-slate-50/70 p-4.5 rounded-2xl border border-slate-200/80">
            {activity.instructions}
          </p>
        </div>

        {/* Material Adjunto / Attachments from teacher */}
        {activity.attachments && activity.attachments.length > 0 && (
          <div>
            <h4 className="font-display font-bold text-slate-800 text-xs uppercase tracking-wider mb-2.5">
              Material de Apoyo Adjunto por el Docente
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {activity.attachments.map((att, idx) => (
                <div
                  key={idx}
                  className="p-3 rounded-xl bg-white border border-slate-200 flex items-center justify-between gap-3 shadow-xs hover:border-[#25855A]/50 transition-all"
                >
                  <div className="flex items-center gap-2.5 min-w-0">
                    <File className="w-4 h-4 text-[#25855A] shrink-0" />
                    <div className="min-w-0">
                      <p className="text-xs font-semibold text-slate-800 truncate">
                        {att.name}
                      </p>
                      <p className="text-[10px] text-slate-400">{att.size}</p>
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => alert(`Descargando recurso: ${att.name}`)}
                    className="p-1.5 text-slate-400 hover:text-[#25855A] hover:bg-slate-50 rounded-lg transition-colors"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Rubric View Section (If activity has rubric) */}
      {activity.rubric && (
        <div>
          <h3 className="font-display font-bold text-slate-900 text-lg mb-3">
            Matriz de Evaluación por Rúbrica
          </h3>
          <RubricView
            rubric={activity.rubric}
            selectedScores={rubricScores}
            onScoreSelect={isDelivered ? undefined : handleRubricScoreSelect}
            readOnly={isDelivered}
            maxScore={activity.maxScore}
          />
        </div>
      )}

      {/* Grade & Teacher Feedback Panel (If Graded) */}
      {activity.status === 'calificada' && activity.submission?.grade !== undefined && (
        <div className="card-crema p-6 md:p-8 bg-gradient-to-br from-emerald-50/90 to-white border-emerald-200 shadow-sm space-y-4">
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-2xl bg-emerald-500 text-white flex items-center justify-center shadow-xs">
                <Sparkles className="w-6 h-6" />
              </div>
              <div>
                <span className="text-[11px] font-bold text-emerald-800 uppercase tracking-wider block">
                  Resultado Oficial de Calificación
                </span>
                <h3 className="font-display font-extrabold text-2xl text-emerald-950">
                  {activity.submission.grade.toFixed(1)} / {activity.maxScore} pts
                </h3>
              </div>
            </div>

            <div className="text-right">
              <span className="text-xs text-emerald-700 font-semibold block">
                Evaluado el{' '}
                {activity.submission.gradedAt
                  ? new Date(activity.submission.gradedAt).toLocaleDateString('es-SV', {
                      day: 'numeric',
                      month: 'short',
                    })
                  : 'Recientemente'}
              </span>
            </div>
          </div>

          {activity.submission.feedback && (
            <div className="p-4 rounded-2xl bg-white/80 border border-emerald-200/80">
              <span className="text-[10px] font-bold text-emerald-800 uppercase tracking-wider block mb-1">
                Retroalimentación del Docente:
              </span>
              <p className="text-slate-800 text-xs md:text-sm leading-relaxed">
                "{activity.submission.feedback}"
              </p>
            </div>
          )}
        </div>
      )}

      {/* Submission Form Section */}
      <div className="card-crema p-6 md:p-8 space-y-6">
        <div className="flex items-center justify-between">
          <h3 className="font-display font-bold text-slate-900 text-lg">
            {isDelivered ? 'Detalles de tu Entrega' : 'Formulario de Entrega'}
          </h3>
          {isDelivered && activity.submission?.submittedAt && (
            <span className="text-xs text-slate-500 font-medium">
              Entregado el{' '}
              {new Date(activity.submission.submittedAt).toLocaleDateString('es-SV', {
                day: 'numeric',
                month: 'short',
                hour: '2-digit',
                minute: '2-digit',
              })}
            </span>
          )}
        </div>

        <form onSubmit={handleSubmit} className="space-y-5">
          {/* Text/Comments / Links */}
          <div>
            <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
              Descripción, Enlace de Repositorio o Respuestas
            </label>
            <textarea
              rows={4}
              disabled={isDelivered}
              value={submissionText}
              onChange={(e) => setSubmissionText(e.target.value)}
              placeholder="Escribe aquí tu entrega, enlaces a repositorios (GitHub), notas sobre el desarrollo o respuestas..."
              className="input-crema resize-none disabled:bg-slate-50 disabled:text-slate-600"
            />
          </div>

          {/* File Upload Box */}
          {!isDelivered && (
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Adjuntar Archivos o Documentos
              </label>
              <div className="border-2 border-dashed border-slate-300 hover:border-[#25855A] rounded-2xl p-6 text-center bg-slate-50/50 hover:bg-emerald-50/20 transition-all cursor-pointer relative group">
                <input
                  type="file"
                  multiple
                  onChange={handleFileUpload}
                  className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
                />
                <UploadCloud className="w-8 h-8 text-slate-400 group-hover:text-[#25855A] mx-auto mb-2 transition-colors" />
                <p className="text-xs font-bold text-slate-700">
                  Arrastra tus archivos aquí o{' '}
                  <span className="text-[#25855A] underline">explora en tu equipo</span>
                </p>
                <p className="text-[11px] text-slate-400 mt-1">
                  Formatos soportados: PDF, ZIP, DOCX, FIG, PNG, MP4 (Máx. 50 MB)
                </p>
              </div>
            </div>
          )}

          {/* Attached Files List */}
          {attachedFiles.length > 0 && (
            <div className="space-y-2">
              <span className="text-xs font-bold text-slate-600 uppercase tracking-wider block">
                Archivos Adjuntos ({attachedFiles.length})
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {attachedFiles.map((file, idx) => (
                  <div
                    key={idx}
                    className="p-3 rounded-xl bg-slate-50 border border-slate-200 flex items-center justify-between gap-3 text-xs"
                  >
                    <div className="flex items-center gap-2 min-w-0">
                      <File className="w-4 h-4 text-[#25855A] shrink-0" />
                      <span className="font-semibold text-slate-800 truncate">
                        {file.name}
                      </span>
                      <span className="text-[10px] text-slate-400 shrink-0">
                        ({file.size})
                      </span>
                    </div>

                    {!isDelivered && (
                      <button
                        type="button"
                        onClick={() => handleRemoveFile(idx)}
                        className="p-1 rounded-lg text-slate-400 hover:text-red-600 hover:bg-red-50 transition-colors"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Submit Action */}
          {!isDelivered ? (
            <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs text-slate-500">
                <Info className="w-4 h-4 text-slate-400" />
                <span>Podrás revisar el estado de tu entrega en cualquier momento.</span>
              </div>

              <button
                type="submit"
                disabled={isSubmitting}
                className="btn-primary !px-6 !py-2.5 gap-2"
              >
                {isSubmitting ? (
                  <span>Enviando entrega...</span>
                ) : (
                  <>
                    <Send className="w-4 h-4" />
                    <span>Confirmar y Enviar Tarea</span>
                  </>
                )}
              </button>
            </div>
          ) : (
            <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-600 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
              <span>Esta actividad ya se encuentra entregada en el sistema.</span>
            </div>
          )}
        </form>
      </div>
    </div>
  );
};

export default LMSSubmissionForm;
