// GENERATED BY GEMINI — Campus Salesiano San José
// Módulo de Documentación Curricular, Planes Didácticos, Jornalizaciones y Rúbrica de 29 Ítems BTV Diseño Gráfico

import React, { useState, useEffect } from 'react';
import {
  Calendar,
  BookOpen,
  FileText,
  ClipboardList,
  CheckCircle2,
  Printer,
  Download,
  Plus,
  Edit3,
  Award,
  Sparkles,
  Layers,
  ArrowRight,
  ShieldCheck,
  Clock,
  HelpCircle,
  FolderPlus,
  AlertCircle,
  ExternalLink,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import {
  curriculumDocsService,
  BTV_29_RUBRIC_ITEMS,
  CSSJ_IMPORTANT_DATES_2026,
} from '../../services/curriculumDocsService';
import { lmsService } from '../../services/lmsService';
import {
  CSSJCalendarPeriod,
  CSSJJornalizacion,
  CSSJPlanDidactico,
  CSSJGuionClase,
  CSSJCuadroActividades,
  CSSJTemarioEvaluacion,
  BTVRubricCriterionItem,
  MinedLevel,
  MINED_LEVELS,
} from '../../types';

type DocTab =
  | 'guia_pasos'
  | 'calendario'
  | 'jornalizacion'
  | 'plan_didactico'
  | 'guiones'
  | 'cuadros'
  | 'temarios'
  | 'rubrica_29'
  | 'impresion';

export const CurricularDocsManager: React.FC = () => {
  const [activeTab, setActiveTab] = useState<DocTab>('guia_pasos');

  // Datasets
  const [calendarPeriods, setCalendarPeriods] = useState<CSSJCalendarPeriod[]>([]);
  const [jornalizaciones, setJornalizaciones] = useState<CSSJJornalizacion[]>([]);
  const [planesDidacticos, setPlanesDidacticos] = useState<CSSJPlanDidactico[]>([]);
  const [guionesClase, setGuionesClase] = useState<CSSJGuionClase[]>([]);
  const [cuadrosActividades, setCuadrosActividades] = useState<CSSJCuadroActividades[]>([]);
  const [temarios, setTemarios] = useState<CSSJTemarioEvaluacion[]>([]);

  // Selected items for view/edit
  const [selectedJorn, setSelectedJorn] = useState<CSSJJornalizacion | null>(null);
  const [selectedPlan, setSelectedPlan] = useState<CSSJPlanDidactico | null>(null);
  const [selectedGuion, setSelectedGuion] = useState<CSSJGuionClase | null>(null);
  const [selectedCuadro, setSelectedCuadro] = useState<CSSJCuadroActividades | null>(null);
  const [selectedTemario, setSelectedTemario] = useState<CSSJTemarioEvaluacion | null>(null);

  // 29-items rubric state
  const [rubricScores, setRubricScores] = useState<Record<string, MinedLevel>>({});
  const [selectedStudentName, setSelectedStudentName] = useState<string>('Glacer Estudiante — 1° Técnico A');
  const [selectedActivityCode, setSelectedActivityCode] = useState<string>('BTVDG1.7 — Proyecto Editorial');
  const [rubricFeedback, setRubricFeedback] = useState<string>(
    'Excelente desempeño en retícula y preprensa editorial. Se sugiere afinar la fundamentación semiótica y el costeo comercial.'
  );
  const [savedSuccessMsg, setSavedSuccessMsg] = useState<string | null>(null);

  // Filter for 29 items
  const [selectedAxisFilter, setSelectedAxisFilter] = useState<'all' | 'tecnico' | 'emprendedor' | 'humano' | 'academico'>('all');

  // Load data
  useEffect(() => {
    const load = () => {
      const c = curriculumDocsService.getCalendarPeriods();
      const j = curriculumDocsService.getJornalizaciones();
      const p = curriculumDocsService.getPlanesDidacticos();
      const g = curriculumDocsService.getGuionesClase();
      const cu = curriculumDocsService.getCuadrosActividades();
      const t = curriculumDocsService.getTemariosEvaluacion();

      setCalendarPeriods(c);
      setJornalizaciones(j);
      setPlanesDidacticos(p);
      setGuionesClase(g);
      setCuadrosActividades(cu);
      setTemarios(t);

      if (j.length > 0 && !selectedJorn) setSelectedJorn(j[0]);
      if (p.length > 0 && !selectedPlan) setSelectedPlan(p[0]);
      if (g.length > 0 && !selectedGuion) setSelectedGuion(g[0]);
      if (cu.length > 0 && !selectedCuadro) setSelectedCuadro(cu[0]);
      if (t.length > 0 && !selectedTemario) setSelectedTemario(t[0]);
    };

    load();
    const unsub = curriculumDocsService.subscribe(load);
    return () => unsub();
  }, []);

  // Initialize initial rubric scores with level 4 (Por sí mismo)
  useEffect(() => {
    const initial: Record<string, MinedLevel> = {};
    BTV_29_RUBRIC_ITEMS.forEach((item) => {
      initial[item.id] = 4;
    });
    setRubricScores(initial);
  }, []);

  // Calculate live 29 items result
  const calculatedRubric = curriculumDocsService.calculate29RubricGrade(rubricScores);

  const handleScoreChange = (itemId: string, level: MinedLevel) => {
    setRubricScores((prev) => ({
      ...prev,
      [itemId]: level,
    }));
  };

  const handleCreateCourseFromJorn = (jorn: CSSJJornalizacion) => {
    const newCourse = lmsService.addCourse({
      name: jorn.asignatura,
      code: jorn.asignatura.split(' ')[0] || 'BTV-MOD',
      description: `Módulo Técnico de ${jorn.horasAnuales}h anuales (${jorn.horasSemanales}h/sem) organizado en ${jorn.unidades.length} unidades según Jornalización CSSJ 2026.`,
      teacherName: jorn.docente,
      hours: jorn.horasAnuales,
      weeks: jorn.totalSemanas,
      gradeName: jorn.gradoSeccion,
      status: 'active',
    });

    // Create module units
    jorn.unidades.forEach((u, idx) => {
      lmsService.addModule({
        courseId: newCourse.id,
        title: `Unidad ${u.unitNumber}: ${u.title}`,
        description: `Carga horaria: ${u.classHours} horas clase (${u.totalObjectives} objetivos de aprendizaje). Periodo: ${u.fechaInicio} al ${u.fechaFin}.`,
        order: idx + 1,
        hours: u.classHours,
      });
    });

    setSavedSuccessMsg(`¡Curso y ${jorn.unidades.length} unidades creadas automáticamente en el Aula Virtual LMS!`);
    setTimeout(() => setSavedSuccessMsg(null), 4000);
  };

  const handlePrintDocument = () => {
    window.print();
  };

  const filteredCriteria = BTV_29_RUBRIC_ITEMS.filter((item) => {
    if (selectedAxisFilter === 'all') return true;
    return item.axis === selectedAxisFilter;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-5 rounded-2xl border border-slate-200/80 shadow-xs">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-[#124D37]/10 text-[#124D37] uppercase tracking-wide">
              Gestión Curricular Institucional
            </span>
            <span className="text-xs font-bold text-slate-400">•</span>
            <span className="text-xs font-semibold text-slate-600">Colegio Salesiano San José — Año Lectivo 2026</span>
          </div>
          <h1 className="font-display font-extrabold text-2xl md:text-3xl text-slate-900 mt-1">
            Planes, Jornalizaciones y Rúbricas Oficiales
          </h1>
          <p className="text-xs text-slate-500 max-w-3xl">
            Alineación total entre la documentación pedagógica salesiana (Jornalización, Plan Didáctico, Guion, Cuadros 35%, Temarios 30%) y la matriz evaluativa de 29 ítems por competencias MINED.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setActiveTab('impresion')}
            className="px-3.5 py-2 rounded-xl text-xs font-bold bg-slate-100 hover:bg-slate-200 text-slate-700 flex items-center gap-1.5 transition-colors"
          >
            <Printer className="w-4 h-4 text-slate-600" />
            <span>Vista de Impresión Oficial</span>
          </button>
        </div>
      </div>

      {/* Success alert */}
      {savedSuccessMsg && (
        <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-semibold flex items-center justify-between animate-fade-in">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-600" />
            <span>{savedSuccessMsg}</span>
          </div>
          <button onClick={() => setSavedSuccessMsg(null)} className="text-emerald-700 font-bold hover:underline">
            Cerrar
          </button>
        </div>
      )}

      {/* Document Navigation Tabs */}
      <div className="bg-white rounded-2xl border border-slate-200/80 p-1.5 flex items-center gap-1 overflow-x-auto shadow-xs">
        <button
          onClick={() => setActiveTab('guia_pasos')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'guia_pasos'
              ? 'bg-[#124D37] text-white shadow-xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <Sparkles className="w-4 h-4" />
          <span>1. Ruta Paso a Paso</span>
        </button>

        <button
          onClick={() => setActiveTab('calendario')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'calendario'
              ? 'bg-[#124D37] text-white shadow-xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <Calendar className="w-4 h-4" />
          <span>2. Calendario CSSJ 2026</span>
        </button>

        <button
          onClick={() => setActiveTab('jornalizacion')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'jornalizacion'
              ? 'bg-[#124D37] text-white shadow-xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <Clock className="w-4 h-4" />
          <span>3. Jornalización Anual</span>
        </button>

        <button
          onClick={() => setActiveTab('plan_didactico')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'plan_didactico'
              ? 'bg-[#124D37] text-white shadow-xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <BookOpen className="w-4 h-4" />
          <span>4. Plan Didáctico (Saberes)</span>
        </button>

        <button
          onClick={() => setActiveTab('guiones')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'guiones'
              ? 'bg-[#124D37] text-white shadow-xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <FileText className="w-4 h-4" />
          <span>5. Guiones de Clase</span>
        </button>

        <button
          onClick={() => setActiveTab('cuadros')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'cuadros'
              ? 'bg-[#124D37] text-white shadow-xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <ClipboardList className="w-4 h-4" />
          <span>6. Cuadros Actividades (35%)</span>
        </button>

        <button
          onClick={() => setActiveTab('temarios')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'temarios'
              ? 'bg-[#124D37] text-white shadow-xs'
              : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <HelpCircle className="w-4 h-4" />
          <span>7. Temarios (30%)</span>
        </button>

        <button
          onClick={() => setActiveTab('rubrica_29')}
          className={`px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 whitespace-nowrap transition-colors ${
            activeTab === 'rubrica_29'
              ? 'bg-[#D97706] text-white shadow-xs'
              : 'text-amber-700 bg-amber-50 hover:bg-amber-100'
          }`}
        >
          <Award className="w-4 h-4" />
          <span>8. Rúbrica 29 Ítems BTV</span>
        </button>
      </div>

      {/* ============================================================ */}
      {/* TAB 1: RUTA PASO A PASO EXPLICATIVA */}
      {/* ============================================================ */}
      {activeTab === 'guia_pasos' && (
        <div className="space-y-6 animate-fade-in">
          <div className="bg-gradient-to-r from-[#124D37] to-[#0A3022] p-6 rounded-2xl text-white shadow-md">
            <span className="text-xs font-extrabold uppercase tracking-widest text-[#E6C35C] block mb-1">
              Manual y Metodología de Alimentación Curricular 2026
            </span>
            <h2 className="font-display font-extrabold text-xl md:text-2xl">
              ¿Cómo se alimenta el Aula Virtual desde los Documentos del Colegio Salesiano San José?
            </h2>
            <p className="text-xs text-emerald-100 mt-2 max-w-3xl leading-relaxed">
              Cada documento institucional que tú o la coordinación llenan en papel o Word alimenta un componente vivo del sistema. A continuación se detalla la secuencia pedagógica exacta:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {/* Step 1 */}
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3 relative overflow-hidden">
              <div className="w-8 h-8 rounded-xl bg-blue-50 text-[#0D71B9] font-display font-bold text-sm flex items-center justify-center">
                1
              </div>
              <h3 className="font-display font-bold text-slate-900 text-sm">Calendario Académico 2026</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Establece los <strong>4 periodos/bimestres</strong> (Educación Media) o <strong>3 trimestres</strong> (Básica), fijando las fechas de actividades 35%, pruebas 30%, entrega a TBox y fichas de proyecto.
              </p>
              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-[#0D71B9] font-bold">
                <span>Alimenta: Periodos y Fechas Límite</span>
                <button onClick={() => setActiveTab('calendario')} className="hover:underline flex items-center gap-1">
                  Ver Calendario <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>

            {/* Step 2 */}
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3 relative overflow-hidden">
              <div className="w-8 h-8 rounded-xl bg-emerald-50 text-[#124D37] font-display font-bold text-sm flex items-center justify-center">
                2
              </div>
              <h3 className="font-display font-bold text-slate-900 text-sm">Jornalización Anual 2026</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Distribuye las <strong>40 semanas</strong> (200 días) y las <strong>horas anuales</strong> (160h académicas o 720h/1200h técnicas) en las 10 unidades con fechas <code>INI</code> y <code>FIN</code>.
              </p>
              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-[#124D37] font-bold">
                <span>Alimenta: Creación de Cursos y Unidades</span>
                <button onClick={() => setActiveTab('jornalizacion')} className="hover:underline flex items-center gap-1">
                  Ver Jornalización <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>

            {/* Step 3 */}
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3 relative overflow-hidden">
              <div className="w-8 h-8 rounded-xl bg-purple-50 text-purple-700 font-display font-bold text-sm flex items-center justify-center">
                3
              </div>
              <h3 className="font-display font-bold text-slate-900 text-sm">Planificación Didáctica</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Desglosa los 3 saberes MINED: <strong>Saber Conocer</strong> (Conceptuales), <strong>Saber Hacer</strong> (Procedimentales) y <strong>Saber Ser</strong> (Actitudinales) + Indicadores y APA 7.
              </p>
              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-purple-700 font-bold">
                <span>Alimenta: Contenidos y Descriptores</span>
                <button onClick={() => setActiveTab('plan_didactico')} className="hover:underline flex items-center gap-1">
                  Ver Plan Didáctico <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>

            {/* Step 4 */}
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3 relative overflow-hidden">
              <div className="w-8 h-8 rounded-xl bg-amber-50 text-amber-700 font-display font-bold text-sm flex items-center justify-center">
                4
              </div>
              <h3 className="font-display font-bold text-slate-900 text-sm">Guiones de Clase</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Estructura la secuencia didáctica diaria: <strong>Inicio (Diagnóstica)</strong>, <strong>Desarrollo (Formativa)</strong> y <strong>Cierre (Sumativa %)</strong> con adaptaciones curriculares.
              </p>
              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-amber-700 font-bold">
                <span>Alimenta: Lecciones y Prácticas</span>
                <button onClick={() => setActiveTab('guiones')} className="hover:underline flex items-center gap-1">
                  Ver Guiones <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>

            {/* Step 5 */}
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3 relative overflow-hidden">
              <div className="w-8 h-8 rounded-xl bg-rose-50 text-rose-700 font-display font-bold text-sm flex items-center justify-center">
                5
              </div>
              <h3 className="font-display font-bold text-slate-900 text-sm">Cuadro de Actividades (35%)</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Publica las subactividades ponderadas (Físicas/LMS) con sus rúbricas adjuntas y las normativas de entrega a tiempo y periodos extraordinarios del colegio.
              </p>
              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-rose-700 font-bold">
                <span>Alimenta: Tareas y Evaluaciones</span>
                <button onClick={() => setActiveTab('cuadros')} className="hover:underline flex items-center gap-1">
                  Ver Cuadros <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>

            {/* Step 6 */}
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3 relative overflow-hidden">
              <div className="w-8 h-8 rounded-xl bg-amber-500 text-white font-display font-bold text-sm flex items-center justify-center">
                6
              </div>
              <h3 className="font-display font-bold text-slate-900 text-sm">Rúbrica de 29 Ítems BTV</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Matriz de evaluación exhaustiva de <strong>Diseño Gráfico (MINED)</strong> con sus 29 criterios en los 4 Ejes (Técnico 35%, Emprendedor 25%, Humano 20%, Académico 20%).
              </p>
              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] text-amber-700 font-bold">
                <span>Alimenta: Calificación por Competencias</span>
                <button onClick={() => setActiveTab('rubrica_29')} className="hover:underline flex items-center gap-1">
                  Abrir Rúbrica 29 Ítems <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 2: CALENDARIO ACADÉMICO 2026 CSSJ */}
      {/* ============================================================ */}
      {activeTab === 'calendario' && (
        <div className="space-y-6 animate-fade-in">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="font-display font-bold text-lg text-slate-900">
                Calendario Académico Institucional 2026 — Colegio Salesiano San José
              </h2>
              <p className="text-xs text-slate-500">
                Educación Media (Bimestres/Periodos) y Educación Básica/Parvularia (Trimestres).
              </p>
            </div>
            <span className="px-3 py-1 bg-blue-50 text-[#0D71B9] text-xs font-bold rounded-lg">
              Año Lectivo 2026
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {calendarPeriods.map((period) => (
              <div key={period.id} className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3">
                <div className="flex items-center justify-between">
                  <h3 className="font-display font-bold text-slate-900 text-sm text-[#124D37]">
                    {period.name}
                  </h3>
                  <span className="text-[11px] font-bold px-2 py-0.5 bg-slate-100 rounded text-slate-600">
                    Nivel: {period.level}
                  </span>
                </div>

                <div className="space-y-2 text-xs">
                  <div className="flex items-center justify-between p-2 rounded-lg bg-slate-50">
                    <span className="text-slate-600 font-semibold">1ª Actividad (35%):</span>
                    <span className="font-bold text-slate-800">
                      {period.actividad1_35?.inicio} al {period.actividad1_35?.fin}
                    </span>
                  </div>

                  <div className="flex items-center justify-between p-2 rounded-lg bg-slate-50">
                    <span className="text-slate-600 font-semibold">2ª Actividad (35%):</span>
                    <span className="font-bold text-slate-800">
                      {period.actividad2_35?.inicio} al {period.actividad2_35?.fin}
                    </span>
                  </div>

                  <div className="flex items-center justify-between p-2 rounded-lg bg-amber-50/60 text-amber-900">
                    <span className="font-semibold">Refuerzo Académico:</span>
                    <span className="font-bold">
                      {period.refuerzo?.inicio} al {period.refuerzo?.fin}
                    </span>
                  </div>

                  <div className="flex items-center justify-between p-2 rounded-lg bg-blue-50/60 text-blue-900">
                    <span className="font-semibold">Pruebas Objetivas (30%):</span>
                    <span className="font-bold">
                      {period.pruebaObjetiva_30?.inicio} al {period.pruebaObjetiva_30?.fin}
                    </span>
                  </div>

                  <div className="flex items-center justify-between p-2 rounded-lg bg-emerald-50 text-emerald-900">
                    <span className="font-semibold">Entrega de Boletas:</span>
                    <span className="font-bold">{period.boletasCalificaciones}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Important salesian dates */}
          <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-4">
            <h3 className="font-display font-bold text-slate-900 text-sm flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-[#D97706]" />
              <span>Hitos y Fiestas Salesianas en la Jornalización 2026</span>
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {CSSJ_IMPORTANT_DATES_2026.map((dateItem, idx) => (
                <div key={idx} className="p-3 rounded-xl bg-slate-50 border border-slate-100 flex items-start gap-3">
                  <div className="w-12 h-10 rounded-lg bg-[#124D37] text-white flex flex-col items-center justify-center font-display leading-tight shrink-0">
                    <span className="text-[10px] uppercase">{dateItem.mes.slice(0, 3)}</span>
                    <span className="text-xs font-extrabold">{dateItem.dia}</span>
                  </div>
                  <div>
                    <span className="text-xs font-bold text-slate-800 block leading-tight">{dateItem.evento}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 3: JORNALIZACIÓN ANUAL 2026 */}
      {/* ============================================================ */}
      {activeTab === 'jornalizacion' && (
        <div className="space-y-6 animate-fade-in">
          {/* Selector */}
          <div className="flex flex-wrap items-center justify-between gap-3 bg-white p-4 rounded-2xl border border-slate-200">
            <div className="flex items-center gap-3">
              <span className="text-xs font-bold text-slate-500">Seleccionar Jornalización:</span>
              <select
                value={selectedJorn?.id || ''}
                onChange={(e) => {
                  const j = jornalizaciones.find((item) => item.id === e.target.value);
                  if (j) setSelectedJorn(j);
                }}
                className="px-3 py-1.5 rounded-xl border border-slate-200 text-xs font-bold text-slate-800 bg-white"
              >
                {jornalizaciones.map((j) => (
                  <option key={j.id} value={j.id}>
                    {j.asignatura} — {j.gradoSeccion}
                  </option>
                ))}
              </select>
            </div>

            {selectedJorn && (
              <button
                onClick={() => handleCreateCourseFromJorn(selectedJorn)}
                className="px-4 py-2 rounded-xl bg-[#124D37] text-white text-xs font-bold flex items-center gap-2 hover:bg-[#0E3D2B] transition-colors shadow-xs"
              >
                <FolderPlus className="w-4 h-4" />
                <span>Generar Curso y Módulos en LMS desde esta Jornalización</span>
              </button>
            )}
          </div>

          {selectedJorn && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-6">
              {/* Document Header CSSJ Style */}
              <div className="border-b border-slate-200 pb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <span className="text-xs font-extrabold text-[#124D37] uppercase tracking-wider block">
                    Colegio Salesiano San José • Santa Ana
                  </span>
                  <h3 className="font-display font-extrabold text-xl text-slate-900">
                    Jornalización Anual — Año Escolar Lectivo 2026
                  </h3>
                  <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-600 mt-2">
                    <span><strong>Docente:</strong> {selectedJorn.docente}</span>
                    <span><strong>Grado y Sección:</strong> {selectedJorn.gradoSeccion}</span>
                    <span><strong>Asignatura/Módulo:</strong> {selectedJorn.asignatura}</span>
                  </div>
                </div>

                <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 text-right">
                  <div className="text-xs text-slate-500 font-semibold">Total Semanas / Días</div>
                  <div className="text-base font-black text-[#124D37]">
                    {selectedJorn.totalSemanas} Semanas • {selectedJorn.totalDias} Días
                  </div>
                  <div className="text-[11px] text-slate-500 font-bold">
                    {selectedJorn.horasSemanales}h/sem • {selectedJorn.horasAnuales}h anuales
                  </div>
                </div>
              </div>

              {/* Trimestres Schedule */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="p-3 rounded-xl bg-blue-50/50 border border-blue-100 text-xs">
                  <span className="font-bold text-[#0D71B9] block">Trimestre 1</span>
                  <span className="text-slate-700">Inicio: <strong>{selectedJorn.trimestre1.inicio}</strong></span>
                  <br />
                  <span className="text-slate-700">Finalización: <strong>{selectedJorn.trimestre1.fin}</strong></span>
                </div>
                <div className="p-3 rounded-xl bg-blue-50/50 border border-blue-100 text-xs">
                  <span className="font-bold text-[#0D71B9] block">Trimestre 2</span>
                  <span className="text-slate-700">Inicio: <strong>{selectedJorn.trimestre2.inicio}</strong></span>
                  <br />
                  <span className="text-slate-700">Finalización: <strong>{selectedJorn.trimestre2.fin}</strong></span>
                </div>
                <div className="p-3 rounded-xl bg-blue-50/50 border border-blue-100 text-xs">
                  <span className="font-bold text-[#0D71B9] block">Trimestre 3</span>
                  <span className="text-slate-700">Inicio: <strong>{selectedJorn.trimestre3.inicio}</strong></span>
                  <br />
                  <span className="text-slate-700">Finalización: <strong>{selectedJorn.trimestre3.fin}</strong></span>
                </div>
              </div>

              {/* Units Table (Exact format of CSSJ) */}
              <div>
                <h4 className="font-display font-bold text-slate-900 text-sm mb-3">
                  Distribución de Horas Clase y Fechas por Unidad ({selectedJorn.unidades.length} Unidades)
                </h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
                    <thead className="bg-[#124D37] text-white">
                      <tr>
                        <th className="p-3 text-center w-12">N°</th>
                        <th className="p-3">Nombre de la Unidad / Módulo</th>
                        <th className="p-3 text-center">Objetivos</th>
                        <th className="p-3 text-center">Horas Clase</th>
                        <th className="p-3 text-center">Fecha Inicio</th>
                        <th className="p-3 text-center">Fecha Fin</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {selectedJorn.unidades.map((u) => (
                        <tr key={u.unitNumber} className="hover:bg-slate-50 transition-colors">
                          <td className="p-3 text-center font-bold text-slate-500 bg-slate-50">
                            {u.unitNumber}
                          </td>
                          <td className="p-3 font-semibold text-slate-800">{u.title}</td>
                          <td className="p-3 text-center font-bold text-slate-600">{u.totalObjectives}</td>
                          <td className="p-3 text-center font-bold text-[#124D37]">{u.classHours}h</td>
                          <td className="p-3 text-center font-medium text-slate-600">{u.fechaInicio}</td>
                          <td className="p-3 text-center font-medium text-slate-600">{u.fechaFin}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 4: PLANIFICACIÓN DIDÁCTICA 2026 */}
      {/* ============================================================ */}
      {activeTab === 'plan_didactico' && (
        <div className="space-y-6 animate-fade-in">
          {/* Selector */}
          <div className="flex items-center justify-between bg-white p-4 rounded-2xl border border-slate-200">
            <div className="flex items-center gap-3">
              <span className="text-xs font-bold text-slate-500">Plan Didáctico:</span>
              <select
                value={selectedPlan?.id || ''}
                onChange={(e) => {
                  const p = planesDidacticos.find((item) => item.id === e.target.value);
                  if (p) setSelectedPlan(p);
                }}
                className="px-3 py-1.5 rounded-xl border border-slate-200 text-xs font-bold text-slate-800 bg-white"
              >
                {planesDidacticos.map((p) => (
                  <option key={p.id} value={p.id}>
                    Unidad {p.unidadNumero}: {p.unidadNombre} ({p.asignatura})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {selectedPlan && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-6">
              {/* Official Header */}
              <div className="border-b border-slate-200 pb-4">
                <span className="text-xs font-extrabold text-[#124D37] uppercase tracking-wider block">
                  Colegio Salesiano San José
                </span>
                <h3 className="font-display font-extrabold text-xl text-slate-900">
                  Planificación Didáctica 2026 — {selectedPlan.grado} "{selectedPlan.seccion}"
                </h3>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs text-slate-600 mt-3 p-3 bg-slate-50 rounded-xl">
                  <div><strong>Docente:</strong> {selectedPlan.docente}</div>
                  <div><strong>Asignatura:</strong> {selectedPlan.asignatura}</div>
                  <div><strong>Periodo:</strong> {selectedPlan.trimestrePeriodo}</div>
                  <div><strong>Tiempo:</strong> {selectedPlan.tiempoHoras} horas</div>
                </div>
              </div>

              {/* Competencias */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-4 rounded-xl bg-blue-50/50 border border-blue-100 space-y-1">
                  <span className="text-xs font-bold text-[#0D71B9] uppercase tracking-wider block">
                    Competencias de la Asignatura
                  </span>
                  <p className="text-xs text-slate-700 leading-relaxed">{selectedPlan.competenciasAsignatura}</p>
                </div>
                <div className="p-4 rounded-xl bg-emerald-50/50 border border-emerald-100 space-y-1">
                  <span className="text-xs font-bold text-[#124D37] uppercase tracking-wider block">
                    Competencias de la Unidad
                  </span>
                  <p className="text-xs text-slate-700 leading-relaxed">{selectedPlan.competenciasUnidad}</p>
                </div>
              </div>

              {/* 3 Saberes MINEDUCYT (Conocer, Hacer, Ser) */}
              <div>
                <h4 className="font-display font-bold text-slate-900 text-sm mb-3 flex items-center gap-2">
                  <Layers className="w-4 h-4 text-[#124D37]" />
                  <span>Contenidos Curriculares por Ejes de Saberes (Extraídos del programa MINEDUCYT)</span>
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {/* Conocer */}
                  <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                    <span className="text-xs font-extrabold text-[#0D71B9] uppercase tracking-wider block border-b border-slate-200 pb-1">
                      Contenidos Conceptuales (Saber Conocer)
                    </span>
                    <ul className="space-y-1.5 text-xs text-slate-700 list-disc list-inside">
                      {selectedPlan.contenidosConceptuales.map((c, i) => (
                        <li key={i} className="leading-tight">{c}</li>
                      ))}
                    </ul>
                  </div>

                  {/* Hacer */}
                  <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                    <span className="text-xs font-extrabold text-[#124D37] uppercase tracking-wider block border-b border-slate-200 pb-1">
                      Contenidos Procedimentales (Saber Hacer)
                    </span>
                    <ul className="space-y-1.5 text-xs text-slate-700 list-disc list-inside">
                      {selectedPlan.contenidosProcedimentales.map((c, i) => (
                        <li key={i} className="leading-tight">{c}</li>
                      ))}
                    </ul>
                  </div>

                  {/* Ser */}
                  <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                    <span className="text-xs font-extrabold text-[#D97706] uppercase tracking-wider block border-b border-slate-200 pb-1">
                      Contenidos Actitudinales (Saber Ser)
                    </span>
                    <ul className="space-y-1.5 text-xs text-slate-700 list-disc list-inside">
                      {selectedPlan.contenidosActitudinales.map((c, i) => (
                        <li key={i} className="leading-tight">{c}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>

              {/* Indicadores de logro */}
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                <span className="text-xs font-bold text-slate-900 uppercase tracking-wider block">
                  Indicadores de Logro (MINEDUCYT)
                </span>
                <div className="space-y-1.5 text-xs text-slate-700">
                  {selectedPlan.indicadoresLogro.map((ind, i) => (
                    <div key={i} className="flex items-start gap-2">
                      <CheckCircle2 className="w-4 h-4 text-[#124D37] shrink-0 mt-0.5" />
                      <span>{ind}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Bibliografía APA 7 */}
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2">
                <span className="text-xs font-bold text-slate-900 uppercase tracking-wider block">
                  Bibliografía y Egrafía Oficial (Normas APA 7ma Edición)
                </span>
                <ul className="space-y-1 text-xs text-slate-600 italic">
                  {selectedPlan.bibliografiaEgrafia.map((b, i) => (
                    <li key={i}>• {b}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 5: GUIONES DE CLASE */}
      {/* ============================================================ */}
      {activeTab === 'guiones' && (
        <div className="space-y-6 animate-fade-in">
          {selectedGuion && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-6">
              <div className="border-b border-slate-200 pb-4">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-extrabold text-[#124D37] uppercase tracking-wider block">
                    Colegio Salesiano San José
                  </span>
                  <span className="text-xs font-bold text-slate-500">Fecha: {selectedGuion.fecha}</span>
                </div>
                <h3 className="font-display font-extrabold text-xl text-slate-900">
                  Guion de Clase 2026 — {selectedGuion.contenido}
                </h3>
                <div className="flex flex-wrap gap-4 text-xs text-slate-600 mt-2">
                  <span><strong>Docente:</strong> {selectedGuion.docente}</span>
                  <span><strong>Grado y Sección:</strong> {selectedGuion.gradoSeccion}</span>
                  <span><strong>Tiempo:</strong> {selectedGuion.tiempoMinutos} min</span>
                </div>
              </div>

              {/* Situaciones de Aprendizaje vs Evaluación */}
              <div className="space-y-4">
                <h4 className="font-display font-bold text-slate-900 text-sm">
                  Secuencia Didáctica: Situaciones de Aprendizaje vs. Evaluación
                </h4>

                {/* Inicio */}
                <div className="p-4 rounded-xl bg-blue-50/40 border border-blue-100 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-[#0D71B9] uppercase">1. Inicio</span>
                    <span className="text-[11px] font-bold px-2 py-0.5 bg-blue-100 text-[#0D71B9] rounded">
                      {selectedGuion.inicio.tipoEvaluacion}
                    </span>
                  </div>
                  <p className="text-xs text-slate-800 leading-relaxed font-medium">{selectedGuion.inicio.situacion}</p>
                  <p className="text-[11px] text-slate-500 italic">{selectedGuion.inicio.estrategia}</p>
                </div>

                {/* Desarrollo */}
                <div className="p-4 rounded-xl bg-emerald-50/40 border border-emerald-100 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-[#124D37] uppercase">2. Desarrollo</span>
                    <span className="text-[11px] font-bold px-2 py-0.5 bg-emerald-100 text-[#124D37] rounded">
                      {selectedGuion.desarrollo.tipoEvaluacion}
                    </span>
                  </div>
                  <p className="text-xs text-slate-800 leading-relaxed font-medium">{selectedGuion.desarrollo.situacion}</p>
                  <p className="text-[11px] text-slate-500 italic">{selectedGuion.desarrollo.estrategia}</p>
                </div>

                {/* Cierre */}
                <div className="p-4 rounded-xl bg-amber-50/40 border border-amber-100 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-amber-800 uppercase">3. Cierre / Finalización</span>
                    <span className="text-[11px] font-bold px-2 py-0.5 bg-amber-100 text-amber-800 rounded">
                      {selectedGuion.cierre.tipoEvaluacion} ({selectedGuion.cierre.ponderacionPorcentaje}%)
                    </span>
                  </div>
                  <p className="text-xs text-slate-800 leading-relaxed font-medium">{selectedGuion.cierre.situacion}</p>
                  <p className="text-[11px] text-slate-600">{selectedGuion.cierre.propuestaActividades}</p>
                  <p className="text-[11px] text-slate-500 italic">Análisis de Desempeño: {selectedGuion.cierre.analisisDesempeno}</p>
                </div>
              </div>

              {/* Adaptaciones curriculares & Tarea */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
                  <span className="font-bold text-slate-900 block mb-1">Adaptaciones Curriculares:</span>
                  <p className="text-slate-600">{selectedGuion.adaptacionesCurriculares}</p>
                </div>
                <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
                  <span className="font-bold text-slate-900 block mb-1">Tarea para Casa:</span>
                  <p className="text-slate-600">{selectedGuion.tarea}</p>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 6: CUADRO DE ACTIVIDADES (35%) */}
      {/* ============================================================ */}
      {activeTab === 'cuadros' && (
        <div className="space-y-6 animate-fade-in">
          {selectedCuadro && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-6">
              <div className="border-b border-slate-200 pb-4">
                <span className="text-xs font-extrabold text-[#124D37] uppercase tracking-wider block">
                  {selectedCuadro.centroEducativo}
                </span>
                <h3 className="font-display font-extrabold text-xl text-slate-900">
                  Cuadro de Actividades — {selectedCuadro.nivelEducativo} ({selectedCuadro.gradoSeccion})
                </h3>
                <div className="flex flex-wrap gap-4 text-xs text-slate-600 mt-2">
                  <span><strong>Docente:</strong> {selectedCuadro.docente}</span>
                  <span><strong>Trimestre:</strong> {selectedCuadro.trimestrePeriodo}</span>
                  <span><strong>Actividad:</strong> {selectedCuadro.actividadTitulo}</span>
                  <span><strong>Fechas:</strong> {selectedCuadro.fechaRango}</span>
                </div>
              </div>

              {/* Subactivities Table */}
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
                  <thead className="bg-[#124D37] text-white">
                    <tr>
                      <th className="p-3 text-center w-12">N°</th>
                      <th className="p-3">Nombre de la Subactividad</th>
                      <th className="p-3">Descripción de la Tarea</th>
                      <th className="p-3">Criterios de Evaluación</th>
                      <th className="p-3 text-center">Formato</th>
                      <th className="p-3 text-center">%</th>
                      <th className="p-3 text-center">Fecha Entrega</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {selectedCuadro.subactividades.map((sub) => (
                      <tr key={sub.no} className="hover:bg-slate-50 transition-colors">
                        <td className="p-3 text-center font-bold text-slate-500 bg-slate-50">{sub.no}</td>
                        <td className="p-3 font-bold text-slate-900">{sub.nombre}</td>
                        <td className="p-3 text-slate-700 leading-relaxed">{sub.descripcion}</td>
                        <td className="p-3 text-slate-600">{sub.criteriosEvaluacion}</td>
                        <td className="p-3 text-center">
                          <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-50 text-[#0D71B9]">
                            {sub.formato}
                          </span>
                        </td>
                        <td className="p-3 text-center font-black text-[#124D37]">{sub.porcentaje}%</td>
                        <td className="p-3 text-center font-semibold text-slate-700">{sub.fechaEntrega}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Indications of General Academic Coordination */}
              <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-900 space-y-2">
                <span className="font-bold uppercase tracking-wider block text-amber-950 flex items-center gap-1.5">
                  <AlertCircle className="w-4 h-4 text-amber-700" />
                  <span>Indicaciones Dirigidas desde Coordinación Académica General:</span>
                </span>
                <ul className="list-disc list-inside space-y-1 text-slate-700">
                  <li>{selectedCuadro.indicacionesCoordinacion.politicaRetraso}</li>
                  <li>{selectedCuadro.indicacionesCoordinacion.limiteDias}</li>
                  <li>{selectedCuadro.indicacionesCoordinacion.periodoExtraordinario}</li>
                  <li>{selectedCuadro.indicacionesCoordinacion.manualConvivencia}</li>
                </ul>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 7: TEMARIOS DE EVALUACIÓN (30%) */}
      {/* ============================================================ */}
      {activeTab === 'temarios' && (
        <div className="space-y-6 animate-fade-in">
          {selectedTemario && (
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-6">
              <div className="border-b border-slate-200 pb-4">
                <span className="text-xs font-extrabold text-[#124D37] uppercase tracking-wider block">
                  Colegio Salesiano San José
                </span>
                <h3 className="font-display font-extrabold text-xl text-slate-900">
                  Temario de Contenidos a Evaluar — Prueba Ordinaria ({selectedTemario.porcentaje})
                </h3>
                <div className="flex flex-wrap gap-4 text-xs text-slate-600 mt-2">
                  <span><strong>Docente:</strong> {selectedTemario.docente}</span>
                  <span><strong>Asignatura:</strong> {selectedTemario.asignatura}</span>
                  <span><strong>Periodo:</strong> {selectedTemario.periodoTrimestre}</span>
                  <span><strong>Comprende:</strong> {selectedTemario.periodoComprendido}</span>
                </div>
              </div>

              {/* Contents list */}
              <div>
                <h4 className="font-display font-bold text-slate-900 text-sm mb-3">
                  Contenidos a Evaluar en la Prueba de Periodo
                </h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
                    <thead className="bg-[#124D37] text-white">
                      <tr>
                        <th className="p-3 w-12 text-center">N°</th>
                        <th className="p-3">Contenido a Evaluar</th>
                        <th className="p-3">N° de Página o Especificación</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {selectedTemario.contenidosAEvaluar.map((c, i) => (
                        <tr key={i} className="hover:bg-slate-50 transition-colors">
                          <td className="p-3 text-center font-bold text-slate-500 bg-slate-50">{i + 1}</td>
                          <td className="p-3 font-semibold text-slate-800">{c.contenido}</td>
                          <td className="p-3 text-slate-600 font-medium">{c.paginaEspecificacion}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* General Indications */}
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs">
                <span className="font-bold text-slate-900 block mb-1">Indicaciones Generales para el Estudiante:</span>
                <p className="text-slate-600">{selectedTemario.indicacionesGenerales}</p>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 8: RÚBRICA COMPLETA DE 29 ÍTEMS BTV DISEÑO GRÁFICO */}
      {/* ============================================================ */}
      {activeTab === 'rubrica_29' && (
        <div className="space-y-6 animate-fade-in">
          {/* Header & live score calculation card */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-7 space-y-2">
              <span className="px-2.5 py-0.5 rounded-full text-[11px] font-extrabold bg-amber-100 text-amber-900 uppercase tracking-wide inline-block">
                Evaluación Oficial de Especialidad MINED
              </span>
              <h2 className="font-display font-extrabold text-xl md:text-2xl text-slate-900">
                Rúbrica Normativa de 29 Ítems Técnicos y Humanos
              </h2>
              <p className="text-xs text-slate-500 leading-relaxed">
                Bachillerato Técnico Vocacional en Diseño Gráfico. Evaluación por competencias en escala 1 al 5 en los 4 Ejes de Desarrollo Vocacional.
              </p>

              <div className="flex flex-wrap items-center gap-3 pt-2">
                <div className="text-xs">
                  <span className="text-slate-500 font-semibold block">Estudiante a Calificar:</span>
                  <input
                    type="text"
                    value={selectedStudentName}
                    onChange={(e) => setSelectedStudentName(e.target.value)}
                    className="px-3 py-1.5 rounded-xl border border-slate-200 text-xs font-bold text-slate-800 bg-slate-50"
                  />
                </div>
                <div className="text-xs">
                  <span className="text-slate-500 font-semibold block">Actividad/Entrega:</span>
                  <input
                    type="text"
                    value={selectedActivityCode}
                    onChange={(e) => setSelectedActivityCode(e.target.value)}
                    className="px-3 py-1.5 rounded-xl border border-slate-200 text-xs font-bold text-slate-800 bg-slate-50"
                  />
                </div>
              </div>
            </div>

            {/* Live Score Summary */}
            <div className="lg:col-span-5 bg-gradient-to-br from-slate-900 to-slate-800 p-5 rounded-2xl text-white flex flex-col justify-between shadow-md">
              <div>
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                    Nota Global Ponderada
                  </span>
                  <span
                    className={`text-xs font-extrabold px-2.5 py-0.5 rounded-full ${
                      calculatedRubric.approved ? 'bg-emerald-500/20 text-emerald-300' : 'bg-rose-500/20 text-rose-300'
                    }`}
                  >
                    {calculatedRubric.approved ? 'APROBADO' : 'REQUIERE REFUERZO'}
                  </span>
                </div>
                <div className="flex items-baseline gap-3 mt-1">
                  <span className="font-display font-black text-4xl text-amber-400">
                    {calculatedRubric.weightedGrade.toFixed(1)}
                  </span>
                  <span className="text-xs text-slate-400">/ 10.0 pts</span>
                  <span className="text-xs font-bold text-emerald-400 ml-auto">
                    Nivel {calculatedRubric.finalMinedLevel} MINED
                  </span>
                </div>
              </div>

              {/* 4 axes breakdown */}
              <div className="grid grid-cols-2 gap-2 pt-3 border-t border-slate-700/60 text-xs">
                <div>
                  <span className="text-slate-400 text-[10px] block">Técnico (35%):</span>
                  <span className="font-extrabold text-blue-300">{calculatedRubric.scoreTecnico.toFixed(1)} pts</span>
                </div>
                <div>
                  <span className="text-slate-400 text-[10px] block">Emprendedor (25%):</span>
                  <span className="font-extrabold text-amber-300">{calculatedRubric.scoreEmprendedor.toFixed(1)} pts</span>
                </div>
                <div>
                  <span className="text-slate-400 text-[10px] block">Humano (20%):</span>
                  <span className="font-extrabold text-emerald-300">{calculatedRubric.scoreHumano.toFixed(1)} pts</span>
                </div>
                <div>
                  <span className="text-slate-400 text-[10px] block">Académico (20%):</span>
                  <span className="font-extrabold text-purple-300">{calculatedRubric.scoreAcademico.toFixed(1)} pts</span>
                </div>
              </div>
            </div>
          </div>

          {/* Filter axis pills */}
          <div className="flex items-center gap-2 overflow-x-auto pb-1">
            <button
              onClick={() => setSelectedAxisFilter('all')}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-colors ${
                selectedAxisFilter === 'all'
                  ? 'bg-slate-900 text-white'
                  : 'bg-white border border-slate-200 text-slate-700 hover:bg-slate-50'
              }`}
            >
              Todos los 29 Ítems
            </button>
            <button
              onClick={() => setSelectedAxisFilter('tecnico')}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-colors ${
                selectedAxisFilter === 'tecnico'
                  ? 'bg-blue-600 text-white'
                  : 'bg-blue-50 text-blue-700 hover:bg-blue-100'
              }`}
            >
              Eje Técnico (9 Ítems - 35%)
            </button>
            <button
              onClick={() => setSelectedAxisFilter('emprendedor')}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-colors ${
                selectedAxisFilter === 'emprendedor'
                  ? 'bg-amber-600 text-white'
                  : 'bg-amber-50 text-amber-800 hover:bg-amber-100'
              }`}
            >
              Eje Emprendedor (7 Ítems - 25%)
            </button>
            <button
              onClick={() => setSelectedAxisFilter('humano')}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-colors ${
                selectedAxisFilter === 'humano'
                  ? 'bg-emerald-600 text-white'
                  : 'bg-emerald-50 text-emerald-800 hover:bg-emerald-100'
              }`}
            >
              Eje Humano-Social (7 Ítems - 20%)
            </button>
            <button
              onClick={() => setSelectedAxisFilter('academico')}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-colors ${
                selectedAxisFilter === 'academico'
                  ? 'bg-purple-600 text-white'
                  : 'bg-purple-50 text-purple-800 hover:bg-purple-100'
              }`}
            >
              Eje Académico Aplicado (6 Ítems - 20%)
            </button>
          </div>

          {/* 29 Items Cards */}
          <div className="space-y-4">
            {filteredCriteria.map((item, index) => {
              const currentLevel = rubricScores[item.id] || 4;
              return (
                <div
                  key={item.id}
                  className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3"
                >
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 pb-2">
                    <div className="flex items-center gap-2">
                      <span className="w-8 h-8 rounded-xl bg-slate-900 text-white font-display font-bold text-xs flex items-center justify-center">
                        {item.code}
                      </span>
                      <div>
                        <h4 className="font-display font-bold text-slate-900 text-sm">{item.name}</h4>
                        <span className="text-[11px] font-semibold text-slate-400">
                          {item.axisLabel} ({item.weightPercentage}%)
                        </span>
                      </div>
                    </div>

                    <div className="flex items-center gap-2 self-end sm:self-center">
                      <span className="text-[11px] font-bold text-slate-500">Nivel Asignado:</span>
                      <span className="px-2.5 py-0.5 rounded-lg text-xs font-black bg-[#124D37] text-white">
                        Nivel {currentLevel}
                      </span>
                    </div>
                  </div>

                  <p className="text-xs text-slate-600 leading-relaxed">{item.description}</p>

                  {/* Level 1 to 5 selector pills */}
                  <div className="grid grid-cols-1 sm:grid-cols-5 gap-2 pt-2">
                    {([1, 2, 3, 4, 5] as MinedLevel[]).map((lvl) => {
                      const isSelected = currentLevel === lvl;
                      let descriptor = '';
                      if (lvl === 1) descriptor = item.descriptorNivel1;
                      if (lvl === 2) descriptor = item.descriptorNivel2;
                      if (lvl === 3) descriptor = item.descriptorNivel3;
                      if (lvl === 4) descriptor = item.descriptorNivel4;
                      if (lvl === 5) descriptor = item.descriptorNivel5;

                      return (
                        <button
                          key={lvl}
                          type="button"
                          onClick={() => handleScoreChange(item.id, lvl)}
                          className={`p-2.5 rounded-xl text-left text-xs transition-all flex flex-col justify-between ${
                            isSelected
                              ? 'bg-[#124D37] text-white ring-2 ring-[#124D37] shadow-sm font-semibold'
                              : 'bg-slate-50 text-slate-700 hover:bg-slate-100 border border-slate-200/70'
                          }`}
                        >
                          <div className="flex items-center justify-between mb-1">
                            <span className="font-bold text-[11px]">Nivel {lvl}</span>
                            <span className={`text-[10px] ${isSelected ? 'text-emerald-200' : 'text-slate-400'}`}>
                              {lvl === 1 ? '4.0' : lvl === 2 ? '5.5' : lvl === 3 ? '6.5' : lvl === 4 ? '8.5' : '10.0'} pts
                            </span>
                          </div>
                          <span className={`text-[10px] leading-tight line-clamp-3 ${isSelected ? 'text-emerald-100' : 'text-slate-500'}`}>
                            {descriptor}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Feedback & Save */}
          <div className="bg-white p-5 rounded-2xl border border-slate-200 space-y-3 shadow-xs">
            <h4 className="font-display font-bold text-slate-900 text-sm">
              Retroalimentación Formativa Cualitativa del Docente
            </h4>
            <textarea
              rows={3}
              value={rubricFeedback}
              onChange={(e) => setRubricFeedback(e.target.value)}
              className="w-full p-3 text-xs rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#124D37]"
              placeholder="Escribe observaciones formativas basadas en los 29 ítems..."
            />
            <div className="flex justify-end">
              <button
                onClick={() => {
                  setSavedSuccessMsg(`¡Evaluación de 29 ítems guardada con éxito para ${selectedStudentName}! Nota: ${calculatedRubric.weightedGrade.toFixed(1)} / 10.0 (Nivel ${calculatedRubric.finalMinedLevel} MINED).`);
                  setTimeout(() => setSavedSuccessMsg(null), 4000);
                }}
                className="px-5 py-2.5 rounded-xl bg-[#124D37] text-white text-xs font-bold flex items-center gap-2 hover:bg-[#0E3D2B] transition-colors shadow-sm"
              >
                <Award className="w-4 h-4" />
                <span>Guardar y Asignar Calificación Oficial de 29 Ítems</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ============================================================ */}
      {/* TAB 9: VISTA OFICIAL DE IMPRESIÓN CON MEMBRETE CSSJ */}
      {/* ============================================================ */}
      {activeTab === 'impresion' && (
        <div className="space-y-6 animate-fade-in bg-white p-8 rounded-2xl border border-slate-300 shadow-md print:p-0 print:border-none print:shadow-none">
          {/* Action bar (hidden on print) */}
          <div className="flex items-center justify-between pb-4 border-b border-slate-200 print:hidden">
            <span className="text-xs font-bold text-slate-600">
              Vista previa para imprimir documentos oficiales del Colegio Salesiano San José
            </span>
            <button
              onClick={handlePrintDocument}
              className="px-4 py-2 rounded-xl bg-[#124D37] text-white text-xs font-bold flex items-center gap-2 hover:bg-[#0E3D2B] shadow-sm"
            >
              <Printer className="w-4 h-4" />
              <span>Imprimir / Guardar en PDF</span>
            </button>
          </div>

          {/* Institutional Letterhead */}
          <div className="text-center space-y-1 border-b-2 border-[#124D37] pb-4">
            <div className="text-xs font-extrabold text-[#124D37] uppercase tracking-widest">
              COLEGIO SALESIANO SAN JOSÉ • SANTA ANA, EL SALVADOR
            </div>
            <h2 className="font-display font-black text-xl md:text-2xl text-slate-900">
              DOCUMENTACIÓN CURRICULAR Y EVALUATIVA — 2026
            </h2>
            <p className="text-xs text-slate-600">
              Bachillerato Técnico Vocacional en Diseño Gráfico & Educación Básica
            </p>
          </div>

          {/* Printable Body Content */}
          <div className="space-y-6 text-xs text-slate-800 pt-2">
            <div className="grid grid-cols-2 gap-4 p-3 bg-slate-50 rounded-xl border border-slate-200">
              <div><strong>Docente:</strong> Lic. Alexander Gómez</div>
              <div><strong>Año Escolar:</strong> 2026 (40 Semanas / 200 Días)</div>
              <div><strong>Especialidad:</strong> Diseño Gráfico (MINED)</div>
              <div><strong>Sede:</strong> Final 17 Av. Sur, Cantón Loma Alta, Santa Ana</div>
            </div>

            {/* Document summary table */}
            <div className="space-y-2">
              <h3 className="font-bold text-slate-900 uppercase">Estructura Curricular Aprobada:</h3>
              <table className="w-full text-left border border-slate-300">
                <thead className="bg-slate-100">
                  <tr>
                    <th className="p-2 border border-slate-300">Documento Oficial</th>
                    <th className="p-2 border border-slate-300">Finalidad Institucional</th>
                    <th className="p-2 border border-slate-300 text-center">Estado</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="p-2 border border-slate-300 font-semibold">1. Calendario Académico 2026</td>
                    <td className="p-2 border border-slate-300">Distribución de los 4 periodos de Media y 3 trimestres de Básica.</td>
                    <td className="p-2 border border-slate-300 text-center font-bold text-emerald-700">Vigente</td>
                  </tr>
                  <tr>
                    <td className="p-2 border border-slate-300 font-semibold">2. Jornalización Anual (40 Semanas)</td>
                    <td className="p-2 border border-slate-300">Cálculo de horas anuales (720h/1200h) y fechas de inicio/fin por unidad.</td>
                    <td className="p-2 border border-slate-300 text-center font-bold text-emerald-700">Aprobada</td>
                  </tr>
                  <tr>
                    <td className="p-2 border border-slate-300 font-semibold">3. Planificación Didáctica</td>
                    <td className="p-2 border border-slate-300">Desglose de Saber Conocer, Saber Hacer, Saber Ser e Indicadores de logro.</td>
                    <td className="p-2 border border-slate-300 text-center font-bold text-emerald-700">Aprobada</td>
                  </tr>
                  <tr>
                    <td className="p-2 border border-slate-300 font-semibold">4. Guiones de Clase</td>
                    <td className="p-2 border border-slate-300">Secuencia de Inicio (Diagnóstica), Desarrollo (Formativa) y Cierre (Sumativa).</td>
                    <td className="p-2 border border-slate-300 text-center font-bold text-emerald-700">Aprobada</td>
                  </tr>
                  <tr>
                    <td className="p-2 border border-slate-300 font-semibold">5. Cuadro de Actividades 35%</td>
                    <td className="p-2 border border-slate-300">Subactividades formativas y normativas de entrega del CSSJ.</td>
                    <td className="p-2 border border-slate-300 text-center font-bold text-emerald-700">Aprobada</td>
                  </tr>
                  <tr>
                    <td className="p-2 border border-slate-300 font-semibold">6. Rúbrica Normativa de 29 Ítems</td>
                    <td className="p-2 border border-slate-300">Evaluación por competencias en escala 1 al 5 en los 4 Ejes MINED.</td>
                    <td className="p-2 border border-slate-300 text-center font-bold text-emerald-700">Certificada</td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Signature fields */}
            <div className="grid grid-cols-3 gap-8 pt-12 text-center text-xs">
              <div className="border-t border-slate-400 pt-2">
                <span className="font-bold block">Firma del Docente</span>
                <span className="text-slate-500">Lic. Alexander Gómez</span>
              </div>
              <div className="border-t border-slate-400 pt-2">
                <span className="font-bold block">Coordinación Pedagógica</span>
                <span className="text-slate-500">Colegio Salesiano San José</span>
              </div>
              <div className="border-t border-slate-400 pt-2">
                <span className="font-bold block">Sello Institucional</span>
                <span className="text-slate-500">Dirección General</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
