// GENERATED BY GEMINI — Campus LMS Module
// Panel Docente • Calificación por Competencias MINED • Rúbrica de 4 Ejes y Escala 1 al 5

import React, { useState, useEffect } from 'react';
import { Award, CheckCircle2, Search, ArrowRight, Sparkles, Send, ShieldCheck, HelpCircle, Layers } from 'lucide-react';
import { lmsService } from '../../services/lmsService';
import { LMSActivity, LMSCourse, MINED_LEVELS, MinedLevel } from '../../types';

interface DocenteLMSGradeProps {
  onOpenCurricularDocs?: () => void;
}

export const DocenteLMSGrade: React.FC<DocenteLMSGradeProps> = ({ onOpenCurricularDocs }) => {
  const [activities, setActivities] = useState<LMSActivity[]>([]);
  const [selectedActivity, setSelectedActivity] = useState<LMSActivity | null>(null);
  
  // 4 Axes state
  const [scoreTecnico, setScoreTecnico] = useState<number>(9);
  const [scoreEmprendedor, setScoreEmprendedor] = useState<number>(8.5);
  const [scoreHumano, setScoreHumano] = useState<number>(9.5);
  const [scoreAcademico, setScoreAcademico] = useState<number>(9);
  const [feedbackInput, setFeedbackInput] = useState<string>('Excelente aplicación de las leyes de composición y consistencia técnica en la entrega del proyecto.');
  const [savedSuccess, setSavedSuccess] = useState(false);

  useEffect(() => {
    const load = () => {
      const all = lmsService.getActivities();
      setActivities(all);
      if (all.length > 0 && !selectedActivity) {
        setSelectedActivity(all[0]);
      }
    };
    load();
    const unsub = lmsService.subscribe(load);
    return () => unsub();
  }, []);

  // Calculated weighted grade
  const calculatedGrade = +(
    scoreTecnico * 0.35 +
    scoreEmprendedor * 0.25 +
    scoreHumano * 0.20 +
    scoreAcademico * 0.20
  ).toFixed(1);

  const calculatedLevel: MinedLevel =
    calculatedGrade >= 9.6 ? 5 :
    calculatedGrade >= 8.5 ? 4 :
    calculatedGrade >= 7.0 ? 3 :
    calculatedGrade >= 5.0 ? 2 : 1;

  const handleGrade = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedActivity) return;

    lmsService.gradeWithMinedScale(
      selectedActivity.id,
      {
        scoreTecnico,
        scoreEmprendedor,
        scoreHumanoSocial: scoreHumano,
        scoreAcademicoAplicado: scoreAcademico,
      },
      feedbackInput
    );

    setSavedSuccess(true);
    setTimeout(() => setSavedSuccess(false), 3000);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <span className="text-xs font-bold text-[#0D71B9] uppercase tracking-wider block">
            Docencia y Evaluación BTV Diseño Gráfico
          </span>
          <h1 className="font-display font-extrabold text-2xl md:text-3xl text-slate-900">
            Calificación por Competencias y Ejes Vocacionales
          </h1>
          <p className="text-xs text-slate-500">
            Evalúa las etapas de la Acción Completa según los 4 ejes de desarrollo MINED (Técnico 35%, Emprendedor 25%, Humano 20%, Académico 20%).
          </p>
        </div>

        {onOpenCurricularDocs && (
          <button
            onClick={onOpenCurricularDocs}
            className="px-4 py-2 rounded-xl bg-[#124D37] text-white text-xs font-bold flex items-center gap-2 hover:bg-[#0E3D2B] transition-colors shadow-xs shrink-0 self-start md:self-auto"
          >
            <Award className="w-4 h-4" />
            <span>Documentación & Rúbrica 29 Ítems</span>
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Activities List */}
        <div className="lg:col-span-5 card-crema p-4.5 space-y-3 border border-slate-200">
          <h3 className="font-display font-bold text-slate-900 text-sm uppercase tracking-wider flex items-center justify-between">
            <span>Entregas de Estudiantes ({activities.length})</span>
            <span className="text-[11px] font-semibold text-slate-400">Cohorte 2026</span>
          </h3>
          <div className="space-y-2 max-h-[600px] overflow-y-auto pr-1">
            {activities.map((act) => {
              const isSelected = selectedActivity?.id === act.id;
              return (
                <div
                  key={act.id}
                  onClick={() => {
                    setSelectedActivity(act);
                    if (act.submission?.axesScores) {
                      setScoreTecnico(act.submission.axesScores.scoreTecnico);
                      setScoreEmprendedor(act.submission.axesScores.scoreEmprendedor);
                      setScoreHumano(act.submission.axesScores.scoreHumanoSocial);
                      setScoreAcademico(act.submission.axesScores.scoreAcademicoAplicado);
                    }
                    if (act.submission?.feedback) setFeedbackInput(act.submission.feedback);
                  }}
                  className={`p-3.5 rounded-2xl border transition-all cursor-pointer ${
                    isSelected
                      ? 'bg-blue-50/80 border-[#0D71B9] shadow-xs'
                      : 'bg-white border-slate-200/80 hover:bg-slate-50'
                  }`}
                >
                  <div className="flex items-center justify-between text-[11px] mb-1">
                    <span className="font-mono font-bold text-slate-900 bg-slate-100 px-1.5 py-0.5 rounded">
                      {act.courseName?.split('—')[0]?.trim() || 'BTVDG'}
                    </span>
                    <span
                      className={`font-semibold px-2 py-0.5 rounded-full text-[10px] ${
                        act.status === 'calificada'
                          ? 'bg-emerald-100 text-emerald-800'
                          : 'bg-amber-100 text-amber-800'
                      }`}
                    >
                      {act.status === 'calificada' ? 'Calificada' : 'Pendiente de Revisión'}
                    </span>
                  </div>
                  <h4 className="font-bold text-slate-800 text-xs line-clamp-1">{act.title}</h4>
                  <p className="text-[10px] text-slate-500 mt-0.5 capitalize">
                    Etapa: {act.stageKey || 'Ejecución'}
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right: Grade & Feedback Form */}
        <div className="lg:col-span-7 space-y-5">
          {selectedActivity ? (
            <div className="card-crema p-6 space-y-5 border border-slate-200">
              <div className="flex items-start justify-between border-b border-slate-100 pb-3">
                <div>
                  <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                    {selectedActivity.courseName}
                  </span>
                  <h2 className="font-display font-bold text-xl text-slate-900 mt-0.5">
                    {selectedActivity.title}
                  </h2>
                </div>
                <div className="text-right">
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-slate-100 text-slate-700">
                    Etapa {selectedActivity.stageKey?.toUpperCase() || 'PROYECTO'}
                  </span>
                </div>
              </div>

              {/* Student Submission preview */}
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs space-y-2">
                <span className="font-bold text-slate-700 block">Detalles de Entrega del Estudiante:</span>
                <p className="text-slate-600">
                  {selectedActivity.submission?.content ||
                    'Entrega digital: Proyecto de identidad visual con mapa conceptual, paleta cromática CMYK y manual de normas técnicas en PDF.'}
                </p>
                <div className="flex items-center gap-2 pt-1">
                  <span className="text-[10px] font-semibold text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded">
                    Archivo: Entrega_Fase_BTVDG.pdf (14.2 MB)
                  </span>
                </div>
              </div>

              {/* Evaluation by 4 Axes */}
              <form onSubmit={handleGrade} className="space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="font-display font-bold text-slate-900 text-sm flex items-center gap-1.5">
                    <Award className="w-4 h-4 text-[#0D71B9]" />
                    Evaluación por los 4 Ejes de Desarrollo Vocacional
                  </h3>
                  <span className="text-xs font-bold text-emerald-700">
                    Nota Ponderada: {calculatedGrade} / 10 (Nivel {calculatedLevel})
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
                  {/* Axis 1 */}
                  <div className="p-3.5 rounded-xl bg-blue-50/60 border border-blue-200 space-y-1.5">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-bold text-blue-900">Eje Técnico (35%)</label>
                      <span className="text-xs font-bold text-blue-700">{scoreTecnico} pts</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="10"
                      step="0.5"
                      value={scoreTecnico}
                      onChange={(e) => setScoreTecnico(Number(e.target.value))}
                      className="w-full accent-blue-600"
                    />
                    <span className="text-[10px] text-slate-500 block">Software, diagramación y normas técnicas</span>
                  </div>

                  {/* Axis 2 */}
                  <div className="p-3.5 rounded-xl bg-amber-50/60 border border-amber-200 space-y-1.5">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-bold text-amber-900">Eje Emprendedor (25%)</label>
                      <span className="text-xs font-bold text-amber-700">{scoreEmprendedor} pts</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="10"
                      step="0.5"
                      value={scoreEmprendedor}
                      onChange={(e) => setScoreEmprendedor(Number(e.target.value))}
                      className="w-full accent-amber-600"
                    />
                    <span className="text-[10px] text-slate-500 block">Propuesta de valor, viabilidad y presupuesto</span>
                  </div>

                  {/* Axis 3 */}
                  <div className="p-3.5 rounded-xl bg-purple-50/60 border border-purple-200 space-y-1.5">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-bold text-purple-900">Eje Humano-Social (20%)</label>
                      <span className="text-xs font-bold text-purple-700">{scoreHumano} pts</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="10"
                      step="0.5"
                      value={scoreHumano}
                      onChange={(e) => setScoreHumano(Number(e.target.value))}
                      className="w-full accent-purple-600"
                    />
                    <span className="text-[10px] text-slate-500 block">Ética, trabajo en equipo y empatía con usuario</span>
                  </div>

                  {/* Axis 4 */}
                  <div className="p-3.5 rounded-xl bg-emerald-50/60 border border-emerald-200 space-y-1.5">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-bold text-emerald-900">Académico Aplicado (20%)</label>
                      <span className="text-xs font-bold text-emerald-700">{scoreAcademico} pts</span>
                    </div>
                    <input
                      type="range"
                      min="1"
                      max="10"
                      step="0.5"
                      value={scoreAcademico}
                      onChange={(e) => setScoreAcademico(Number(e.target.value))}
                      className="w-full accent-emerald-600"
                    />
                    <span className="text-[10px] text-slate-500 block">Ortografía, semiótica, teoría del color</span>
                  </div>
                </div>

                {/* Feedback Box */}
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-700">Retroalimentación Formativa y Cualitativa:</label>
                  <textarea
                    rows={3}
                    value={feedbackInput}
                    onChange={(e) => setFeedbackInput(e.target.value)}
                    className="w-full p-3 rounded-xl bg-white border border-slate-200 text-xs focus:outline-none focus:border-[#0D71B9]"
                    placeholder="Escriba aquí los comentarios formativos para el estudiante..."
                  />
                </div>

                {/* Submit button */}
                <div className="flex items-center justify-between pt-2">
                  {savedSuccess ? (
                    <span className="text-xs font-bold text-emerald-600 flex items-center gap-1">
                      <CheckCircle2 className="w-4 h-4" /> Calificación guardada y sincronizada en MINED.
                    </span>
                  ) : <span />}

                  <button
                    type="submit"
                    className="btn-primary !py-2 !px-5 text-xs flex items-center gap-2"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>Guardar Calificación MINED</span>
                  </button>
                </div>
              </form>
            </div>
          ) : (
            <div className="card-crema p-10 text-center border border-slate-200">
              <p className="text-xs text-slate-500">Selecciona una actividad de la lista para evaluarla.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DocenteLMSGrade;
