// DATOS OFICIALES DEL PLAN DE ESTUDIOS — BACHILLERATO TÉCNICO VOCACIONAL EN DISEÑO GRÁFICO
// Ministerio de Educación de El Salvador / Instituto Técnico Ricaldone / Institución Salesiana
// 3 Años Lectivos • 26 Módulos Técnicos • Enfoque de Competencias Orientadas a la Acción • Escala MINED 1-5

import { LMSCourse, TechnicalModuleDescriptor, Rubric, ProjectBrief, TechnicalYear } from '../types';

// Rúbricas Oficiales con Escala 1 a 5 y los 4 Ejes
export const DEFAULT_BTV_RUBRICS: Record<string, Rubric> = {
  'rubric-btv-standard': {
    id: 'rubric-btv-standard',
    title: 'Rúbrica Oficial de Evaluación por Competencias MINED (Escala 1 a 5)',
    description: 'Evaluación criterial y holística en los 4 ejes de desarrollo de la competencia.',
    criteria: [
      {
        id: 'crit-tecnico',
        title: 'Eje 1: Desarrollo Técnico y Tecnológico',
        axis: 'tecnico',
        weight: 35,
        levels: [
          { score: 1, label: 'Nivel 1 (1.0-4.9)', description: 'Aplica herramientas y procesos de diseño con mucha ayuda constante y dificultades técnicas.' },
          { score: 2, label: 'Nivel 2 (5.0-5.9)', description: 'Aplica herramientas básicas con poca ayuda pero requiere corrección en artes finales.' },
          { score: 3, label: 'Nivel 3 (6.0-6.9)', description: 'Aplica herramientas y técnicas con eventual ayuda; resolución aceptable.' },
          { score: 4, label: 'Nivel 4 (7.0-8.9) [Aprobado]', description: 'Domina las herramientas manuales/digitales y técnicas de arte final por sí mismo(a).' },
          { score: 5, label: 'Nivel 5 (9.0-10.0)', description: 'Manejo experto y autónomo; asesora técnicamente a sus compañeros de equipo.' },
        ],
      },
      {
        id: 'crit-emprendedor',
        title: 'Eje 2: Desarrollo Emprendedor y Productivo',
        axis: 'emprendedor',
        weight: 25,
        levels: [
          { score: 1, label: 'Nivel 1 (1.0-4.9)', description: 'No vincula el proyecto con necesidades del cliente o mercado; no administra costos.' },
          { score: 2, label: 'Nivel 2 (5.0-5.9)', description: 'Identifica oportunidades con poca ayuda pero el enfoque comercial es débil.' },
          { score: 3, label: 'Nivel 3 (6.0-6.9)', description: 'Plantea soluciones funcionales con eventual asesoría en costos y factibilidad.' },
          { score: 4, label: 'Nivel 4 (7.0-8.9) [Aprobado]', description: 'Propone soluciones viables, optimiza insumos y responde al mercado por sí mismo(a).' },
          { score: 5, label: 'Nivel 5 (9.0-10.0)', description: 'Modelo de negocio sobresaliente con visión cooperativa e impacto comunitario.' },
        ],
      },
      {
        id: 'crit-humano-social',
        title: 'Eje 3: Desarrollo Humano y Social (Valores y Liderazgo)',
        axis: 'humanoSocial',
        weight: 20,
        levels: [
          { score: 1, label: 'Nivel 1 (1.0-4.9)', description: 'Dificultad para integrarse al equipo, no cumple roles asignados ni tiempos.' },
          { score: 2, label: 'Nivel 2 (5.0-5.9)', description: 'Participa pasivamente requiriendo recordatorios de puntualidad y convivencia.' },
          { score: 3, label: 'Nivel 3 (6.0-6.9)', description: 'Cumple tareas con eventual apoyo, mantiene trato cordial en el grupo.' },
          { score: 4, label: 'Nivel 4 (7.0-8.9) [Aprobado]', description: 'Demuestra liderazgo participativo, puntualidad, ética y cooperación activa.' },
          { score: 5, label: 'Nivel 5 (9.0-10.0)', description: 'Modela valores de solidaridad, resuelve conflictos y motiva al equipo.' },
        ],
      },
      {
        id: 'crit-academico',
        title: 'Eje 4: Desarrollo Académico Aplicado (Racional y Ciencias)',
        axis: 'academico',
        weight: 20,
        levels: [
          { score: 1, label: 'Nivel 1 (1.0-4.9)', description: 'Racional creativo inconsistente, errores de ortografía, no fundamenta decisiones.' },
          { score: 2, label: 'Nivel 2 (5.0-5.9)', description: 'Aplica conceptos teóricos básicos con poca ayuda; redacción requiere mejoras.' },
          { score: 3, label: 'Nivel 3 (6.0-6.9)', description: 'Fundamenta adecuadamente la propuesta con eventual asistencia conceptual.' },
          { score: 4, label: 'Nivel 4 (7.0-8.9) [Aprobado]', description: 'Redacta racionales técnicos impecables con ortografía, semiótica y cálculo preciso.' },
          { score: 5, label: 'Nivel 5 (9.0-10.0)', description: 'Sustentación académica sobresaliente, discursos elocuentes y dominio conceptual pleno.' },
        ],
      },
    ],
  },
};

// Generador de Etapas de la Acción Completa Estándar
const createActionStages = (moduleName: string, specificExecTask: string, tools: string[]): TechnicalModuleDescriptor['actionStages'] => ({
  informar: {
    key: 'informar',
    title: '1. Etapa de Informarse (10% de horas)',
    hoursPercentage: 10,
    guidingQuestions: [
      `¿Qué debemos saber sobre ${moduleName}?`,
      '¿Cuáles son las fuentes bibliográficas, técnicas y digitales confiables?',
      '¿Qué saberes previos dominamos y cuáles necesitamos adquirir?',
    ],
    studentTasks: [
      'Investigación documental y bibliográfica en web y libros especializados.',
      'Aplicación del cuestionario diagnóstico de saberes previos (Mucho, Poco, Nada).',
      'Elaboración de mapas mentales, fichas técnicas y glosario de términos.',
      'Entrevistas a especialistas y visitas de campo a empresas del sector.',
    ],
    teacherTasks: [
      'Presentación de la situación problemática y objetivos de competencia.',
      'Suministro de fuentes de información y guía metodológica.',
      'Facilitación de dinámicas de lluvia de ideas y clarificación del rol constructivista.',
    ],
    suggestedTools: ['METAPLAN', 'Cuestionario de Saberes Previos', 'Glosario Técnico', 'Buscadores y bases de datos'],
  },
  planificar: {
    key: 'planificar',
    title: '2. Etapa de Planificar (10% de horas)',
    hoursPercentage: 10,
    guidingQuestions: [
      '¿Qué actividades debemos realizar para resolver el problema?',
      '¿Cómo organizamos los tiempos en el cronograma?',
      '¿Cuáles son los recursos, herramientas y roles de cada miembro?',
    ],
    studentTasks: [
      'Formación de equipos de trabajo y asignación consensuada de roles.',
      'Construcción de la matriz del proyecto y cronograma de ruta crítica.',
      'Listado de materiales, herramientas, software y presupuesto estimado.',
      'Definición de etapas de bocetería, validación y entrega.',
    ],
    teacherTasks: [
      'Orientación en la elaboración del plan de trabajo y marco lógico.',
      'Revisión de factibilidad de tiempos y recursos de los equipos.',
      'Adecuación de espacios de taller y laboratorios de computación.',
    ],
    suggestedTools: ['Ruta Crítica', 'Diagrama de Gantt', 'Matriz de Marco Lógico', 'METAPLAN'],
  },
  decidir: {
    key: 'decidir',
    title: '3. Etapa de Decidir (10% de horas)',
    hoursPercentage: 10,
    guidingQuestions: [
      '¿Cuál alternativa de diseño o proyecto es la más viable y factible?',
      '¿El proyecto responde fielmente al público objetivo y necesidad real?',
      '¿Qué decisiones técnicas consensuamos antes de producir?',
    ],
    studentTasks: [
      'Llenado del formulario de decisiones (¿Quiénes? ¿Con qué? ¿Dónde? Tiempo).',
      'Evaluación de alternativas mediante método Delphi o matriz de pros/contras.',
      'Selección del concepto creativo, paleta cromática, estilo y técnica definitiva.',
      'Consenso democrático de responsabilidades individuales en el equipo.',
    ],
    teacherTasks: [
      'Asesoría en la toma de decisiones asistida y mediación pedagógica.',
      'Validación técnica de pertinencia del proyecto antes de la fase de taller.',
    ],
    suggestedTools: ['Formulario de Decisiones', 'Método Delphi', 'Matriz de Pros y Contras', 'Diagrama de Espina (Ishikawa)'],
  },
  ejecutar: {
    key: 'ejecutar',
    title: '4. Etapa de Ejecutar (25% de horas)',
    hoursPercentage: 25,
    guidingQuestions: [
      '¿Estamos siguiendo las normas de calidad, medidas y especificaciones técnicas?',
      '¿Cómo transformamos los bocetos en artes finales impresos o digitales?',
      `¿Cómo aplicamos ${specificExecTask}?`,
    ],
    studentTasks: [
      'Desarrollo exhaustivo de bocetos, pruebas de color y composiciones.',
      specificExecTask,
      'Producción de dummies, prototipos a escala real y artes finales.',
      'Registro continuo de procedimientos en la bitácora o diario de trabajo.',
    ],
    teacherTasks: [
      'Acompañamiento técnico en talleres y laboratorios de diseño.',
      'Verificación de estándares de calidad, seguridad y uso adecuado de software.',
      'Intervención oportuna ante desviaciones de proceso.',
    ],
    suggestedTools: tools,
  },
  controlar: {
    key: 'controlar',
    title: '5. Etapa de Controlar (25% de horas)',
    hoursPercentage: 25,
    guidingQuestions: [
      '¿Se están cumpliendo los indicadores de logro y fechas del cronograma?',
      '¿Qué fallas técnicas o desajustes hemos detectado y cómo los corregimos?',
      '¿Cómo evoluciona la convivencia y participación en el equipo?',
    ],
    studentTasks: [
      'Monitoreo semanal del cronograma de actividades (realizado vs. planificado).',
      'Aplicación de listas de cotejo, análisis FODA y listado de atributos.',
      'Sesiones de crítica guiada y revisión de pruebas de impresión o render.',
      'Corrección oportuna de trazados, color, tipografía y encuadre.',
    ],
    teacherTasks: [
      'Revisión periódica de bitácoras y reportes semanales de avance.',
      'Retroalimentación formativa inmediata en el aula/taller.',
      'Detección de necesidades de refuerzo educativo técnico o procedimental.',
    ],
    suggestedTools: ['Listas de Cotejo', 'Matriz FODA', 'Círculo PHVA (Deming)', 'Listado de Atributos'],
  },
  valorar: {
    key: 'valorar',
    title: '6. Etapa de Valorar y Reflexionar (20% de horas)',
    hoursPercentage: 20,
    guidingQuestions: [
      '¿En qué nivel de logro (1 a 5) alcanzamos cada competencia?',
      '¿Qué impacto generó el proyecto en la comunidad o público objetivo?',
      '¿Qué lecciones aprendidas y valores éticos fortalecimos?',
    ],
    studentTasks: [
      'Autoevaluación individual y coevaluación entre pares del equipo.',
      'Defensa oral del proyecto con racional creativo y presentación de artes finales.',
      'Montaje de exposiciones o ferias institucionales (Semana de la Juventud/Muestra Gráfica).',
      'Formulación de conclusiones, lecciones aprendidas y técnica ETPO.',
    ],
    teacherTasks: [
      'Aplicación de la rúbrica oficial MINED en los 4 ejes de desarrollo.',
      'Asignación de calificación en escala de nivel 1 a 5 y conversión a nota 1-10.',
      'Planificación de actividades de recuperación para estudiantes con nivel < 4.',
    ],
    suggestedTools: ['Rúbrica Oficial MINED', 'Técnica ETPO', 'SCAMPER', 'Portafolio de Evidencias'],
  },
});

// DESCRIPTORES COMPLETOS DE LOS MÓDULOS DE DISEÑO GRÁFICO (26 MÓDULOS TÉCNICOS)
export const BTV_GRAPHIC_DESIGN_COURSES: LMSCourse[] = [
  // ==========================================
  // PRIMER AÑO (720 HORAS TOTALES)
  // ==========================================
  {
    id: 'btvdg-1-0',
    name: 'Orientación al Proceso Educativo del 1° Año',
    code: 'BTVDG1.0',
    technicalYear: '1',
    hours: 18,
    weeks: 1,
    affineArea: 'Orientación',
    description: 'Inducción al enfoque de competencias orientadas a la acción, roles constructivistas y método de proyectos de la especialidad.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'orientacion-1',
    icon: 'Compass',
    color: '#0D71B9',
    status: 'active',
    schedule: 'Semana 1 • 18 Horas',
    classroom: 'Aula Magna / Taller 1',
    unitsCount: 6,
    activitiesCount: 3,
    progress: 100,
    averageGrade: 9.5,
    minedLevel: 5,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'btvdg-1-1',
    name: 'Lectura de Documentos Técnicos en Inglés',
    code: 'BTVDG1.1',
    technicalYear: '1',
    hours: 18,
    weeks: 1,
    affineArea: 'Publicidad y comunicación',
    description: 'Comprensión de vocabulario técnico básico en manuales de marca, software de diseño e investigación en idioma inglés.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'ingles-tecnico-1',
    icon: 'Languages',
    color: '#2563EB',
    status: 'active',
    schedule: 'Semana 2 • 18 Horas',
    classroom: 'Laboratorio de Idiomas',
    unitsCount: 6,
    activitiesCount: 2,
    progress: 100,
    averageGrade: 9.0,
    minedLevel: 4,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'btvdg-1-2',
    name: 'Aplicación de Procesos de Investigación Gráfica',
    code: 'BTVDG1.2',
    technicalYear: '1',
    hours: 72,
    weeks: 4,
    affineArea: 'Estrategias conceptuales y artísticas',
    description: 'Metodologías de recolección sistemática de datos, análisis de audiencias y síntesis en organizadores gráficos para fundamentar proyectos visuales.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'investigacion-grafica',
    icon: 'Search',
    color: '#059669',
    status: 'active',
    schedule: 'Semanas 3 a 6 • 18 H/Semana',
    classroom: 'Taller de Creatividad',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 85,
    averageGrade: 8.8,
    minedLevel: 4,
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'btvdg-1-3',
    name: 'Desarrollo de Estrategias y Pensamiento Creativo',
    code: 'BTVDG1.3',
    technicalYear: '1',
    hours: 126,
    weeks: 7,
    affineArea: 'Estrategias conceptuales y artísticas',
    description: 'Métodos creativos (Brainstorming, Design Thinking, Caja Negra y Caja Transparente), desarrollo de racionales y bocetería funcional.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'pensamiento-creativo',
    icon: 'Sparkles',
    color: '#D97706',
    status: 'active',
    schedule: 'Semanas 7 a 13 • 18 H/Semana',
    classroom: 'Taller de Diseño 1',
    unitsCount: 6,
    activitiesCount: 5,
    progress: 60,
    averageGrade: 8.5,
    minedLevel: 4,
    createdAt: '2026-02-15T08:00:00Z',
  },
  {
    id: 'btvdg-1-4',
    name: 'Aplicación de Influencias Artísticas en el Diseño',
    code: 'BTVDG1.4',
    technicalYear: '1',
    hours: 54,
    weeks: 3,
    affineArea: 'Estrategias conceptuales y artísticas',
    description: 'Interpretación de movimientos de la historia del arte (Art Nouveau, Surrealismo, Expresionismo, Bauhaus) aplicados a piezas gráficas contemporáneas.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'historia-arte-dg',
    icon: 'Palette',
    color: '#7C3AED',
    status: 'active',
    schedule: 'Semanas 14 a 16 • 18 H/Semana',
    classroom: 'Salón de Historia del Arte',
    unitsCount: 6,
    activitiesCount: 3,
    progress: 40,
    averageGrade: 8.0,
    minedLevel: 4,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'btvdg-1-5',
    name: 'Representación de Dibujo al Natural',
    code: 'BTVDG1.5',
    technicalYear: '1',
    hours: 108,
    weeks: 6,
    affineArea: 'Estrategias conceptuales y artísticas',
    description: 'Observación y proporción, cánones anatómicos, valoración tonal de luz y sombras, perspectiva y desarrollo de estilo ilustrativo propio.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'dibujo-natural',
    icon: 'PenTool',
    color: '#DB2777',
    status: 'active',
    schedule: 'Semanas 17 a 22 • 18 H/Semana',
    classroom: 'Taller de Dibujo y Caballetes',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 25,
    averageGrade: 8.5,
    minedLevel: 4,
    createdAt: '2026-03-15T08:00:00Z',
  },
  {
    id: 'btvdg-1-6',
    name: 'Aplicación de Técnicas de Expresión Manual',
    code: 'BTVDG1.6',
    technicalYear: '1',
    hours: 126,
    weeks: 7,
    affineArea: 'Estrategias conceptuales y artísticas',
    description: 'Técnicas secas, húmedas y experimentales (grafito, acuarela, témpera, acrílico, pasteles y texturas) aplicadas a piezas publicitarias.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'expresion-manual',
    icon: 'Brush',
    color: '#0891B2',
    status: 'upcoming',
    schedule: 'Semanas 23 a 29 • 18 H/Semana',
    classroom: 'Taller de Técnicas Húmedas',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 0,
    createdAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'btvdg-1-7',
    name: 'Diseño de Objetos Vectoriales',
    code: 'BTVDG1.7',
    technicalYear: '1',
    hours: 126,
    weeks: 7,
    affineArea: 'Diseño y diagramación',
    description: 'Creación de recursos vectoriales con Adobe Illustrator: herramienta pluma, puntos de ancla, isotipos, iconografía y preparación técnica de arte final.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'diseno-vectorial',
    icon: 'Feather',
    color: '#EA580C',
    status: 'upcoming',
    schedule: 'Semanas 30 a 36 • 18 H/Semana',
    classroom: 'Laboratorio Mac 1',
    unitsCount: 6,
    activitiesCount: 5,
    progress: 0,
    createdAt: '2026-05-01T08:00:00Z',
  },
  {
    id: 'btvdg-1-8',
    name: 'Emprendedurismo Colaborativo',
    code: 'BTVDG1.8',
    technicalYear: '1',
    hours: 72,
    weeks: 4,
    affineArea: 'Emprendedurismo',
    description: 'Desarrollo de características personales emprendedoras, trabajo en equipo asociativo, liderazgo y perfil inicial de idea de negocio cooperativo.',
    teacherId: 'doc-marvin',
    teacherName: 'Ing. Marvin Torres',
    gradeId: '10',
    gradeName: '1° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'emprendimiento-1',
    icon: 'Briefcase',
    color: '#4F46E5',
    status: 'upcoming',
    schedule: 'Semanas 37 a 40 • 18 H/Semana',
    classroom: 'Aula de Negocios y Emprendimiento',
    unitsCount: 6,
    activitiesCount: 3,
    progress: 0,
    createdAt: '2026-06-01T08:00:00Z',
  },

  // ==========================================
  // SEGUNDO AÑO (720 HORAS TOTALES)
  // ==========================================
  {
    id: 'btvdg-2-0',
    name: 'Orientación al Proceso Educativo del 2° Año',
    code: 'BTVDG2.0',
    technicalYear: '2',
    hours: 18,
    weeks: 1,
    affineArea: 'Orientación',
    description: 'Consolidación de competencias de segundo año, reestructuración del plan de vida profesional e inserción laboral en el sector gráfico.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'orientacion-2',
    icon: 'Compass',
    color: '#0D71B9',
    status: 'active',
    schedule: 'Semana 1 • 18 Horas',
    classroom: 'Auditorio Salesiano',
    unitsCount: 6,
    activitiesCount: 2,
    progress: 90,
    averageGrade: 9.0,
    minedLevel: 4,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'btvdg-2-1',
    name: 'Elaboración de Piezas Gráficas con Principios de Diseño',
    code: 'BTVDG2.1',
    technicalYear: '2',
    hours: 108,
    weeks: 6,
    affineArea: 'Diseño y diagramación',
    description: 'Aplicación rigurosa de pesos visuales, jerarquías, cuadrantes, escalas cromáticas, tipografía y semiótica en piezas funcionales.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'principios-diseno',
    icon: 'Layout',
    color: '#84CC16',
    status: 'active',
    schedule: 'Semanas 2 a 7 • 18 H/Semana',
    classroom: 'Taller de Diseño 2',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 75,
    averageGrade: 8.8,
    minedLevel: 4,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'btvdg-2-2',
    name: 'Desarrollo de Estrategias de Comunicación Aplicadas',
    code: 'BTVDG2.2',
    technicalYear: '2',
    hours: 90,
    weeks: 5,
    affineArea: 'Publicidad y comunicación',
    description: 'Planes de medios, tonos de comunicación y campañas de concientización social para erradicar antivalores con alto impacto visual.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'estrategias-comunicacion',
    icon: 'Radio',
    color: '#EAB308',
    status: 'active',
    schedule: 'Semanas 8 a 12 • 18 H/Semana',
    classroom: 'Taller de Medios',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 50,
    averageGrade: 8.6,
    minedLevel: 4,
    createdAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'btvdg-2-3',
    name: 'Edición Digital de Imágenes (Photoshop)',
    code: 'BTVDG2.3',
    technicalYear: '2',
    hours: 126,
    weeks: 7,
    affineArea: 'Producción',
    description: 'Tratamiento digital avanzado de mapa de bits: fotomontaje, retoque profesional, máscaras, canales, corrección de color y arte final.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'edicion-imagenes',
    icon: 'Image',
    color: '#3B82F6',
    status: 'active',
    schedule: 'Semanas 13 a 19 • 18 H/Semana',
    classroom: 'Laboratorio Mac 2',
    unitsCount: 6,
    activitiesCount: 5,
    progress: 40,
    averageGrade: 9.2,
    minedLevel: 5,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'btvdg-2-4',
    name: 'Desarrollo de Estrategias de Medios en Idioma Inglés',
    code: 'BTVDG2.4',
    technicalYear: '2',
    hours: 18,
    weeks: 1,
    affineArea: 'Publicidad y comunicación',
    description: 'Formulación y exposición de planes de medios en inglés técnico, análisis del comportamiento del consumidor global y tarifarios.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'medios-ingles',
    icon: 'Globe',
    color: '#06B6D4',
    status: 'upcoming',
    schedule: 'Semana 20 • 18 Horas',
    classroom: 'Laboratorio de Idiomas',
    unitsCount: 6,
    activitiesCount: 2,
    progress: 0,
    createdAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'btvdg-2-5',
    name: 'Diseño de Piezas Publicitarias',
    code: 'BTVDG2.5',
    technicalYear: '2',
    hours: 108,
    weeks: 6,
    affineArea: 'Publicidad y comunicación',
    description: 'Producción de campañas publicitarias masivas: vallas, mupies, banners, afiches comerciales y material POP para marcas y productos.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'piezas-publicitarias',
    icon: 'Megaphone',
    color: '#F43F5E',
    status: 'upcoming',
    schedule: 'Semanas 21 a 26 • 18 H/Semana',
    classroom: 'Taller Creativo Publicitario',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 0,
    createdAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'btvdg-2-6',
    name: 'Maquetación y Diseño Editorial (InDesign)',
    code: 'BTVDG2.6',
    technicalYear: '2',
    hours: 108,
    weeks: 6,
    affineArea: 'Diseño y diagramación',
    description: 'Diseño y diagramación de revistas, libros, catálogos y fascículos con Adobe InDesign, retículas, tipometría y compaginación para imprenta.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'diseno-editorial',
    icon: 'BookOpen',
    color: '#A855F7',
    status: 'upcoming',
    schedule: 'Semanas 27 a 32 • 18 H/Semana',
    classroom: 'Laboratorio Editorial Mac',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 0,
    createdAt: '2026-05-01T08:00:00Z',
  },
  {
    id: 'btvdg-2-7',
    name: 'Diseño y Construcción de Empaques y Viñetas',
    code: 'BTVDG2.7',
    technicalYear: '2',
    hours: 72,
    weeks: 4,
    affineArea: 'Diseño y diagramación',
    description: 'Diseño estructural de troqueles (sisas, cortes, dobleces), normativa de etiquetado comercial, prototipado 3D y packaging para productos.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'empaques-vinetas',
    icon: 'Box',
    color: '#10B981',
    status: 'upcoming',
    schedule: 'Semanas 33 a 36 • 18 H/Semana',
    classroom: 'Taller de Prototipado y Empaque',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 0,
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'btvdg-2-8',
    name: 'Diseño de Planes de Negocio en Asociatividad Cooperativa',
    code: 'BTVDG2.8',
    technicalYear: '2',
    hours: 72,
    weeks: 4,
    affineArea: 'Emprendedurismo',
    description: 'Estructuración legal y financiera de la microempresa pre-cooperativa bajo lineamientos de INSAFOCOOP, estudio de mercado y plan estratégico.',
    teacherId: 'doc-marvin',
    teacherName: 'Ing. Marvin Torres',
    gradeId: '11',
    gradeName: '2° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'planes-negocio-coop',
    icon: 'TrendingUp',
    color: '#6366F1',
    status: 'upcoming',
    schedule: 'Semanas 37 a 40 • 18 H/Semana',
    classroom: 'Aula de Negocios y Emprendimiento',
    unitsCount: 6,
    activitiesCount: 3,
    progress: 0,
    createdAt: '2026-07-01T08:00:00Z',
  },

  // ==========================================
  // TERCER AÑO (1,200 HORAS TOTALES)
  // ==========================================
  {
    id: 'btvdg-3-0',
    name: 'Orientación al Proceso Educativo del 3° Año',
    code: 'BTVDG3.0',
    technicalYear: '3',
    hours: 30,
    weeks: 1,
    affineArea: 'Orientación',
    description: 'Orientación al año de especialización técnica integral (1,200h 100% técnicas), fuentes de empleo, portafolios y pasantías.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'orientacion-3',
    icon: 'Compass',
    color: '#0D71B9',
    status: 'active',
    schedule: 'Semana 1 • 30 Horas',
    classroom: 'Auditorio Ricaldone',
    unitsCount: 6,
    activitiesCount: 2,
    progress: 100,
    averageGrade: 9.8,
    minedLevel: 5,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'btvdg-3-1',
    name: 'Aplicación de Sistemas de Impresión y Artes Finales',
    code: 'BTVDG3.1',
    technicalYear: '3',
    hours: 120,
    weeks: 4,
    affineArea: 'Producción',
    description: 'Sistemas Offset, Serigrafía, Flexografía e Impresión Digital. Separación de color CMYK, tramados, papeles y presupuestación industrial.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'sistemas-impresion',
    icon: 'Printer',
    color: '#0284C7',
    status: 'active',
    schedule: 'Semanas 2 a 5 • 30 H/Semana',
    classroom: 'Taller de Artes Gráficas e Imprenta',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 80,
    averageGrade: 9.1,
    minedLevel: 5,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'btvdg-3-2',
    name: 'Aplicación de Técnicas Fotográficas para Publicidad',
    code: 'BTVDG3.2',
    technicalYear: '3',
    hours: 150,
    weeks: 5,
    affineArea: 'Producción',
    description: 'Manejo manual de cámara réflex, iluminación de estudio, fotografía de producto, encuadres, ángulos y revelado digital en Lightroom.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'fotografia-publicitaria',
    icon: 'Camera',
    color: '#0D9488',
    status: 'active',
    schedule: 'Semanas 6 a 10 • 30 H/Semana',
    classroom: 'Estudio Fotográfico Salesiano',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 60,
    averageGrade: 8.9,
    minedLevel: 4,
    createdAt: '2026-02-15T08:00:00Z',
  },
  {
    id: 'btvdg-3-3',
    name: 'Creación de Identidad Corporativa y Branding',
    code: 'BTVDG3.3',
    technicalYear: '3',
    hours: 180,
    weeks: 6,
    affineArea: 'Estrategias conceptuales y artísticas',
    description: 'Diseño integral de marca: logotipo, isotipo, imagotipo, manual de normas de identidad visual, papelería comercial y estrategia de lanzamiento.',
    teacherId: 'doc-karla',
    teacherName: 'Licda. Karla Hernández',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'identidad-corporativa',
    icon: 'Award',
    color: '#D97706',
    status: 'active',
    schedule: 'Semanas 11 a 16 • 30 H/Semana',
    classroom: 'Taller de Branding',
    unitsCount: 6,
    activitiesCount: 5,
    progress: 45,
    averageGrade: 9.3,
    minedLevel: 5,
    createdAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'btvdg-3-4',
    name: 'Creación de Recursos Publicitarios Ilustrados',
    code: 'BTVDG3.4',
    technicalYear: '3',
    hours: 150,
    weeks: 5,
    affineArea: 'Estrategias conceptuales y artísticas',
    description: 'Ilustración conceptual publicitaria, metáforas visuales, diseño y desarrollo de personajes de marca (mascotas corporativas) para productos.',
    teacherId: 'doc-nelson',
    teacherName: 'Lic. Nelson Miranda',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'ilustracion-publicitaria',
    icon: 'Sparkles',
    color: '#EC4899',
    status: 'upcoming',
    schedule: 'Semanas 17 a 21 • 30 H/Semana',
    classroom: 'Taller de Ilustración Digital',
    unitsCount: 6,
    activitiesCount: 4,
    progress: 0,
    createdAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'btvdg-3-5',
    name: 'Desarrollo y Aplicación de Publicidad Estratégica',
    code: 'BTVDG3.5',
    technicalYear: '3',
    hours: 210,
    weeks: 7,
    affineArea: 'Publicidad y comunicación',
    description: 'Investigación de mercados, psicología del consumidor salvadoreño, formulación y ejecución de campañas 360° para empresas y ONGs.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'publicidad-estrategica',
    icon: 'Target',
    color: '#EF4444',
    status: 'upcoming',
    schedule: 'Semanas 22 a 28 • 30 H/Semana',
    classroom: 'Agencia de Publicidad Simulada',
    unitsCount: 6,
    activitiesCount: 5,
    progress: 0,
    createdAt: '2026-05-01T08:00:00Z',
  },
  {
    id: 'btvdg-3-6',
    name: 'Producción de Video y Animación Publicitaria',
    code: 'BTVDG3.6',
    technicalYear: '3',
    hours: 210,
    weeks: 7,
    affineArea: 'Producción',
    description: 'Storyboarding, stop motion, motion graphics con Adobe After Effects/Premiere, edición de audio y spots publicitarios para redes sociales.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'video-animacion',
    icon: 'Video',
    color: '#8B5CF6',
    status: 'upcoming',
    schedule: 'Semanas 29 a 35 • 30 H/Semana',
    classroom: 'Laboratorio Multimedia y Render',
    unitsCount: 6,
    activitiesCount: 5,
    progress: 0,
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'btvdg-3-7',
    name: 'Puesta en Marcha de la Microempresa Asociativa',
    code: 'BTVDG3.7',
    technicalYear: '3',
    hours: 90,
    weeks: 3,
    affineArea: 'Emprendedurismo',
    description: 'Operación comercial real o simulada de un estudio de diseño cooperativo, gestión de clientes, facturación, tributos y control contable.',
    teacherId: 'doc-marvin',
    teacherName: 'Ing. Marvin Torres',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'operacion-microempresa',
    icon: 'Coins',
    color: '#14B8A6',
    status: 'upcoming',
    schedule: 'Semanas 36 a 38 • 30 H/Semana',
    classroom: 'Espacio Co-Working Salesiano',
    unitsCount: 6,
    activitiesCount: 3,
    progress: 0,
    createdAt: '2026-07-01T08:00:00Z',
  },
  {
    id: 'btvdg-3-8',
    name: 'Presentación de Proyectos en Idioma Inglés (Pitch & Portfolio)',
    code: 'BTVDG3.8',
    technicalYear: '3',
    hours: 60,
    weeks: 2,
    affineArea: 'Publicidad y comunicación',
    description: 'Portafolio profesional (Behance/Web), pitch de proyectos en inglés técnico y presentación a clientes y jurados internacionales.',
    teacherId: 'doc-brenda',
    teacherName: 'Licda. Brenda Alvarado',
    gradeId: '12',
    gradeName: '3° Año Bachillerato',
    sectionId: 'A',
    sectionName: 'Diseño Gráfico',
    subjectId: 'pitch-ingles-portfolio',
    icon: 'Presentation',
    color: '#F59E0B',
    status: 'upcoming',
    schedule: 'Semanas 39 y 40 • 30 H/Semana',
    classroom: 'Sala de Conferencias Internacional',
    unitsCount: 6,
    activitiesCount: 3,
    progress: 0,
    createdAt: '2026-07-15T08:00:00Z',
  },
];

// Helper para obtener descriptors técnicos enriquecidos por módulo
export const getModuleDescriptorData = (code: string): TechnicalModuleDescriptor => {
  const descriptorsMap: Record<string, Partial<TechnicalModuleDescriptor>> = {
    'BTVDG1.7': {
      code: 'BTVDG1.7',
      year: '1',
      title: 'Diseño de objetos vectoriales',
      hours: 126,
      weeks: 7,
      prerequisite: 'Noveno grado',
      field: 'Industrial',
      specialty: 'Diseño Gráfico',
      affineArea: 'Diseño y diagramación',
      competenceGeneral: 'Utilizar las herramientas básicas de creación de vectores para la elaboración de elementos gráficos digitales, aplicables a piezas gráficas.',
      moduleObjective: 'Utilizar las herramientas básicas de software digital para la creación de elementos vectoriales, combinando el uso de recursos de dibujo digital, aplicación de color y efectos en el proceso de diseño de un proyecto.',
      problematicSituation: {
        cause: 'Uso de software digital sin criterios ni fundamentos formales de diseño.',
        situation: 'En la actualidad muchas personas saben utilizar herramientas digitales básicas, pero no cuentan con el dominio de criterios de diseño vectorial ni precisión técnica de trazados.',
        effect: 'Piezas gráficas con trazados quebrados, falta de jerarquía visual y mala calidad en impresos.',
        summary: 'Falta de profesionales capacitados en el uso riguroso del dibujo vectorial para resolver piezas con alta funcionalidad y valor comunicacional.',
      },
      evaluationCriteria: [
        'Aplica las diversas herramientas de dibujo en la elaboración de recursos gráficos digitales.',
        'Domina el uso de la herramienta pluma para la ejecución de trazados vectoriales fluidos, simplificados y sin quiebres.',
        'Elabora recursos digitales básicos como íconos para la aplicación en piezas gráficas.',
        'Diseña recursos digitales complejos como ilustraciones vectoriales para piezas publicitarias.',
        'Configura archivos técnicos para artes finales según normas de imprenta digital y offset.',
      ],
      promotionCriteria: 'Comprobar haber alcanzado el Nivel 4 de Desempeño (7.0 mínimo).',
      developmentAxes: {
        desarrolloTecnico: 'Diseña piezas vectoriales con pluma, nodos y manejadores, configurando artes finales con resolución y perfiles de color óptimos.',
        desarrolloEmprendedor: 'Diseña recursos comerciales adaptados a las necesidades reales del brief del cliente.',
        desarrolloHumanoSocial: 'Trabaja cooperativamente, cuida detalles de presentación y respeta el feedback del equipo.',
        desarrolloAcademicoAplicado: 'Aplica conceptos matemáticos de geometría analítica, curvas Bézier, cuadrantes y teoría del color.',
      },
      currentProject: {
        id: 'proj-2026-btvdg17',
        academicYear: '2026',
        title: 'Campaña de Identidad Gráfica para Ecoparque Los Volcanes',
        theme: 'Diseño vectorial para la conservación de recursos naturales',
        targetClient: 'Ministerio de Medio Ambiente y Cooperativa Ecoturística',
        problemStatement: 'El Ecoparque carece de un sistema iconográfico y piezas vectoriales modernas para señalización y difusión turística responsable.',
        creativeBrief: 'Crear un set de 6 pictogramas temáticos, mascota vectorial y afiche promocional en formato A3 con arte final para serigrafía e impresión digital.',
        deliverables: ['Set de 6 íconos en AI/PDF', 'Mascota vectorial en 3 poses', 'Afiche promocional A3 con guías de corte y marcas de registro', 'Manual de uso técnico'],
        suggestedSoftware: ['Adobe Illustrator CS6/CC', 'Wacom Tablet'],
        materialsRequired: ['Papel bond 120g', 'Cartón ilustración', 'Prueba de color calibrada'],
        status: 'active',
      },
      availableProjects: [
        {
          id: 'proj-2025-btvdg17',
          academicYear: '2025',
          title: 'Sistema Iconográfico para Transporte Público Sostenible',
          theme: 'Movilidad urbana y señalética',
          targetClient: 'Viceministerio de Transporte (VMT)',
          problemStatement: 'Falta de pictogramas inclusivos y legibles para ciclovías y estaciones de buses.',
          creativeBrief: 'Diseñar 8 iconos vectoriales de señalética urbana y mapa esquemático de rutas.',
          deliverables: ['Manual de señalética vectorial', 'Artes finales a escala'],
          suggestedSoftware: ['Adobe Illustrator'],
          materialsRequired: ['Papel adhesivo', 'Cutter y regla'],
          status: 'archived',
        },
      ],
      resources: {
        materials: ['Papel bond carta', 'Libreta de bocetos', 'Cartón montaje', 'Lápices de grafito graduados'],
        equipment: ['Computadoras con Adobe Illustrator', 'Tabletas gráficas', 'Proyector multimedia'],
        furniture: ['Mesas de dibujo con ángulo ajustable', 'Bancos ergonómicos'],
        safety: ['Tabla de corte antideslizante', 'Regla metálica con base de corcho', 'Cutter con seguro'],
      },
      bibliography: {
        books: ['Adobe Creative Team. Classroom in a Book Illustrator', 'MEDIActive. Aprender Illustrator con 100 ejercicios'],
        websites: ['www.adobe.com', 'www.logopond.com', 'www.kuler.com'],
      },
    },
    'BTVDG2.7': {
      code: 'BTVDG2.7',
      year: '2',
      title: 'Diseño y construcción de empaques y viñetas',
      hours: 72,
      weeks: 4,
      prerequisite: 'Primer año de Bachillerato',
      field: 'Industrial',
      specialty: 'Diseño Gráfico',
      affineArea: 'Diseño y diagramación',
      competenceGeneral: 'Identificar los principios y procesos básicos de construcción y edición digital de empaques funcionales para el desarrollo de proyectos de diseño envases, empaques y viñetas para productos.',
      moduleObjective: 'Elaborar empaques y viñetas que cumplan con lineamientos establecidos de comunicación y funcionalidad, como parte importante del desarrollo de piezas de promoción y venta de productos.',
      problematicSituation: {
        cause: 'Desconocimiento del dibujo técnico-lineal y normativas técnicas de embalaje.',
        situation: 'Pocos diseñadores son capaces de desarrollar proyectos de empaques con equilibrio entre diseño estructural y gráfico.',
        effect: 'Empaques que colapsan en distribución o que no cumplen normas sanitarias y de etiquetado.',
        summary: 'Necesidad de capacitar a bachilleres en el desarrollo completo de troqueles funcionales, viñetas normadas y prototipos tridimensionales.',
      },
      evaluationCriteria: [
        'Realiza la estructura y troqueles de productos respondiendo a ergonomía, seguridad y manipulación.',
        'Desarrolla procesos de investigación de mercado y necesidades del consumidor salvadoreño.',
        'Diseña empaques y viñetas con código de barras, tabla nutricional y normativas legales.',
        'Construye domies y prototipos a escala 1:1 con acabados de alta calidad.',
      ],
      promotionCriteria: 'Comprobar haber alcanzado el Nivel 4 de Desempeño (7.0 mínimo).',
      developmentAxes: {
        desarrolloTecnico: 'Diseña troqueles con sisas, cortes y pestañas exactas en Illustrator/CAD y monta gráficos vectoriales.',
        desarrolloEmprendedor: 'Calcula costos de cartoncillo, mermas de troquelado y tiempos de ensamblado para MIPYMES.',
        desarrolloHumanoSocial: 'Fomenta el diseño ecológico y uso de cartones reciclables y tintas biodegradables.',
        desarrolloAcademicoAplicado: 'Aplica geometría espacial tridimensional, cálculo de volúmenes y redacción legal.',
      },
      currentProject: {
        id: 'proj-2026-btvdg27',
        academicYear: '2026',
        title: 'Línea de Empaque y Viñeta para Café Gourmet de Altura "Montecristo"',
        theme: 'Empaque sustentable con valor cultural salvadoreño',
        targetClient: 'Cooperativa de Caficultores de la Cordillera Apaneca-Ilamatepec',
        problemStatement: 'Los productores artesanales venden su café en bolsas genéricas sin protección hermética ni valor de marca.',
        creativeBrief: 'Diseñar una caja dispensadora con troquel autoarmable y viñeta frontal con laminado mate y detalles de origen.',
        deliverables: ['Plano técnico de troquel acotado', 'Arte final en CMYK a 300 DPI', 'Dummie físico armado a escala real', 'Ficha técnica de materiales'],
        suggestedSoftware: ['Adobe Illustrator', 'Adobe Photoshop'],
        materialsRequired: ['Cartoncillo sulfatado calibre 14', 'Cutter bisturí', 'Pegamento blanco libre de ácido'],
        status: 'active',
      },
      availableProjects: [
        {
          id: 'proj-2025-btvdg27',
          academicYear: '2025',
          title: 'Empaque de Dulces Típicos Salvadoreños para Exportación',
          theme: 'Identidad nostálgica y protección en transporte',
          targetClient: 'Asociación de Dulceros de San Vicente',
          problemStatement: 'El producto se quiebra en envíos internacionales por falta de cuna interior protectora.',
          creativeBrief: 'Troquel con separadores internos y ventana transparente de acetato biodegradable.',
          deliverables: ['Dummie con ventana', 'Plano de troquel'],
          suggestedSoftware: ['Adobe Illustrator'],
          materialsRequired: ['Cartón kraft', 'Acetato'],
          status: 'archived',
        },
      ],
      resources: {
        materials: ['Cartoncillo sulfatado', 'Papel ledger', 'Cutter y bisturí', 'Regla metálica con escala'],
        equipment: ['Computadoras con Illustrator', 'Plotter de corte / Impresora de pruebas'],
        furniture: ['Mesas de corte de madera tratada', 'Bancos de altura adaptable'],
        safety: ['Tabla de corte antideslizante', 'Gabacha de protección', 'Luz blanca de 5000K'],
      },
      bibliography: {
        books: ['Calver, Giles. What is packaging design', 'Denison, Edward. The big book of packaging prototypes'],
        websites: ['www.packagingoftheworld.com', 'www.lovelypackage.com'],
      },
    },
    'BTVDG3.3': {
      code: 'BTVDG3.3',
      year: '3',
      title: 'Creación de identidad corporativa',
      hours: 180,
      weeks: 6,
      prerequisite: 'Segundo año de Bachillerato',
      field: 'Industrial',
      specialty: 'Diseño Gráfico',
      affineArea: 'Estrategias conceptuales y artísticas',
      competenceGeneral: 'Desarrollar proyectos en el área de branding, como una estrategia fundamental de comunicación y proyección de una marca o producto.',
      moduleObjective: 'Aplicar los fundamentos básicos del diseño en la creación de diversas piezas que le den una identidad a empresas, personas, productos y servicios.',
      problematicSituation: {
        cause: 'Falta de análisis de identidad y copia de tendencias pasajeras sin investigación.',
        situation: 'Muchos diseñadores diseñan logotipos sin vincular la esencia de la marca ni elaborar manuales de uso técnico normado.',
        effect: 'Marcas vulnerables a mal uso, deformaciones y falta de diferenciación en el mercado.',
        summary: 'Se requiere formar diseñadores integrales capaces de conceptualizar identidades perdurables y manuales de marca profesionales.',
      },
      evaluationCriteria: [
        'Realiza investigación exhaustiva de la empresa, competencia y target.',
        'Conceptualiza y aplica semiótica en logotipos, isotipos e imagotipos.',
        'Diseña sistema de papelería corporativa (tarjetas, membrete, sobres, carpetas).',
        'Estructura el Manual de Identidad Visual con cotas, zona de reserva y usos permitidos.',
      ],
      promotionCriteria: 'Comprobar haber alcanzado el Nivel 4 de Desempeño (7.0 mínimo).',
      developmentAxes: {
        desarrolloTecnico: 'Vectorización precisa de isotipos, retícula constructiva y especificación de códigos Pantone, CMYK, RGB y Hexadecimal.',
        desarrolloEmprendedor: 'Genera valor de marca medible y presupuesto de implementación para clientes reales.',
        desarrolloHumanoSocial: 'Presenta el proyecto con ética, respetando derechos de autor y propiedad intelectual.',
        desarrolloAcademicoAplicado: 'Redacta un manual de marca de 24+ páginas con ortografía impecable y sustentación semiótica.',
      },
      currentProject: {
        id: 'proj-2026-btvdg33',
        academicYear: '2026',
        title: 'Branding e Identidad Corporativa para "Cacao Ancestral El Bálsamo"',
        theme: 'Revalorización de productos prehispánicos con estándares de exportación',
        targetClient: 'Cooperativa Agrícola de la Cordillera del Bálsamo',
        problemStatement: 'La cooperativa produce cacao fino pero carece de identidad corporativa formal para competir en ferias internacionales.',
        creativeBrief: 'Crear la identidad de marca completa (imagotipo, retícula, paleta cromática, tipografías corporativas, papelería institucional y manual de marca de 30 páginas).',
        deliverables: ['Manual de Marca en PDF interactivo', 'Set de papelería institucional impresa', 'Mockups de uniformes y fachada', 'Archivos vectoriales maestros'],
        suggestedSoftware: ['Adobe Illustrator', 'Adobe InDesign', 'Adobe Photoshop'],
        materialsRequired: ['Papel opalina 220g', 'Papel hilo para papelería', 'Carpeta corporativa'],
        status: 'active',
      },
      availableProjects: [],
      resources: {
        materials: ['Papel bond y opalina', 'Cartón ilustración', 'Libreta de bocetos de cuadrícula'],
        equipment: ['Computadoras de alto rendimiento', 'Tabletas Wacom', 'Proyector HDMI'],
        furniture: ['Mesas de trabajo colaborativo', 'Pizarra acrílica'],
        safety: ['Ambiente ergonómico e iluminación adecuada'],
      },
      bibliography: {
        books: ['Wally Olins. On Brand', 'Kevin Roberts. LoveMarks', 'Melissa Davis. The Fundamentals of Branding'],
        websites: ['www.brandnew.com', 'www.logopond.com'],
      },
    },
  };

  const base = descriptorsMap[code];
  const course = BTV_GRAPHIC_DESIGN_COURSES.find((c) => c.code === code);

  if (base && course) {
    return {
      code: course.code,
      year: course.technicalYear,
      title: course.name,
      hours: course.hours,
      weeks: course.weeks,
      prerequisite: base.prerequisite || (course.technicalYear === '1' ? 'Noveno grado' : course.technicalYear === '2' ? '1° Año Bachillerato' : '2° Año Bachillerato'),
      field: 'Industrial',
      specialty: 'Diseño Gráfico',
      affineArea: (course.affineArea as any) || 'Diseño y diagramación',
      competenceGeneral: base.competenceGeneral || `Desarrollar competencias técnicas y profesionales en ${course.name}.`,
      moduleObjective: base.moduleObjective || `Aplicar los procesos y herramientas de ${course.name} en proyectos reales.`,
      problematicSituation: base.problematicSituation || {
        cause: 'Falta de dominio en técnicas especializadas de diseño y comunicación.',
        situation: 'El mercado demanda profesionales técnicos con experiencia práctica y competencias orientadas a la acción.',
        effect: 'Baja inserción laboral y proyectos de baja calidad visual.',
        summary: `Aplicación de metodologías activas en ${course.name}.`,
      },
      evaluationCriteria: base.evaluationCriteria || [
        'Aplica los fundamentos técnicos y herramientas especializadas.',
        'Desarrolla las 6 etapas de la acción completa en su proyecto.',
        'Elabora racionales creativos y bitácoras de trabajo.',
        'Presenta resultados de calidad técnica y estética.',
      ],
      promotionCriteria: 'Comprobar haber alcanzado el Nivel 4 de Desempeño (7.0).',
      developmentAxes: base.developmentAxes || {
        desarrolloTecnico: `Aplica herramientas y técnicas de ${course.name}.`,
        desarrolloEmprendedor: 'Identifica oportunidades comerciales y de autoempleo.',
        desarrolloHumanoSocial: 'Trabaja en equipo con liderazgo participativo y ética.',
        desarrolloAcademicoAplicado: 'Aplica conceptos científicos, ortografía y redacción técnica.',
      },
      actionStages: createActionStages(
        course.name,
        `Ejecución de actividades técnicas de taller y laboratorio para ${course.name}`,
        ['Adobe Creative Cloud', 'Mesa de dibujo', 'Herramientas de corte y calibrado']
      ),
      saberesPrevios: [
        { id: 'sp-1', description: `Conceptos fundamentales relacionados a ${course.name}`, appreciation: 'POCO' },
        { id: 'sp-2', description: 'Manejo de herramientas de dibujo y software digital básico', appreciation: 'MUCHO' },
        { id: 'sp-3', description: 'Normativas técnicas de producción y arte final', appreciation: 'NADA' },
        { id: 'sp-4', description: 'Redacción de racionales creativos y briefs de cliente', appreciation: 'POCO' },
      ],
      saberesNecesarios: [
        { id: 'sn-1', description: `Dominio práctico de herramientas y metodologías de ${course.name}` },
        { id: 'sn-2', description: 'Planificación y cronograma de ruta crítica para proyectos' },
        { id: 'sn-3', description: 'Control de calidad en pruebas de color y artes finales' },
        { id: 'sn-4', description: 'Defensa técnica y argumentación con clientes' },
      ],
      currentProject: base.currentProject || {
        id: `proj-2026-${code.toLowerCase().replace('.', '')}`,
        academicYear: '2026',
        title: `Proyecto Integrador Anual: ${course.name}`,
        theme: 'Innovación gráfica y desarrollo socioeconómico',
        targetClient: 'Empresa o institución comunitaria aliada',
        problemStatement: `Desarrollo de soluciones visuales aplicando las competencias de ${course.name}.`,
        creativeBrief: 'Elaborar un conjunto de piezas gráficas y prototipos aplicando la metodología de acción completa.',
        deliverables: ['Bocetos y bitácora', 'Artes finales digitales', 'Prototipo o muestra física', 'Informe técnico'],
        suggestedSoftware: ['Adobe Illustrator', 'Adobe Photoshop', 'Adobe InDesign'],
        materialsRequired: ['Papel especializado', 'Herramientas de corte'],
        status: 'active',
      },
      availableProjects: base.availableProjects || [],
      resources: base.resources || {
        materials: ['Papel bond', 'Libreta de bocetos', 'Lápices graduados'],
        equipment: ['Computadoras con software de diseño', 'Proyector'],
        furniture: ['Mesas de dibujo', 'Sillas ergonómicas'],
        safety: ['Tabla de corte', 'Regla de seguridad'],
      },
      bibliography: base.bibliography || {
        books: ['MINED. Fundamentos del Bachillerato Técnico Vocacional', 'Diseño Gráfico Aplicado'],
        websites: ['www.mined.gob.sv', 'www.adobe.com'],
      },
    };
  }

  // Generic fallback descriptor
  return {
    code: code || 'BTVDG1.0',
    year: '1',
    title: course?.name || 'Módulo Técnico',
    hours: course?.hours || 72,
    weeks: course?.weeks || 4,
    prerequisite: 'Noveno grado',
    field: 'Industrial',
    specialty: 'Diseño Gráfico',
    affineArea: 'Diseño y diagramación',
    competenceGeneral: 'Aplicar procesos técnicos de diseño gráfico.',
    moduleObjective: 'Desarrollar competencias en la especialidad técnica.',
    problematicSituation: {
      cause: 'Falta de formación técnica sistemática.',
      situation: 'Desafíos en la resolución de problemas visuales.',
      effect: 'Limitación de oportunidades laborales.',
      summary: 'Formación basada en proyectos de acción completa.',
    },
    evaluationCriteria: ['Aplica criterios de diseño', 'Ejecuta proyectos en 6 etapas'],
    promotionCriteria: 'Nivel 4 mínimo (7.0)',
    developmentAxes: {
      desarrolloTecnico: 'Dominio de herramientas de diseño.',
      desarrolloEmprendedor: 'Gestión de proyectos y negocios.',
      desarrolloHumanoSocial: 'Valores cooperativos y ética.',
      desarrolloAcademicoAplicado: 'Racional técnico y comunicación.',
    },
    actionStages: createActionStages('Módulo Técnico', 'Ejecución de actividades de diseño', ['Adobe Creative Cloud']),
    saberesPrevios: [],
    saberesNecesarios: [],
    currentProject: {
      id: 'proj-default',
      academicYear: '2026',
      title: 'Proyecto Anual de Módulo',
      theme: 'Diseño Gráfico',
      targetClient: 'Cliente local',
      problemStatement: 'Problema gráfico real.',
      creativeBrief: 'Desarrollar piezas gráficas.',
      deliverables: ['Arte final'],
      suggestedSoftware: ['Adobe Illustrator'],
      materialsRequired: ['Papel'],
      status: 'active',
    },
    availableProjects: [],
    resources: { materials: [], equipment: [], furniture: [], safety: [] },
    bibliography: { books: [] },
  };
};

// Generador de Nuevos Proyectos y Briefs Anuales para Docentes
export interface AnnualProjectTemplate {
  title: string;
  theme: string;
  targetClient: string;
  problemStatement: string;
  creativeBrief: string;
  deliverables: string[];
  suggestedSoftware: string[];
  materialsRequired: string[];
}

export const GENERATE_ANNUAL_PROJECT = (
  moduleCode: string,
  academicYear: string,
  customTopic?: string
): ProjectBrief => {
  const templates: Record<string, AnnualProjectTemplate[]> = {
    'BTVDG1.7': [
      {
        title: `Campaña de Señalética e Iconografía Sostenible ${academicYear}`,
        theme: 'Diseño vectorial para eco-rutas y áreas protegidas de El Salvador',
        targetClient: 'Parque Nacional El Boquerón & MARN',
        problemStatement: 'Falta de mapas vectoriales y señalética comprensible para turistas locales y extranjeros.',
        creativeBrief: 'Diseñar un sistema de 8 pictogramas vectoriales normalizados y un mapa ilustrado en alta resolución.',
        deliverables: ['Iconografía en SVG/AI', 'Mapa vectorial 50x70 cm', 'Manual de normas de señalética'],
        suggestedSoftware: ['Adobe Illustrator', 'Inkscape'],
        materialsRequired: ['Papel bond 150g', 'Cartón montaje'],
      },
      {
        title: `Rediseño Vectorial de Marcas Artesanales ${academicYear}`,
        theme: 'Identidad geométrica para alfarería de Ilobasco',
        targetClient: 'Asociación de Artesanos de Cabañas',
        problemStatement: 'Marcas con baja legibilidad en aplicaciones pequeñas como sellos y etiquetas.',
        creativeBrief: 'Construir logotipos geométricos con retícula modular y versión en positivo/negativo.',
        deliverables: ['Guía de construcción vectorial', 'Arte final en 4 formatos'],
        suggestedSoftware: ['Adobe Illustrator'],
        materialsRequired: ['Papel opalina'],
      },
    ],
    'BTVDG2.7': [
      {
        title: `Línea de Empaque para Snacks Nativos de Exportación ${academicYear}`,
        theme: 'Empaques de chips de plátano y yuca con troquel innovador',
        targetClient: 'Cooperativa Agroindustrial de Usulután',
        problemStatement: 'Pérdida de frescura y baja presencia en estantería frente a marcas internacionales.',
        creativeBrief: 'Diseñar caja expositora tipo display con troquel autoarmable sin pegamento y bolsa hermética.',
        deliverables: ['Plano de troquel 1:1', 'Dummie armado y fotografiado', 'Tabla nutricional reglamentada'],
        suggestedSoftware: ['Adobe Illustrator', 'Photoshop'],
        materialsRequired: ['Cartón microcorrugado', 'Acetato', 'Cutter bisturí'],
      },
      {
        title: `Eco-Packaging para Cosméticos de Miel de Abeja ${academicYear}`,
        theme: 'Troqueles hexagonales sin adhesivos químicos',
        targetClient: 'Apicultores de Suchitoto',
        problemStatement: 'Necesidad de empaques biodegradables con estética premium para jabones y cremas.',
        creativeBrief: 'Desarrollar troquel plegable inspirado en panales de abeja con viñetas en papel kraft.',
        deliverables: ['Prototipo 3D funcional', 'Viñeta serigráfica'],
        suggestedSoftware: ['Adobe Illustrator'],
        materialsRequired: ['Cartulina kraft 300g', 'Lápiz de cera'],
      },
    ],
    'BTVDG3.3': [
      {
        title: `Branding Integral y Manual de Marca para Start-up Tecnológica ${academicYear}`,
        theme: 'Identidad visual para fintech salvadoreña de inclusión financiera',
        targetClient: 'Fintech ChivoPay Innovation Labs',
        problemStatement: 'Marca emergente que requiere transmitir seguridad bancaria, dinamismo y juventud.',
        creativeBrief: 'Crear sistema de identidad 360°: isotipo dinámico, manual de marca de 35 páginas, app UI assets y papelería corporativa.',
        deliverables: ['Manual de Marca interactivo en PDF', 'Kit de marca vectorial', 'Mockups de aplicación móvil', 'Papelería impresa'],
        suggestedSoftware: ['Adobe Illustrator', 'Adobe InDesign', 'Figma'],
        materialsRequired: ['Papel hilo 120g', 'Carpeta corporativa troquelada'],
      },
      {
        title: `Retro-Branding de Marca Emblemática Salvadoreña ${academicYear}`,
        theme: 'Modernización de marca tradicional sin perder valor histórico',
        targetClient: 'Panadería Tradicional San José (Fundada en 1970)',
        problemStatement: 'Pérdida de conexión con nuevas generaciones por imagen obsoleta.',
        creativeBrief: 'Rediseñar el imagotipo aplicando proporciones áureas y crear sistema de papelería vintage moderno.',
        deliverables: ['Manual de identidad', 'Set de papelería y uniformes'],
        suggestedSoftware: ['Adobe Illustrator', 'InDesign'],
        materialsRequired: ['Papel reciclado premium'],
      },
    ],
  };

  const pool = templates[moduleCode] || [
    {
      title: `Proyecto Formativo Innovador ${academicYear}: ${customTopic || 'Diseño Gráfico Aplicado'}`,
      theme: 'Solución a problemática real del sector productivo',
      targetClient: 'Empresa / Institución de la comunidad',
      problemStatement: 'Necesidad de comunicación gráfica y posicionamiento visual.',
      creativeBrief: 'Desarrollar la estrategia de diseño y piezas gráficas aplicando las 6 etapas de la acción completa.',
      deliverables: ['Bitácora de investigación y bocetos', 'Artes finales normalizados', 'Prototipo evaluado', 'Informe técnico'],
      suggestedSoftware: ['Adobe Creative Cloud'],
      materialsRequired: ['Papel de dibujo', 'Herramientas de corte'],
    },
  ];

  const selected = pool[Math.floor(Math.random() * pool.length)];

  return {
    id: `proj-${academicYear}-${moduleCode.toLowerCase().replace('.', '')}-${Date.now()}`,
    academicYear,
    title: selected.title,
    theme: selected.theme,
    targetClient: selected.targetClient,
    problemStatement: selected.problemStatement,
    creativeBrief: selected.creativeBrief,
    deliverables: selected.deliverables,
    suggestedSoftware: selected.suggestedSoftware,
    materialsRequired: selected.materialsRequired,
    status: 'active',
  };
};
