// GENERATED BY GEMINI — Campus Salesiano San José
// Servicio de Documentación Curricular Institucional (Jornalización, Plan Didáctico, Guiones, Cuadros, Temarios y Rúbrica 29 Ítems)

import {
  CSSJCalendarPeriod,
  CSSJJornalizacion,
  CSSJPlanDidactico,
  CSSJGuionClase,
  CSSJCuadroActividades,
  CSSJTemarioEvaluacion,
  BTVRubricCriterionItem,
  MinedLevel,
} from '../types';

// ==========================================
// 1. RÚBRICA NORMATIVA BTV DISEÑO GRÁFICO (29 ÍTEMS OFICIALES)
// ==========================================
export const BTV_29_RUBRIC_ITEMS: BTVRubricCriterionItem[] = [
  // --- EJE 1: TÉCNICO - TECNOLÓGICO (35% PONDERACIÓN) ---
  {
    id: 'crit-t1',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T1',
    name: 'Identidad Gráfica y Dominio Vectorial',
    description: 'Destreza en el manejo de herramientas vectoriales (Illustrator), nodos Bézier, operaciones booleanas y coherencia formal del imagotipo.',
    descriptorNivel1: 'Presenta trazados vectoriales deformados con exceso de nodos y problemas de proporción sin orientación visual.',
    descriptorNivel2: 'Construye vectores básicos pero con irregularidades en curvas y unión de segmentos.',
    descriptorNivel3: 'Domina el dibujo vectorial con apoyo ocasional para optimizar anclas y proporciones complejas.',
    descriptorNivel4: 'Construye identidades vectoriales limpias, con economía de nodos y precisión geométrica por sí mismo(a).',
    descriptorNivel5: 'Diseña sistemas de identidad vectorial impecables, aplicando retículas avanzadas y capacitando a sus compañeros.',
  },
  {
    id: 'crit-t2',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T2',
    name: 'Tratamiento y Retoque Digital de Imágenes',
    description: 'Edición no destructiva en Photoshop, máscaras de capa, trazados de recorte, corrección tonal y perfiles de color.',
    descriptorNivel1: 'Aplica filtros destructivos sin máscaras, alterando la resolución y generando pixelación.',
    descriptorNivel2: 'Usa capas de ajuste pero los calados y transiciones de recorte son duros y evidentes.',
    descriptorNivel3: 'Realiza fotomontajes coherentes requiriendo asistencia en igualación de iluminación y sombras.',
    descriptorNivel4: 'Ejecuta retoque fotográfico profesional, integración tonal y máscaras impecables por sí mismo(a).',
    descriptorNivel5: 'Domina técnicas avanzadas de photobashing, frequency separation y color grading con calidad de estudio.',
  },
  {
    id: 'crit-t3',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T3',
    name: 'Maquetación y Retícula Editorial',
    description: 'Estructuración de páginas maestras, grillas modulares, estilos de párrafo/carácter y flujo editorial en InDesign.',
    descriptorNivel1: 'Coloca cajas de texto sin retícula ni jerarquía, con desbordes y líneas viudas/huérfanas.',
    descriptorNivel2: 'Emplea márgenes básicos pero omite estilos automatizados y la alineación a rejilla base es irregular.',
    descriptorNivel3: 'Diseña la maquetación aplicando páginas maestras y estilos con eventual revisión de espaciados.',
    descriptorNivel4: 'Estructura publicaciones editoriales fluidas con grillas complejas y estilos jerárquicos autónomamente.',
    descriptorNivel5: 'Crea sistemas editoriales complejos de alta foliación con tablas de contenido y variables automatizadas.',
  },
  {
    id: 'crit-t4',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T4',
    name: 'Preprensa, Separación de Color y Artes Finales',
    description: 'Configuración técnica para imprenta: sangrado (bleed), marcas de registro/corte, perfiles CMYK/Pantone y trapping.',
    descriptorNivel1: 'Envía archivos en RGB, sin sangrado y con imágenes en baja resolución imposibles de imprimir.',
    descriptorNivel2: 'Incluye sangrado pero olvida incrustar fuentes o vincular imágenes en alta resolución.',
    descriptorNivel3: 'Prepara el arte final en PDF/X con adecuada separación de tintas bajo supervisión docente.',
    descriptorNivel4: 'Genera paquetes de arte final y PDF/X-1a certificados para imprenta offset o digital por sí mismo(a).',
    descriptorNivel5: 'Audita y verifica técnicamente los artes de sus compañeros detectando errores de sobreimpresión y cobertura de tinta.',
  },
  {
    id: 'crit-t5',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T5',
    name: 'Teoría del Color y Armonía Cromática',
    description: 'Aplicación psicológica, cultural y técnica del círculo cromático, contrastes tonales y accesibilidad visual.',
    descriptorNivel1: 'Utiliza colores disonantes y sin contraste que anulan la legibilidad del mensaje.',
    descriptorNivel2: 'Aplica combinaciones cromáticas estándar con leves problemas de balance perceptual.',
    descriptorNivel3: 'Aplica esquemas análogos, complementarios o triádicos adecuados al concepto con guía puntual.',
    descriptorNivel4: 'Maneja paletas cromáticas estratégicas con ratios de contraste WCAG óptimos de manera autónoma.',
    descriptorNivel5: 'Justifica semiótica y técnicamente cada elección cromática, creando manuales de marca con equivalencias HEX/RGB/CMYK/Pantone.',
  },
  {
    id: 'crit-t6',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T6',
    name: 'Sintaxis y Jerarquía Tipográfica',
    description: 'Selección tipográfica, kerning, tracking, interlineado, legibilidad y correspondencia conceptual de fuentes.',
    descriptorNivel1: 'Mezcla más de 4 fuentes incompatibles con distorsión de escala horizontal/vertical.',
    descriptorNivel2: 'Selecciona fuentes legibles pero la jerarquía entre titulares, subtítulos y cuerpo es débil.',
    descriptorNivel3: 'Aplica maridajes tipográficos armónicos controlando interlineados con asistencia ocasional.',
    descriptorNivel4: 'Establece jerarquías tipográficas claras con micro y macro-tipografía impecable por sí mismo(a).',
    descriptorNivel5: 'Diseña piezas con excelencia tipográfica, personalizando glifos y manejando principios ortotipográficos avanzados.',
  },
  {
    id: 'crit-t7',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T7',
    name: 'Bocetería y Conceptualización Visual',
    description: 'Exploración creativa mediante bocetos rápidos (thumbnails), mapas mentales, moodboards y síntesis formal.',
    descriptorNivel1: 'Pasa directo al software sin realizar bocetos previos ni exploración de alternativas.',
    descriptorNivel2: 'Presenta bocetos mínimos y literales sin profundidad en la síntesis conceptual.',
    descriptorNivel3: 'Desarrolla variedad de propuestas dibujadas a mano con buena estructura compositiva.',
    descriptorNivel4: 'Documenta un proceso rico de bocetaje, síntesis y evolución morfológica antes de digitalizar.',
    descriptorNivel5: 'Lidera sesiones de visual thinking y moodboarding con alta capacidad de conceptualización abstracta.',
  },
  {
    id: 'crit-t8',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T8',
    name: 'Construcción de Dummies y Prototipos',
    description: 'Elaboración manual de maquetas físicas (empaques, plegables, encuadernación) y prototipos digitales interactivos.',
    descriptorNivel1: 'Dummies desarmados, con cortes imprecisos o pegado deficiente que no cumplen la escala.',
    descriptorNivel2: 'Elabora la maqueta con pequeños desfases en líneas de doblez o armado estructural.',
    descriptorNivel3: 'Construye prototipos funcionales y presentables con asistencia en acabados especiales.',
    descriptorNivel4: 'Produce dummies con cortes exactos, troquelado preciso y acabados de calidad comercial.',
    descriptorNivel5: 'Diseña estructuras volumétricas innovadoras y prototipos interactivos testeados con usuarios reales.',
  },
  {
    id: 'crit-t9',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T9',
    name: 'Optimización de Salidas y Formatos Digitales',
    description: 'Exportación de activos web/app (SVG, WebP, PNG-24), compresión sin pérdida y adaptación responsive.',
    descriptorNivel1: 'Exporta imágenes pesadas y distorsionadas sin considerar el medio de publicación final.',
    descriptorNivel2: 'Exporta en formatos adecuados pero con peso excesivo para plataformas digitales.',
    descriptorNivel3: 'Genera activos optimizados para redes y web con orientación ocasional en resoluciones.',
    descriptorNivel4: 'Configura y optimiza assets digitales para pantallas de alta densidad (Retina/@2x/@3x) autónomamente.',
    descriptorNivel5: 'Estandariza guías de exportación y repositorios de diseño con nombrado semántico y automatización.',
  },

  // --- EJE 2: EMPRENDEDOR Y PRODUCTIVO (25% PONDERACIÓN) ---
  {
    id: 'crit-e1',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E1',
    name: 'Análisis de Mercado y Perfil de Usuario (Target)',
    description: 'Investigación del público meta, mapa de empatía, arquetipo de cliente y benchmarking de la competencia.',
    descriptorNivel1: 'Desconoce las características de la audiencia destinataria de la propuesta gráfica.',
    descriptorNivel2: 'Describe el target con datos demográficos generales sin profundizar en hábitos y necesidades.',
    descriptorNivel3: 'Define el buyer persona y analiza competidores directos con soporte metodológico.',
    descriptorNivel4: 'Construye perfiles de usuario y mapas de empatía fundamentados que guían la propuesta visual.',
    descriptorNivel5: 'Aplica investigación cualitativa y cuantitativa avanzada para identificar nichos de mercado desatendidos.',
  },
  {
    id: 'crit-e2',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E2',
    name: 'Formulación y Cumplimiento del Brief de Diseño',
    description: 'Interpretación de requerimientos del cliente, objetivos SMART, alcance, entregables y limitantes.',
    descriptorNivel1: 'Ignora las especificaciones del brief entregando piezas que no responden a la necesidad.',
    descriptorNivel2: 'Cumple parcialmente los requerimientos omitiendo detalles de formato o lineamientos de marca.',
    descriptorNivel3: 'Interpreta el brief y elabora un contra-brief adecuado con asistencia del docente.',
    descriptorNivel4: 'Desarrolla proyectos respondiendo con exactitud a cada punto del brief técnico y comercial.',
    descriptorNivel5: 'Formula briefs estratégicos para clientes reales anticipando riesgos y proponiendo soluciones integrales.',
  },
  {
    id: 'crit-e3',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E3',
    name: 'Costeo, Presupuestos y Hoja de Producción',
    description: 'Cálculo de horas-diseño, depreciación, insumos, costos de imprenta, mermas e impuestos en El Salvador.',
    descriptorNivel1: 'No presenta presupuesto o fija precios arbitrarios sin base de costos ni rentabilidad.',
    descriptorNivel2: 'Calcula costos de materiales pero omite el valor de sus honorarios profesionales.',
    descriptorNivel3: 'Elabora cotizaciones comerciales considerando mano de obra y materiales con guía docente.',
    descriptorNivel4: 'Formula presupuestos profesionales detallados con desglose de costos fijos, variables y utilidad.',
    descriptorNivel5: 'Maneja hojas de costeo dinámicas y contratos de prestación de servicios de diseño bajo marco legal salvadoreño.',
  },
  {
    id: 'crit-e4',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E4',
    name: 'Matriz FODA y Posicionamiento Estratégico',
    description: 'Evaluación de Fortalezas, Oportunidades, Debilidades y Amenazas de la marca y su entorno comercial.',
    descriptorNivel1: 'No identifica los factores internos y externos que afectan la viabilidad del proyecto.',
    descriptorNivel2: 'Completa la matriz FODA de forma superficial sin conectar con la estrategia visual.',
    descriptorNivel3: 'Elabora la matriz FODA y formula cruces estratégicos (FO, FA, DO, DA) con apoyo docente.',
    descriptorNivel4: 'Diseña estrategias de posicionamiento de marca directamente derivadas de los hallazgos del FODA.',
    descriptorNivel5: 'Propone modelos de negocio Canvas vinculados a estrategias de branding de alto impacto en el mercado local.',
  },
  {
    id: 'crit-e5',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E5',
    name: 'Gestión del Tiempo y Ruta Crítica',
    description: 'Planificación de cronograma (diagrama de Gantt), cumplimiento de hitos y control de entregas por fase.',
    descriptorNivel1: 'Trabaja de manera desorganizada acumulando tareas y entregando fuera del plazo sin justificación.',
    descriptorNivel2: 'Establece fechas pero incurre en retrasos en las fases intermedias de bocetaje y aprobación.',
    descriptorNivel3: 'Sigue el cronograma establecido cumpliendo los hitos principales con recordatorios puntuales.',
    descriptorNivel4: 'Administra su tiempo eficientemente, cumpliendo las 6 etapas de la Acción Completa en los plazos fijados.',
    descriptorNivel5: 'Optimiza los flujos de trabajo del equipo, aplicando metodologías ágiles (Scrum/Kanban) en el taller.',
  },
  {
    id: 'crit-e6',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E6',
    name: 'Propuesta de Valor y Solución Innovadora',
    description: 'Diferenciación de la solución gráfica, aporte creativo y resolución de la problemática real del sector.',
    descriptorNivel1: 'Presenta soluciones genéricas que imitan plantillas existentes sin valor diferenciador.',
    descriptorNivel2: 'Propone ideas funcionales pero convencionales sin impacto disruptivo.',
    descriptorNivel3: 'Aporta elementos creativos novedosos que enriquecen la propuesta visual del cliente.',
    descriptorNivel4: 'Desarrolla soluciones de diseño originales y pertinentes que generan valor tangible a la marca.',
    descriptorNivel5: 'Crea propuestas de diseño con alto grado de innovación social y comercial reconocidas externamente.',
  },
  {
    id: 'crit-e7',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E7',
    name: 'Sustentación Comercial y Pitch de Venta',
    description: 'Defensa persuasiva, oratoria profesional y argumentación técnica del proyecto ante jurado o cliente.',
    descriptorNivel1: 'Muestra inseguridad, lee diapositivas y no logra justificar las decisiones de diseño adoptadas.',
    descriptorNivel2: 'Explica el proyecto pero le cuesta responder preguntas técnicas sobre costos o producción.',
    descriptorNivel3: 'Presenta con claridad y seguridad apoyándose en material visual estructurado.',
    descriptorNivel4: 'Defiende su propuesta con elocuencia, dominio técnico y seguridad comercial convincente.',
    descriptorNivel5: 'Realiza pitches comerciales de nivel profesional, cautivando a la audiencia y cerrando negociaciones.',
  },

  // --- EJE 3: HUMANO Y SOCIAL (20% PONDERACIÓN) ---
  {
    id: 'crit-h1',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H1',
    name: 'Ética Profesional y Respeto a Derechos de Autor',
    description: 'Uso de licencias Creative Commons/Copyright, citación de recursos tipográficos y rechazo total al plagio.',
    descriptorNivel1: 'Copia diseños o recursos protegidos sin atribución ni autorización de derechos.',
    descriptorNivel2: 'Utiliza recursos de bancos de imágenes sin verificar los términos de licencia comercial.',
    descriptorNivel3: 'Verifica licencias y atribuye fuentes con adecuada orientación del docente.',
    descriptorNivel4: 'Respeta rigurosamente la propiedad intelectual y produce piezas originales con licencias claras.',
    descriptorNivel5: 'Promueve activamente la cultura de la legalidad y el registro de marcas en el marco del CNR salvadoreño.',
  },
  {
    id: 'crit-h2',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H2',
    name: 'Trabajo Cooperativo y Corresponsabilidad',
    description: 'Colaboración activa en equipo, distribución equitativa de cargas y resolución pacífica de discrepancias.',
    descriptorNivel1: 'Muestra resistencia al trabajo en equipo o delega toda la carga en sus compañeros.',
    descriptorNivel2: 'Participa sólo en lo asignado sin mostrar interés por la integración global del proyecto.',
    descriptorNivel3: 'Colabora activamente en el grupo y apoya en la consecución de las metas colectivas.',
    descriptorNivel4: 'Demuestra liderazgo positivo, escucha activa y corresponsabilidad en el éxito del equipo.',
    descriptorNivel5: 'Facilita la cohesión grupal, media en desacuerdos y maximiza las fortalezas individuales del taller.',
  },
  {
    id: 'crit-h3',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H3',
    name: 'Vivencia del Carisma y Valores Salesianos',
    description: 'Amabilidad (Amorevolezza), respeto, solidaridad con los necesitados y espíritu de familia en el aula.',
    descriptorNivel1: 'Muestra actitudes displicentes o irrespetuosas hacia sus pares y docentes.',
    descriptorNivel2: 'Mantiene un comportamiento pasivo sin involucrarse en las dinámicas comunitarias del colegio.',
    descriptorNivel3: 'Practica la convivencia fraterna y el buen trato diario en todas las actividades escolares.',
    descriptorNivel4: 'Encarna el Sistema Preventivo de Don Bosco con alegría, laboriosidad y empatía constante.',
    descriptorNivel5: 'Es referente moral y salesiano para sus compañeros, animando siempre desde el servicio desinteresado.',
  },
  {
    id: 'crit-h4',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H4',
    name: 'Puntualidad y Cumplimiento Normativo CSSJ',
    description: 'Puntualidad en ingresos, cumplimiento del reglamento interno del Colegio Salesiano San José.',
    descriptorNivel1: 'Incurre en impuntualidades recurrentes y requiere recordatorios disciplinarios continuos.',
    descriptorNivel2: 'Llega a tiempo a clases pero presenta entregas al límite o con justificantes frecuentes.',
    descriptorNivel3: 'Cumple puntualmente con sus horarios y reglamentos en el 90% de las ocasiones.',
    descriptorNivel4: 'Es modelo de puntualidad, asistencia y cumplimiento ejemplar del manual de convivencia.',
    descriptorNivel5: 'Impulsa a su grupo al cumplimiento estricto y puntual de todos los compromisos formativos.',
  },
  {
    id: 'crit-h5',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H5',
    name: 'Seguridad Ocupacional y Ergonomía en Taller',
    description: 'Postura frente a la computadora, pausas activas, iluminación adecuada y prevención de lesiones posturales.',
    descriptorNivel1: 'Adopta malas posturas frente al monitor e ignora las normas de seguridad del laboratorio.',
    descriptorNivel2: 'Corrige la postura sólo cuando se le señala, sin interiorizar el hábito ergonómico.',
    descriptorNivel3: 'Mantiene una estación de trabajo ergonómica y realiza pausas activas durante jornadas largas.',
    descriptorNivel4: 'Aplica de forma autónoma principios de salud laboral, ergonomía y cuidado de la visión.',
    descriptorNivel5: 'Diseña y difunde campañas de prevención ergonómica y bienestar físico para el taller de diseño.',
  },
  {
    id: 'crit-h6',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H6',
    name: 'Orden, Limpieza y Cuidado de Equipos',
    description: 'Manipulación responsable de computadoras, tabletas gráficas, guillotinas, adhesivos y espacio común.',
    descriptorNivel1: 'Deja sucio su puesto de trabajo, manipula herramientas cortantes de forma descuidada.',
    descriptorNivel2: 'Limpia su área únicamente ante llamados de atención del encargado de taller.',
    descriptorNivel3: 'Mantiene su estación limpia y cuida los equipos informáticos asignados.',
    descriptorNivel4: 'Es sumamente ordenado(a) con sus herramientas, sustratos y periféricos en todo momento.',
    descriptorNivel5: 'Organiza y lidera jornadas de mantenimiento preventivo y limpieza general del taller de diseño.',
  },
  {
    id: 'crit-h7',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H7',
    name: 'Sostenibilidad y Ecodiseño Responsable',
    description: 'Aprovechamiento de sustratos, reducción de mermas de papel, uso de tintas biodegradables y reciclaje.',
    descriptorNivel1: 'Desperdicia pliegos enteros de papel y desecha insumos reutilizables sin criterio.',
    descriptorNivel2: 'Recicla únicamente cuando el docente lo exige en tareas específicas.',
    descriptorNivel3: 'Optimiza el trazado de pliegos para minimizar el desperdicio de sustratos de impresión.',
    descriptorNivel4: 'Integra principios de ecodiseño y economía circular en el empaque y producción de sus piezas.',
    descriptorNivel5: 'Desarrolla proyectos con huella de carbono reducida y sustratos 100% ecológicos o reciclados.',
  },

  // --- EJE 4: ACADÉMICO APLICADO (20% PONDERACIÓN) ---
  {
    id: 'crit-a1',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A1',
    name: 'Ortografía, Redacción y Corrección de Estilo',
    description: 'Escritura impecable en piezas gráficas, acentuación, puntuación y coherencia en titulares y cuerpos de texto.',
    descriptorNivel1: 'Entrega piezas con faltas ortográficas graves en titulares y errores de concordancia.',
    descriptorNivel2: 'Presenta descuidos menores de puntuación o tildes que afectan la profesionalidad del texto.',
    descriptorNivel3: 'Redacta textos claros y correctamente puntuados con mínima corrección docente.',
    descriptorNivel4: 'Escribe copys y textos editoriales impecables gramaticalmente y con alto poder comunicativo.',
    descriptorNivel5: 'Ejerce funciones de corrección de estilo editorial para todas las publicaciones del grupo.',
  },
  {
    id: 'crit-a2',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A2',
    name: 'Semiótica, Retórica y Significación Visual',
    description: 'Uso consciente de metáforas, metonimias, signos, símbolos, denotación y connotación en el mensaje.',
    descriptorNivel1: 'Coloca elementos visuales sin justificación simbólica ni correspondencia con el mensaje.',
    descriptorNivel2: 'Utiliza símbolos muy obvios o clichés gráficos con escasa profundidad semiótica.',
    descriptorNivel3: 'Aplica figuras retóricas visuales coherentes con el concepto comunicacional.',
    descriptorNivel4: 'Construye metáforas visuales ricas y sofisticadas con alta pregnancia en el receptor.',
    descriptorNivel5: 'Realiza análisis semióticos profundos desglosando significantes, significados e ideologías visuales.',
  },
  {
    id: 'crit-a3',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A3',
    name: 'Geometría, Proporciones y Medidas Técnicas',
    description: 'Aplicación de la Proporción Áurea (Phi), regla de tercios, escalas, conversión de unidades (mm/pt/px).',
    descriptorNivel1: 'Ignora las proporciones matemáticas generando composiciones inestables y desequilibradas.',
    descriptorNivel2: 'Aplica la regla de tercios de forma rígida con problemas en la conversión de medidas reales.',
    descriptorNivel3: 'Utiliza retículas basadas en proporciones matemáticas con asistencia para cálculos complejos.',
    descriptorNivel4: 'Aplica con maestría la divina proporción, secuencias Fibonacci y cálculo métrico exacto.',
    descriptorNivel5: 'Diseña complejas geometrías sagradas y sistemas modulares armónicos con fundamento matemático riguroso.',
  },
  {
    id: 'crit-a4',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A4',
    name: 'Inglés Técnico Aplicado al Diseño Gráfico',
    description: 'Comprensión de terminología gráfica internacional (Bleed, Leading, Kerning, Vector, Tracking, Layers, DPI).',
    descriptorNivel1: 'Desconoce los términos en inglés de los menús y herramientas del software de diseño.',
    descriptorNivel2: 'Comprende comandos básicos de software pero le cuesta interpretar briefs o especificaciones en inglés.',
    descriptorNivel3: 'Maneja adecuadamente el vocabulario técnico estándar en la documentación de proyectos.',
    descriptorNivel4: 'Utiliza con fluidez la terminología técnica internacional en descripciones y reportes de diseño.',
    descriptorNivel5: 'Presenta conceptos y documentación bilingüe (español/inglés) adaptada a clientes internacionales.',
  },
  {
    id: 'crit-a5',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A5',
    name: 'Investigación y Rigor Bibliográfico (Normas APA 7)',
    description: 'Recopilación documental de fuentes científicas/artísticas fidedignas con citación y egrafía correcta.',
    descriptorNivel1: 'No incluye bibliografía o se limita a enlaces URL sueltos sin formato académico.',
    descriptorNivel2: 'Cita fuentes pero comete errores en la estructura de autores, fechas o formato APA.',
    descriptorNivel3: 'Estructura la bibliografía con normas APA 7ma edición con mínimas correcciones.',
    descriptorNivel4: 'Presenta marcos teóricos y egrafías impecables bajo norma APA 7 que sustentan el proyecto.',
    descriptorNivel5: 'Publica y sistematiza investigaciones teóricas de diseño con rigor académico universitario.',
  },
  {
    id: 'crit-a6',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A6',
    name: 'Pensamiento Crítico y Metacognición',
    description: 'Autoevaluación honesta de logros, identificación de dificultades superadas y asimilación formativa del feedback.',
    descriptorNivel1: 'Rechaza la retroalimentación y no identifica sus propias oportunidades de mejora.',
    descriptorNivel2: 'Acepta las observaciones docentes pero le cuesta implementarlas en la siguiente iteración.',
    descriptorNivel3: 'Reflexiona sobre sus errores y ajusta sus procesos de aprendizaje con guía constructiva.',
    descriptorNivel4: 'Realiza autoevaluaciones lúcidas y aplica el feedback docente con madurez profesional.',
    descriptorNivel5: 'Desarrolla una cultura de mejora continua y coevaluación constructiva en todo su entorno formativo.',
  },
];

// ==========================================
// 2. CALENDARIO ACADÉMICO 2026 CSSJ
// ==========================================
export const DEFAULT_CSSJ_CALENDAR_PERIODS: CSSJCalendarPeriod[] = [
  {
    id: 'cal-p1',
    name: 'PRIMER PERIODO (19 enero – 20 marzo)',
    level: 'Media',
    fechaInicio: '2026-01-19',
    fechaCierre: '2026-03-20',
    ingresoTBox: '2026-04-08',
    diagnosticas: { inicio: '2026-01-19', fin: '2026-01-23' },
    actividad1_35: { inicio: '2026-01-19', fin: '2026-02-13', ingresoTBox: '2026-02-20' },
    actividad2_35: { inicio: '2026-02-16', fin: '2026-03-06', ingresoTBox: '2026-03-13' },
    refuerzo: { inicio: '2026-03-09', fin: '2026-03-13' },
    pruebaObjetiva_30: { inicio: '2026-03-16', fin: '2026-03-20', ingresoTBox: '2026-03-27' },
    pruebaExtraordinaria: { inicio: '2026-03-23', fin: '2026-03-27', ingresoTBox: '2026-03-27' },
    actividadesPendientes: { inicio: '2026-03-23', fin: '2026-03-25', ingresoTBox: '2026-04-01' },
    boletasCalificaciones: '2026-04-08',
    temariosCoordinacion: { inicio: '2026-02-23', fin: '2026-03-02' },
  },
  {
    id: 'cal-p2',
    name: 'SEGUNDO PERIODO (24 marzo – 05 junio)',
    level: 'Media',
    fechaInicio: '2026-03-24',
    fechaCierre: '2026-06-05',
    ingresoTBox: '2026-06-19',
    actividad1_35: { inicio: '2026-03-23', fin: '2026-04-24', ingresoTBox: '2026-03-04' },
    actividad2_35: { inicio: '2026-04-27', fin: '2026-05-22', ingresoTBox: '2026-05-29' },
    refuerzo: { inicio: '2026-05-25', fin: '2026-05-29' },
    pruebaObjetiva_30: { inicio: '2026-06-01', fin: '2026-06-05', ingresoTBox: '2026-06-12' },
    pruebaExtraordinaria: { inicio: '2026-06-08', fin: '2026-06-12', ingresoTBox: '2026-06-12' },
    actividadesPendientes: { inicio: '2026-06-08', fin: '2026-06-10', ingresoTBox: '2026-06-15' },
    boletasCalificaciones: '2026-06-19',
    temariosCoordinacion: { inicio: '2026-05-11', fin: '2026-05-18' },
  },
  {
    id: 'cal-p3',
    name: 'TERCER PERIODO (08 junio – 14 agosto)',
    level: 'Media',
    fechaInicio: '2026-06-08',
    fechaCierre: '2026-08-14',
    ingresoTBox: '2026-08-31',
    actividad1_35: { inicio: '2026-06-08', fin: '2026-06-30', ingresoTBox: '2026-07-07' },
    actividad2_35: { inicio: '2026-07-01', fin: '2026-07-23', ingresoTBox: '2026-07-30' },
    refuerzo: { inicio: '2026-07-27', fin: '2026-07-31' },
    pruebaObjetiva_30: { inicio: '2026-08-10', fin: '2026-08-13', ingresoTBox: '2026-08-20' },
    pruebaExtraordinaria: { inicio: '2026-08-18', fin: '2026-08-20', ingresoTBox: '2026-08-20' },
    actividadesPendientes: { inicio: '2026-08-18', fin: '2026-08-20', ingresoTBox: '2026-08-26' },
    boletasCalificaciones: '2026-08-31',
    temariosCoordinacion: { inicio: '2026-07-13', fin: '2026-07-27' },
  },
  {
    id: 'cal-p4',
    name: 'CUARTO PERIODO (17 agosto – 16 octubre)',
    level: 'Media',
    fechaInicio: '2026-08-17',
    fechaCierre: '2026-10-16',
    ingresoTBox: '2026-10-29',
    actividad1_35: { inicio: '2026-08-17', fin: '2026-09-11', ingresoTBox: '2026-09-18' },
    actividad2_35: { inicio: '2026-09-14', fin: '2026-10-02', ingresoTBox: '2026-10-09' },
    refuerzo: { inicio: '2026-10-05', fin: '2026-10-09' },
    pruebaObjetiva_30: { inicio: '2026-10-12', fin: '2026-10-16', ingresoTBox: '2026-10-23' },
    pruebaExtraordinaria: { inicio: '2026-10-19', fin: '2026-10-23', ingresoTBox: '2026-10-23' },
    actividadesPendientes: { inicio: '2026-10-19', fin: '2026-10-21', ingresoTBox: '2026-10-26' },
    boletasCalificaciones: '2026-10-29',
    temariosCoordinacion: { inicio: '2026-09-14', fin: '2026-09-28' },
  },
];

// Fechas Salesianas e Hitos Institucionales CSSJ 2026
export const CSSJ_IMPORTANT_DATES_2026 = [
  { mes: 'Enero', dia: '19', evento: 'Inicio del Año Escolar 2026 y 1ª Asamblea General de Padres (4:30 p.m.)' },
  { mes: 'Enero', dia: '30-31', evento: 'Solemnidad de San Juan Bosco' },
  { mes: 'Febrero', dia: '02', evento: 'Compensatorio Don Bosco' },
  { mes: 'Febrero', dia: '27', evento: 'Celebración Salesiana de la Amorevolezza' },
  { mes: 'Marzo', dia: '19', evento: 'Solemnidad de San José / Sport Fest Salesiano' },
  { mes: 'Marzo', dia: '30 al 05 Abr', evento: 'Semana Santa 2026' },
  { mes: 'Mayo', dia: '06', evento: 'Día de Santo Domingo Savio' },
  { mes: 'Mayo', dia: '22-24', evento: 'Fiesta de María Auxiliadora' },
  { mes: 'Junio', dia: '01', evento: 'Entrega de Ficha de Proyectos (Docentes a Estudiantes)' },
  { mes: 'Junio', dia: '08-15', evento: 'Recepción y Aprobación de Fichas de Proyectos' },
  { mes: 'Junio', dia: '22', evento: 'Día del Maestro' },
  { mes: 'Agosto', dia: '10-14', evento: 'Semana de la Juventud 2026' },
  { mes: 'Agosto', dia: '14-16', evento: 'Natalicio de San Juan Bosco' },
  { mes: 'Noviembre', dia: '03-05', evento: 'Proceso de Recuperación Extraordinaria (P.E.R. Guía 40% + Prueba 60%)' },
  { mes: 'Diciembre', dia: '02', evento: 'Graduación de Educación Media (Bachillerato Técnico y General)' },
];

// ==========================================
// 3. JORNALIZACIÓN ANUAL 2026 (EJEMPLO OFICIAL)
// ==========================================
export const DEFAULT_CSSJ_JORNALIZACIONES: CSSJJornalizacion[] = [
  {
    id: 'jorn-btvdg-101',
    docente: 'Lic. Alexander Gómez / Especialidad de Diseño',
    gradoSeccion: '1° Bachillerato Técnico Vocacional "A"',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    anioLectivo: 2026,
    totalSemanas: 40,
    totalDias: 200,
    horasSemanales: 18,
    horasAnuales: 720,
    trimestre1: { inicio: '2026-01-20', fin: '2026-04-11' },
    trimestre2: { inicio: '2026-04-22', fin: '2026-07-18' },
    trimestre3: { inicio: '2026-07-21', fin: '2026-10-17' },
    unidades: [
      { unitNumber: 1, title: 'Fundamentos de la Diagramación y Grillas Editoriales', totalObjectives: 3, classHours: 18, fechaInicio: '2026-01-20', fechaFin: '2026-02-13' },
      { unitNumber: 2, title: 'Anatomía de la Página y Familias Tipográficas', totalObjectives: 3, classHours: 18, fechaInicio: '2026-02-16', fechaFin: '2026-03-06' },
      { unitNumber: 3, title: 'Arquitectura de Folletos y Plegables Promocionales', totalObjectives: 4, classHours: 24, fechaInicio: '2026-03-09', fechaFin: '2026-04-11' },
      { unitNumber: 4, title: 'Maquetación de Revistas y Catálogos Modulares', totalObjectives: 4, classHours: 24, fechaInicio: '2026-04-22', fechaFin: '2026-05-22' },
      { unitNumber: 5, title: 'Diseño de Portadas y Encuadernación Artesanal', totalObjectives: 3, classHours: 18, fechaInicio: '2026-05-25', fechaFin: '2026-06-19' },
      { unitNumber: 6, title: 'Sustratos, Tintas y Acabados Especiales de Impresión', totalObjectives: 3, classHours: 18, fechaInicio: '2026-06-22', fechaFin: '2026-07-18' },
      { unitNumber: 7, title: 'Preprensa Digital, Sangrados y Separación CMYK', totalObjectives: 3, classHours: 18, fechaInicio: '2026-07-21', fechaFin: '2026-08-21' },
      { unitNumber: 8, title: 'Publicaciones Digitales Interactivas (EPUB / PDF)', totalObjectives: 3, classHours: 18, fechaInicio: '2026-08-24', fechaFin: '2026-09-18' },
      { unitNumber: 9, title: 'Proyecto Integrador Editorial y Dummies de Exposición', totalObjectives: 4, classHours: 24, fechaInicio: '2026-09-21', fechaFin: '2026-10-17' },
    ],
  },
  {
    id: 'jorn-basica-501',
    docente: 'Licda. María Eugenia Santos',
    gradoSeccion: 'Educación Básica – 5° “A”, “B” y “C”',
    asignatura: 'Lenguaje y Literatura',
    anioLectivo: 2026,
    totalSemanas: 40,
    totalDias: 200,
    horasSemanales: 5,
    horasAnuales: 160,
    trimestre1: { inicio: '2026-01-20', fin: '2026-04-11' },
    trimestre2: { inicio: '2026-04-22', fin: '2026-07-18' },
    trimestre3: { inicio: '2026-07-21', fin: '2026-10-17' },
    unidades: [
      { unitNumber: 1, title: 'La Crónica Periodística y el Texto Informativo', totalObjectives: 2, classHours: 16, fechaInicio: '2026-01-20', fechaFin: '2026-02-13' },
      { unitNumber: 2, title: 'El Esquema de Llaves y Organizadores Gráficos', totalObjectives: 2, classHours: 16, fechaInicio: '2026-02-16', fechaFin: '2026-03-06' },
      { unitNumber: 3, title: 'Lengua Náhuat y Emociones Ancestrales', totalObjectives: 2, classHours: 16, fechaInicio: '2026-03-09', fechaFin: '2026-04-11' },
      { unitNumber: 4, title: 'El Cuento Fantástico y la Narrativa Salvadoreña', totalObjectives: 2, classHours: 16, fechaInicio: '2026-04-22', fechaFin: '2026-05-22' },
      { unitNumber: 5, title: 'La Poesía Lírica y Figuras Retóricas', totalObjectives: 2, classHours: 16, fechaInicio: '2026-05-25', fechaFin: '2026-06-19' },
      { unitNumber: 6, title: 'El Teatro y la Expresión Escénica', totalObjectives: 2, classHours: 16, fechaInicio: '2026-06-22', fechaFin: '2026-07-18' },
      { unitNumber: 7, title: 'Mitos y Leyendas de Cuscatlán', totalObjectives: 2, classHours: 16, fechaInicio: '2026-07-21', fechaFin: '2026-08-21' },
      { unitNumber: 8, title: 'El Ensayo Infantil y la Argumentación', totalObjectives: 2, classHours: 16, fechaInicio: '2026-08-24', fechaFin: '2026-09-18' },
      { unitNumber: 9, title: 'Medios de Comunicación y Ética Digital', totalObjectives: 2, classHours: 16, fechaInicio: '2026-09-21', fechaFin: '2026-10-17' },
    ],
  },
];

// ==========================================
// 4. PLANIFICACIÓN DIDÁCTICA 2026 (OFICIAL CSSJ)
// ==========================================
export const DEFAULT_CSSJ_PLANES_DIDACTICOS: CSSJPlanDidactico[] = [
  {
    id: 'plan-btvdg-unit1',
    centroEducativo: 'Colegio Salesiano San José',
    docente: 'Lic. Alexander Gómez',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    grado: '1° Año Técnico',
    seccion: 'A y B',
    unidadNumero: 1,
    unidadNombre: 'Fundamentos de la Diagramación y Grillas Editoriales',
    trimestrePeriodo: 'Trimestre I',
    tiempoHoras: 18,
    fechas: '20 de enero al 13 de febrero de 2026',
    competenciasAsignatura: 'Estructurar publicaciones editoriales aplicando normas de jerarquía visual, retícula suiza y preimpresión con solvencia técnica.',
    competenciasUnidad: 'Diseñar retículas modulares de 6 y 12 columnas en software vectorial y de maquetación, optimizando el espacio gráfico.',
    contenidosConceptuales: [
      'Historia de la retícula editorial y el Estilo Tipográfico Internacional Suizo.',
      'Cálculo de márgenes, callejones, medianil y jerarquías de lectura.',
      'Software de diagramación (Adobe InDesign / Illustrator): páginas maestras y estilos de párrafo.',
    ],
    contenidosProcedimentales: [
      'Construcción de grillas modulares en software especializado respetando la proporción áurea.',
      'Bocetaje manual en retículas impresas con rotulador y escala milimétrica.',
      'Maquetación de un díptico editorial con colocación de texto falso (Lorem Ipsum) y cajas de imagen.',
    ],
    contenidosActitudinales: [
      'Rigor y meticulosidad en la precisión geométrica de márgenes y medianiles.',
      'Respeto a las normas de convivencia y cuidado del equipo informático del taller.',
      'Actitud crítica y constructiva al recibir retroalimentación docente en la mesa de luz.',
    ],
    metodologia: 'Metodología de Proyectos con Enfoque de Acción Completa (Informar, Planificar, Decidir, Ejecutar, Controlar, Valorar).',
    indicadoresLogro: [
      '1.1 Traza con precisión milimétrica la retícula editorial respetando los márgenes de seguridad para encuadernación.',
      '1.2 Aplica estilos de párrafo y jerarquías tipográficas legibles según el estándar editorial MINEDUCYT.',
      '1.3 Demuestra orden y limpieza en la entrega del dummy físico del díptico maquetado.',
    ],
    actividadesEvaluacion: [
      { no: 1, nombre: 'Matriz de Retículas y Guía de Bocetaje Manual', ponderacion: '35%', fechaRealizacion: '30 de enero de 2026' },
      { no: 2, nombre: 'Maquetación Digital del Díptico en InDesign', ponderacion: '35%', fechaRealizacion: '06 de febrero de 2026' },
      { no: 3, nombre: 'Prueba Objetiva Teórica de Tipometría y Márgenes', ponderacion: '30%', fechaRealizacion: '13 de febrero de 2026' },
    ],
    recursos: 'Computadoras con suite Adobe CC, papel bond de 90g, escalímetro, cuchillas olfa y base de corte.',
    tics: 'Plataforma LMS Campus Salesiano, repositorios Google Drive y bibliotecas de fuentes Adobe Fonts.',
    bibliografiaEgrafia: [
      'Müller-Brockmann, J. (2018). Sistemas de retículas: Un manual para diseñadores gráficos. Gustavo Gili.',
      'Bringhurst, R. (2019). Los elementos del estilo tipográfico (4ta ed.). Fondo de Cultura Económica.',
      'MINEDUCYT. (2025). Descriptor del Módulo BTVDG1.7 Diseño Editorial. San Salvador: MINED.',
    ],
  },
];

// ==========================================
// 5. GUIONES DE CLASE 2026 (OFICIAL CSSJ)
// ==========================================
export const DEFAULT_CSSJ_GUIONES: CSSJGuionClase[] = [
  {
    id: 'guion-clase-1',
    docente: 'Lic. Alexander Gómez',
    gradoSeccion: '1° Bachillerato Técnico "A"',
    trimestre: 'Trimestre I',
    fecha: '2026-01-26',
    unidad: 'Unidad 1: Fundamentos de la Diagramación',
    contenido: 'Cálculo de Grillas Modulares y Jerarquías de Párrafo en InDesign',
    tiempoMinutos: 90,
    objetivoClase: 'Calcular e implementar retículas de 12 columnas con páginas maestras para publicaciones de formato carta.',
    indicadorLogro: '1.2 Aplica estilos de párrafo y jerarquías tipográficas legibles según el estándar editorial.',
    competenciasEspecificas: 'Dominio de software editorial, configuración de márgenes y sangrado técnico.',
    ejeTransversal: 'Educación ambiental: optimización de pliegos y reducción de merma de sustratos en pruebas de impresión.',
    inicio: {
      situacion: 'Lluvia de ideas proyectando portadas de revistas icónicas (National Geographic, Vogue, Wired). Preguntas generadoras sobre ¿Por qué nuestros ojos viajan primero al titular?',
      tipoEvaluacion: 'Diagnóstica (sin valor numérico)',
      estrategia: 'Estrategia diagnóstica para identificar aprendizajes previos de composición y tipometría.',
    },
    desarrollo: {
      situacion: 'Demostración paso a paso en proyector de creación de documento en InDesign, configuración de márgenes (Superior: 20mm, Inferior: 25mm, Interior: 15mm, Exterior: 20mm, Sangrado: 3mm). Práctica guiada en laboratorio.',
      tipoEvaluacion: 'Formativa (sin valor numérico)',
      estrategia: 'Evaluación formativa mediante revisión individual en estación de trabajo para verificar si comprendieron el concepto de medianil y páginas enfrentadas.',
    },
    cierre: {
      situacion: 'Consolidación de dudas y exportación del primer pliego en PDF interactivo para revisión en el LMS.',
      tipoEvaluacion: 'Sumativa (con valor % en cuadro de actividades)',
      ponderacionPorcentaje: 10,
      propuestaActividades: 'Mini-entrega de avance de retícula en LMS con rúbrica técnica de 29 ítems.',
      analisisDesempeno: 'El 85% de los estudiantes asimiló con éxito la diferencia entre margen interior para lomo y margen exterior.',
    },
    adaptacionesCurriculares: 'Se proporciona guía impresa con atajos de teclado y contraste de interfaz aumentado para estudiantes con requerimientos visuales.',
    actividadesEvaluacion: [
      { no: 1, actividad: 'Avance de Maqueta con Retícula Suiza', ponderacion: '10%', fecha: '2026-01-26' },
    ],
    tarea: 'Investigar 3 ejemplos de retícula asimétrica y traerlos impresos o digitales en formato moodboard.',
    bibliografiaAPA7: 'Müller-Brockmann, J. (2018). Sistemas de retículas. Gustavo Gili.',
    recursosClase: 'Laboratorio Mac/PC con Adobe InDesign, proyector interactivo, reglas metálicas.',
    tics: 'Campus Virtual LMS Salesiano, atajos en PDF.',
  },
];

// ==========================================
// 6. CUADRO DE ACTIVIDADES (35% + 35% + 30%) CSSJ
// ==========================================
export const DEFAULT_CSSJ_CUADROS_ACTIVIDADES: CSSJCuadroActividades[] = [
  {
    id: 'cuadro-act-1',
    centroEducativo: 'Colegio Salesiano San José',
    nivelEducativo: 'Educación Media – 1° Bachillerato Técnico Vocacional',
    gradoSeccion: '1° "A" y "B"',
    docente: 'Lic. Alexander Gómez',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    trimestrePeriodo: 'Trimestre I',
    actividadTitulo: 'Actividad N° 01 – 35% (Proyecto Editorial Fase I)',
    fechaRango: '19 de enero al 13 de febrero de 2026',
    subactividades: [
      {
        no: 1,
        nombre: 'Matriz de Retículas y Guía de Bocetaje Manual',
        descripcion: 'Realizar 6 bocetos a mano alzada de doble página de revista aplicando retícula de 6 y 12 columnas. Entregar en folder con portada formal.',
        criteriosEvaluacion: 'Se adjunta rúbrica de evaluación oficial MINED (29 ítems). Entregar 2 rúbricas impresas (una para el alumno y otra para el docente).',
        formato: 'Entrega en físico',
        porcentaje: 35,
        fechaEntrega: '30 de enero de 2026',
        rubricaAdjuntaInfo: 'Rúbrica de 29 ítems BTV (Técnico 35%, Emprendedor 25%, Humano 20%, Académico 20%).',
      },
      {
        no: 2,
        nombre: 'Maquetación Digital del Díptico en InDesign',
        descripcion: 'Construir el archivo maestro `.indd` con páginas maestras, estilos de párrafo y colocación de imágenes en alta resolución con sangrado de 3mm.',
        criteriosEvaluacion: 'Cumplimiento de márgenes, empaquetado de fuentes y links, exportación en PDF/X-1a.',
        formato: 'Entrega en plataforma (LMS)',
        porcentaje: 35,
        fechaEntrega: '06 de febrero de 2026',
        rubricaAdjuntaInfo: 'Verificación técnica de artes finales y perfil CMYK.',
      },
      {
        no: 3,
        nombre: 'Dummy Físico y Sustentación de la Propuesta',
        descripcion: 'Armar la maqueta física impresa a doble cara en papel couché de 150g con corte y doblez exacto. Presentación en pareja.',
        criteriosEvaluacion: 'Acabado manual, precisión en el lomo, sustentación oral del concepto.',
        formato: 'Mixto (Físico + Digital)',
        porcentaje: 30,
        fechaEntrega: '13 de febrero de 2026',
        rubricaAdjuntaInfo: 'Rúbrica de Pitch y Dummy.',
      },
    ],
    indicacionesCoordinacion: {
      politicaRetraso: 'LA ENTREGA DE TRABAJOS FUERA DE LAS FECHAS SEÑALADAS SE RECIBIRÁ ÚNICAMENTE CON JUSTIFICACIÓN FORMAL Y LA NOTA DISMINUIRÁ SEGÚN LOS DÍAS DE RETRASO.',
      limiteDias: 'LAS ACTIVIDADES SERÁN RECIBIDAS HASTA DOS DÍAS DESPUÉS DE LA FECHA LÍMITE.',
      periodoExtraordinario: 'POSTERIOR A ESE PLAZO, EL ESTUDIANTE DEBERÁ ENTREGAR EN PERIODO EXTRAORDINARIO CON BASE MÁXIMA DE 5.0.',
      manualConvivencia: 'Si un estudiante incumple las normas del aula o taller, será notificado a sus responsables y se aplicará el Manual de Convivencia Institucional.',
    },
  },
];

// ==========================================
// 7. TEMARIO DE CONTENIDOS A EVALUAR (30%) CSSJ
// ==========================================
export const DEFAULT_CSSJ_TEMARIOS: CSSJTemarioEvaluacion[] = [
  {
    id: 'temario-1',
    docente: 'Lic. Alexander Gómez',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    gradoSeccion: '1° Bachillerato Técnico "A"',
    periodoTrimestre: 'Primer Periodo / Trimestre I',
    porcentaje: '30%',
    periodoComprendido: '19 de enero al 20 de marzo de 2026 (Tomado de la Jornalización)',
    contenidosAEvaluar: [
      { contenido: 'Historia de la retícula y aportes de Josef Müller-Brockmann', paginaEspecificacion: 'Manual Guía págs. 14-22' },
      { contenido: 'Tipometría: cícero, puntos didot, puntos pica y cálculo milimétrico', paginaEspecificacion: 'Guía técnica 1, págs. 5-11' },
      { contenido: 'Anatomía de la tipografía (serif, sans serif, astas, remates, modulación)', paginaEspecificacion: 'Descriptor BTVDG, Unidad 1' },
      { contenido: 'Diferencias entre síntesis aditiva (RGB) y síntesis sustractiva (CMYK)', paginaEspecificacion: 'Módulo de Color, págs. 30-38' },
      { contenido: 'Parámetros técnicos de preprensa: sangrado, margen de seguridad y trapping', paginaEspecificacion: 'Rúbrica de taller, ítem T4' },
      { contenido: 'Normas de exportación PDF/X-1a y resolución óptima (300 DPI vs 72 DPI)', paginaEspecificacion: 'Guía de laboratorio InDesign' },
    ],
    indicadoresLogro: [
      'Identifica con certeza las partes anatómicas de la tipografía y calcula equivalencias en puntos.',
      'Diferencia los modos de color y resoluciones necesarias para impresión offset y pantalla digital.',
      'Calcula márgenes y medianiles para diversas piezas editoriales de alta foliación.',
    ],
    indicacionesGenerales: 'Traer lápiz, borrador, calculadora básica y escalímetro. No se permite el uso de teléfonos celulares durante la prueba objetiva ordinaria.',
  },
];

// ==========================================
// CLASE PRINCIPAL DEL SERVICIO DE DOCUMENTACIÓN CURRICULAR
// ==========================================
const STORAGE_KEY_CALENDAR = 'cssj_lms_calendar_2026';
const STORAGE_KEY_JORNAL = 'cssj_lms_jornalizaciones_2026';
const STORAGE_KEY_PLANES = 'cssj_lms_planes_didacticos_2026';
const STORAGE_KEY_GUIONES = 'cssj_lms_guiones_clase_2026';
const STORAGE_KEY_CUADROS = 'cssj_lms_cuadros_actividades_2026';
const STORAGE_KEY_TEMARIOS = 'cssj_lms_temarios_evaluacion_2026';
const STORAGE_KEY_RUBRIC_SCORES = 'cssj_lms_rubric_evaluations';

export class CurriculumDocsService {
  private calendarPeriods: CSSJCalendarPeriod[] = [];
  private jornalizaciones: CSSJJornalizacion[] = [];
  private planesDidacticos: CSSJPlanDidactico[] = [];
  private guionesClase: CSSJGuionClase[] = [];
  private cuadrosActividades: CSSJCuadroActividades[] = [];
  private temariosEvaluacion: CSSJTemarioEvaluacion[] = [];
  private listeners: (() => void)[] = [];

  constructor() {
    this.loadFromStorage();
  }

  private loadFromStorage() {
    try {
      const savedCal = localStorage.getItem(STORAGE_KEY_CALENDAR);
      this.calendarPeriods = savedCal ? JSON.parse(savedCal) : DEFAULT_CSSJ_CALENDAR_PERIODS;

      const savedJorn = localStorage.getItem(STORAGE_KEY_JORNAL);
      this.jornalizaciones = savedJorn ? JSON.parse(savedJorn) : DEFAULT_CSSJ_JORNALIZACIONES;

      const savedPlanes = localStorage.getItem(STORAGE_KEY_PLANES);
      this.planesDidacticos = savedPlanes ? JSON.parse(savedPlanes) : DEFAULT_CSSJ_PLANES_DIDACTICOS;

      const savedGuiones = localStorage.getItem(STORAGE_KEY_GUIONES);
      this.guionesClase = savedGuiones ? JSON.parse(savedGuiones) : DEFAULT_CSSJ_GUIONES;

      const savedCuadros = localStorage.getItem(STORAGE_KEY_CUADROS);
      this.cuadrosActividades = savedCuadros ? JSON.parse(savedCuadros) : DEFAULT_CSSJ_CUADROS_ACTIVIDADES;

      const savedTemarios = localStorage.getItem(STORAGE_KEY_TEMARIOS);
      this.temariosEvaluacion = savedTemarios ? JSON.parse(savedTemarios) : DEFAULT_CSSJ_TEMARIOS;
    } catch {
      this.calendarPeriods = DEFAULT_CSSJ_CALENDAR_PERIODS;
      this.jornalizaciones = DEFAULT_CSSJ_JORNALIZACIONES;
      this.planesDidacticos = DEFAULT_CSSJ_PLANES_DIDACTICOS;
      this.guionesClase = DEFAULT_CSSJ_GUIONES;
      this.cuadrosActividades = DEFAULT_CSSJ_CUADROS_ACTIVIDADES;
      this.temariosEvaluacion = DEFAULT_CSSJ_TEMARIOS;
    }
  }

  private saveToStorage() {
    try {
      localStorage.setItem(STORAGE_KEY_CALENDAR, JSON.stringify(this.calendarPeriods));
      localStorage.setItem(STORAGE_KEY_JORNAL, JSON.stringify(this.jornalizaciones));
      localStorage.setItem(STORAGE_KEY_PLANES, JSON.stringify(this.planesDidacticos));
      localStorage.setItem(STORAGE_KEY_GUIONES, JSON.stringify(this.guionesClase));
      localStorage.setItem(STORAGE_KEY_CUADROS, JSON.stringify(this.cuadrosActividades));
      localStorage.setItem(STORAGE_KEY_TEMARIOS, JSON.stringify(this.temariosEvaluacion));
    } catch (e) {
      console.warn('Storage save failed:', e);
    }
    this.notify();
  }

  public subscribe(fn: () => void) {
    this.listeners.push(fn);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== fn);
    };
  }

  private notify() {
    this.listeners.forEach((fn) => fn());
  }

  // --- CALENDARIO ACADÉMICO ---
  public getCalendarPeriods(): CSSJCalendarPeriod[] {
    return [...this.calendarPeriods];
  }

  public updateCalendarPeriod(period: CSSJCalendarPeriod) {
    const idx = this.calendarPeriods.findIndex((p) => p.id === period.id);
    if (idx >= 0) {
      this.calendarPeriods[idx] = period;
    } else {
      this.calendarPeriods.push(period);
    }
    this.saveToStorage();
  }

  // --- JORNALIZACIÓN ---
  public getJornalizaciones(): CSSJJornalizacion[] {
    return [...this.jornalizaciones];
  }

  public saveJornalizacion(jorn: CSSJJornalizacion) {
    const idx = this.jornalizaciones.findIndex((j) => j.id === jorn.id);
    if (idx >= 0) {
      this.jornalizaciones[idx] = jorn;
    } else {
      this.jornalizaciones.push(jorn);
    }
    this.saveToStorage();
  }

  // --- PLANIFICACIÓN DIDÁCTICA ---
  public getPlanesDidacticos(): CSSJPlanDidactico[] {
    return [...this.planesDidacticos];
  }

  public savePlanDidactico(plan: CSSJPlanDidactico) {
    const idx = this.planesDidacticos.findIndex((p) => p.id === plan.id);
    if (idx >= 0) {
      this.planesDidacticos[idx] = plan;
    } else {
      this.planesDidacticos.push(plan);
    }
    this.saveToStorage();
  }

  // --- GUIONES DE CLASE ---
  public getGuionesClase(): CSSJGuionClase[] {
    return [...this.guionesClase];
  }

  public saveGuionClase(guion: CSSJGuionClase) {
    const idx = this.guionesClase.findIndex((g) => g.id === guion.id);
    if (idx >= 0) {
      this.guionesClase[idx] = guion;
    } else {
      this.guionesClase.push(guion);
    }
    this.saveToStorage();
  }

  // --- CUADROS DE ACTIVIDADES ---
  public getCuadrosActividades(): CSSJCuadroActividades[] {
    return [...this.cuadrosActividades];
  }

  public saveCuadroActividades(cuadro: CSSJCuadroActividades) {
    const idx = this.cuadrosActividades.findIndex((c) => c.id === cuadro.id);
    if (idx >= 0) {
      this.cuadrosActividades[idx] = cuadro;
    } else {
      this.cuadrosActividades.push(cuadro);
    }
    this.saveToStorage();
  }

  // --- TEMARIOS DE EVALUACIÓN ---
  public getTemariosEvaluacion(): CSSJTemarioEvaluacion[] {
    return [...this.temariosEvaluacion];
  }

  public saveTemarioEvaluacion(temario: CSSJTemarioEvaluacion) {
    const idx = this.temariosEvaluacion.findIndex((t) => t.id === temario.id);
    if (idx >= 0) {
      this.temariosEvaluacion[idx] = temario;
    } else {
      this.temariosEvaluacion.push(temario);
    }
    this.saveToStorage();
  }

  // --- 29 ÍTEMS EVALUATION CALCULATOR ---
  public calculate29RubricGrade(scores: Record<string, MinedLevel>): {
    scoreTecnico: number;
    scoreEmprendedor: number;
    scoreHumano: number;
    scoreAcademico: number;
    weightedGrade: number;
    finalMinedLevel: MinedLevel;
    approved: boolean;
  } {
    const levelToScore = (lvl: MinedLevel) => {
      switch (lvl) {
        case 1: return 4.0;
        case 2: return 5.5;
        case 3: return 6.5;
        case 4: return 8.5;
        case 5: return 10.0;
        default: return 7.0;
      }
    };

    const getAxisAverage = (axis: 'tecnico' | 'emprendedor' | 'humano' | 'academico') => {
      const items = BTV_29_RUBRIC_ITEMS.filter((i) => i.axis === axis);
      let total = 0;
      let count = 0;
      items.forEach((i) => {
        const lvl = scores[i.id] || 4; // default to level 4
        total += levelToScore(lvl);
        count++;
      });
      return count > 0 ? +(total / count).toFixed(1) : 8.5;
    };

    const scoreTecnico = getAxisAverage('tecnico');
    const scoreEmprendedor = getAxisAverage('emprendedor');
    const scoreHumano = getAxisAverage('humano');
    const scoreAcademico = getAxisAverage('academico');

    const weightedGrade = +(
      scoreTecnico * 0.35 +
      scoreEmprendedor * 0.25 +
      scoreHumano * 0.20 +
      scoreAcademico * 0.20
    ).toFixed(1);

    const finalMinedLevel: MinedLevel =
      weightedGrade >= 9.6 ? 5 :
      weightedGrade >= 8.5 ? 4 :
      weightedGrade >= 7.0 ? 3 :
      weightedGrade >= 5.0 ? 2 : 1;

    return {
      scoreTecnico,
      scoreEmprendedor,
      scoreHumano,
      scoreAcademico,
      weightedGrade,
      finalMinedLevel,
      approved: weightedGrade >= 7.0,
    };
  }
}

export const curriculumDocsService = new CurriculumDocsService();
