// GENERATED BY GEMINI — Campus Salesiano San José
// Servicio de Documentación Curricular Institucional (Jornalización, Plan Didáctico, Guiones, Cuadros, Temarios y Rúbrica 29 Ítems)

import {
  CSSJCalendarPeriod,
  CSSJJornalizacion,
  CSSJPlanDidactico,
  CSSJGuionClase,
  CSSJCuadroActividades,
  CSSJTemarioEvaluacion,
  BTVRubricCriterionItem,
  MinedLevel,
} from '../types';

// ==========================================
// 1. RÚBRICA NORMATIVA BTV DISEÑO GRÁFICO (29 ÍTEMS OFICIALES)
// ==========================================
export const BTV_29_RUBRIC_ITEMS: BTVRubricCriterionItem[] = [
  // --- EJE 1: TÉCNICO - TECNOLÓGICO (35% PONDERACIÓN) ---
  {
    id: 'crit-t1',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T1',
    name: 'Identidad Gráfica y Dominio Vectorial',
    description: 'Destreza en el manejo de herramientas vectoriales (Illustrator), nodos Bézier, operaciones booleanas y coherencia formal del imagotipo.',
    descriptorNivel1: 'Presenta trazados vectoriales deformados con exceso de nodos y problemas de proporción sin orientación visual.',
    descriptorNivel2: 'Construye vectores básicos pero con irregularidades en curvas y unión de segmentos.',
    descriptorNivel3: 'Domina el dibujo vectorial con apoyo ocasional para optimizar anclas y proporciones complejas.',
    descriptorNivel4: 'Construye identidades vectoriales limpias, con economía de nodos y precisión geométrica por sí mismo(a).',
    descriptorNivel5: 'Diseña sistemas de identidad vectorial impecables, aplicando retículas avanzadas y capacitando a sus compañeros.',
  },
  {
    id: 'crit-t2',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T2',
    name: 'Tratamiento y Retoque Digital de Imágenes',
    description: 'Edición no destructiva en Photoshop, máscaras de capa, trazados de recorte, corrección tonal y perfiles de color.',
    descriptorNivel1: 'Aplica filtros destructivos sin máscaras, alterando la resolución y generando pixelación.',
    descriptorNivel2: 'Usa capas de ajuste pero los calados y transiciones de recorte son duros y evidentes.',
    descriptorNivel3: 'Realiza fotomontajes coherentes requiriendo asistencia en igualación de iluminación y sombras.',
    descriptorNivel4: 'Ejecuta retoque fotográfico profesional, integración tonal y máscaras impecables por sí mismo(a).',
    descriptorNivel5: 'Domina técnicas avanzadas de photobashing, frequency separation y color grading con calidad de estudio.',
  },
  {
    id: 'crit-t3',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T3',
    name: 'Maquetación y Retícula Editorial',
    description: 'Estructuración de páginas maestras, grillas modulares, estilos de párrafo/carácter y flujo editorial en InDesign.',
    descriptorNivel1: 'Coloca cajas de texto sin retícula ni jerarquía, con desbordes y líneas viudas/huérfanas.',
    descriptorNivel2: 'Emplea márgenes básicos pero omite estilos automatizados y la alineación a rejilla base es irregular.',
    descriptorNivel3: 'Diseña la maquetación aplicando páginas maestras y estilos con eventual revisión de espaciados.',
    descriptorNivel4: 'Estructura publicaciones editoriales fluidas con grillas complejas y estilos jerárquicos autónomamente.',
    descriptorNivel5: 'Crea sistemas editoriales complejos de alta foliación con tablas de contenido y variables automatizadas.',
  },
  {
    id: 'crit-t4',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T4',
    name: 'Preprensa, Separación de Color y Artes Finales',
    description: 'Configuración técnica para imprenta: sangrado (bleed), marcas de registro/corte, perfiles CMYK/Pantone y trapping.',
    descriptorNivel1: 'Envía archivos en RGB, sin sangrado y con imágenes en baja resolución imposibles de imprimir.',
    descriptorNivel2: 'Incluye sangrado pero olvida incrustar fuentes o vincular imágenes en alta resolución.',
    descriptorNivel3: 'Prepara el arte final en PDF/X con adecuada separación de tintas bajo supervisión docente.',
    descriptorNivel4: 'Genera paquetes de arte final y PDF/X-1a certificados para imprenta offset o digital por sí mismo(a).',
    descriptorNivel5: 'Audita y verifica técnicamente los artes de sus compañeros detectando errores de sobreimpresión y cobertura de tinta.',
  },
  {
    id: 'crit-t5',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T5',
    name: 'Teoría del Color y Armonía Cromática',
    description: 'Aplicación psicológica, cultural y técnica del círculo cromático, contrastes tonales y accesibilidad visual.',
    descriptorNivel1: 'Utiliza colores disonantes y sin contraste que anulan la legibilidad del mensaje.',
    descriptorNivel2: 'Aplica combinaciones cromáticas estándar con leves problemas de balance perceptual.',
    descriptorNivel3: 'Aplica esquemas análogos, complementarios o triádicos adecuados al concepto con guía puntual.',
    descriptorNivel4: 'Maneja paletas cromáticas estratégicas con ratios de contraste WCAG óptimos de manera autónoma.',
    descriptorNivel5: 'Justifica semiótica y técnicamente cada elección cromática, creando manuales de marca con equivalencias HEX/RGB/CMYK/Pantone.',
  },
  {
    id: 'crit-t6',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T6',
    name: 'Sintaxis y Jerarquía Tipográfica',
    description: 'Selección tipográfica, kerning, tracking, interlineado, legibilidad y correspondencia conceptual de fuentes.',
    descriptorNivel1: 'Mezcla más de 4 fuentes incompatibles con distorsión de escala horizontal/vertical.',
    descriptorNivel2: 'Selecciona fuentes legibles pero la jerarquía entre titulares, subtítulos y cuerpo es débil.',
    descriptorNivel3: 'Aplica maridajes tipográficos armónicos controlando interlineados con asistencia ocasional.',
    descriptorNivel4: 'Establece jerarquías tipográficas claras con micro y macro-tipografía impecable por sí mismo(a).',
    descriptorNivel5: 'Diseña piezas con excelencia tipográfica, personalizando glifos y manejando principios ortotipográficos avanzados.',
  },
  {
    id: 'crit-t7',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T7',
    name: 'Bocetería y Conceptualización Visual',
    description: 'Exploración creativa mediante bocetos rápidos (thumbnails), mapas mentales, moodboards y síntesis formal.',
    descriptorNivel1: 'Pasa directo al software sin realizar bocetos previos ni exploración de alternativas.',
    descriptorNivel2: 'Presenta bocetos mínimos y literales sin profundidad en la síntesis conceptual.',
    descriptorNivel3: 'Desarrolla variedad de propuestas dibujadas a mano con buena estructura compositiva.',
    descriptorNivel4: 'Documenta un proceso rico de bocetaje, síntesis y evolución morfológica antes de digitalizar.',
    descriptorNivel5: 'Lidera sesiones de visual thinking y moodboarding con alta capacidad de conceptualización abstracta.',
  },
  {
    id: 'crit-t8',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T8',
    name: 'Construcción de Dummies y Prototipos',
    description: 'Elaboración manual de maquetas físicas (empaques, plegables, encuadernación) y prototipos digitales interactivos.',
    descriptorNivel1: 'Dummies desarmados, con cortes imprecisos o pegado deficiente que no cumplen la escala.',
    descriptorNivel2: 'Elabora la maqueta con pequeños desfases en líneas de doblez o armado estructural.',
    descriptorNivel3: 'Construye prototipos funcionales y presentables con asistencia en acabados especiales.',
    descriptorNivel4: 'Produce dummies con cortes exactos, troquelado preciso y acabados de calidad comercial.',
    descriptorNivel5: 'Diseña estructuras volumétricas innovadoras y prototipos interactivos testeados con usuarios reales.',
  },
  {
    id: 'crit-t9',
    axis: 'tecnico',
    axisLabel: 'Eje Técnico-Tecnológico',
    weightPercentage: 35,
    code: 'T9',
    name: 'Optimización de Salidas y Formatos Digitales',
    description: 'Exportación de activos web/app (SVG, WebP, PNG-24), compresión sin pérdida y adaptación responsive.',
    descriptorNivel1: 'Exporta imágenes pesadas y distorsionadas sin considerar el medio de publicación final.',
    descriptorNivel2: 'Exporta en formatos adecuados pero con peso excesivo para plataformas digitales.',
    descriptorNivel3: 'Genera activos optimizados para redes y web con orientación ocasional en resoluciones.',
    descriptorNivel4: 'Configura y optimiza assets digitales para pantallas de alta densidad (Retina/@2x/@3x) autónomamente.',
    descriptorNivel5: 'Estandariza guías de exportación y repositorios de diseño con nombrado semántico y automatización.',
  },

  // --- EJE 2: EMPRENDEDOR Y PRODUCTIVO (25% PONDERACIÓN) ---
  {
    id: 'crit-e1',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E1',
    name: 'Análisis de Mercado y Perfil de Usuario (Target)',
    description: 'Investigación del público meta, mapa de empatía, arquetipo de cliente y benchmarking de la competencia.',
    descriptorNivel1: 'Desconoce las características de la audiencia destinataria de la propuesta gráfica.',
    descriptorNivel2: 'Describe el target con datos demográficos generales sin profundizar en hábitos y necesidades.',
    descriptorNivel3: 'Define el buyer persona y analiza competidores directos con soporte metodológico.',
    descriptorNivel4: 'Construye perfiles de usuario y mapas de empatía fundamentados que guían la propuesta visual.',
    descriptorNivel5: 'Aplica investigación cualitativa y cuantitativa avanzada para identificar nichos de mercado desatendidos.',
  },
  {
    id: 'crit-e2',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E2',
    name: 'Formulación y Cumplimiento del Brief de Diseño',
    description: 'Interpretación de requerimientos del cliente, objetivos SMART, alcance, entregables y limitantes.',
    descriptorNivel1: 'Ignora las especificaciones del brief entregando piezas que no responden a la necesidad.',
    descriptorNivel2: 'Cumple parcialmente los requerimientos omitiendo detalles de formato o lineamientos de marca.',
    descriptorNivel3: 'Interpreta el brief y elabora un contra-brief adecuado con asistencia del docente.',
    descriptorNivel4: 'Desarrolla proyectos respondiendo con exactitud a cada punto del brief técnico y comercial.',
    descriptorNivel5: 'Formula briefs estratégicos para clientes reales anticipando riesgos y proponiendo soluciones integrales.',
  },
  {
    id: 'crit-e3',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E3',
    name: 'Costeo, Presupuestos y Hoja de Producción',
    description: 'Cálculo de horas-diseño, depreciación, insumos, costos de imprenta, mermas e impuestos en El Salvador.',
    descriptorNivel1: 'No presenta presupuesto o fija precios arbitrarios sin base de costos ni rentabilidad.',
    descriptorNivel2: 'Calcula costos de materiales pero omite el valor de sus honorarios profesionales.',
    descriptorNivel3: 'Elabora cotizaciones comerciales considerando mano de obra y materiales con guía docente.',
    descriptorNivel4: 'Formula presupuestos profesionales detallados con desglose de costos fijos, variables y utilidad.',
    descriptorNivel5: 'Maneja hojas de costeo dinámicas y contratos de prestación de servicios de diseño bajo marco legal salvadoreño.',
  },
  {
    id: 'crit-e4',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E4',
    name: 'Matriz FODA y Posicionamiento Estratégico',
    description: 'Evaluación de Fortalezas, Oportunidades, Debilidades y Amenazas de la marca y su entorno comercial.',
    descriptorNivel1: 'No identifica los factores internos y externos que afectan la viabilidad del proyecto.',
    descriptorNivel2: 'Completa la matriz FODA de forma superficial sin conectar con la estrategia visual.',
    descriptorNivel3: 'Elabora la matriz FODA y formula cruces estratégicos (FO, FA, DO, DA) con apoyo docente.',
    descriptorNivel4: 'Diseña estrategias de posicionamiento de marca directamente derivadas de los hallazgos del FODA.',
    descriptorNivel5: 'Propone modelos de negocio Canvas vinculados a estrategias de branding de alto impacto en el mercado local.',
  },
  {
    id: 'crit-e5',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E5',
    name: 'Gestión del Tiempo y Ruta Crítica',
    description: 'Planificación de cronograma (diagrama de Gantt), cumplimiento de hitos y control de entregas por fase.',
    descriptorNivel1: 'Trabaja de manera desorganizada acumulando tareas y entregando fuera del plazo sin justificación.',
    descriptorNivel2: 'Establece fechas pero incurre en retrasos en las fases intermedias de bocetaje y aprobación.',
    descriptorNivel3: 'Sigue el cronograma establecido cumpliendo los hitos principales con recordatorios puntuales.',
    descriptorNivel4: 'Administra su tiempo eficientemente, cumpliendo las 6 etapas de la Acción Completa en los plazos fijados.',
    descriptorNivel5: 'Optimiza los flujos de trabajo del equipo, aplicando metodologías ágiles (Scrum/Kanban) en el taller.',
  },
  {
    id: 'crit-e6',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E6',
    name: 'Propuesta de Valor y Solución Innovadora',
    description: 'Diferenciación de la solución gráfica, aporte creativo y resolución de la problemática real del sector.',
    descriptorNivel1: 'Presenta soluciones genéricas que imitan plantillas existentes sin valor diferenciador.',
    descriptorNivel2: 'Propone ideas funcionales pero convencionales sin impacto disruptivo.',
    descriptorNivel3: 'Aporta elementos creativos novedosos que enriquecen la propuesta visual del cliente.',
    descriptorNivel4: 'Desarrolla soluciones de diseño originales y pertinentes que generan valor tangible a la marca.',
    descriptorNivel5: 'Crea propuestas de diseño con alto grado de innovación social y comercial reconocidas externamente.',
  },
  {
    id: 'crit-e7',
    axis: 'emprendedor',
    axisLabel: 'Eje Emprendedor y Productivo',
    weightPercentage: 25,
    code: 'E7',
    name: 'Sustentación Comercial y Pitch de Venta',
    description: 'Defensa persuasiva, oratoria profesional y argumentación técnica del proyecto ante jurado o cliente.',
    descriptorNivel1: 'Muestra inseguridad, lee diapositivas y no logra justificar las decisiones de diseño adoptadas.',
    descriptorNivel2: 'Explica el proyecto pero le cuesta responder preguntas técnicas sobre costos o producción.',
    descriptorNivel3: 'Presenta con claridad y seguridad apoyándose en material visual estructurado.',
    descriptorNivel4: 'Defiende su propuesta con elocuencia, dominio técnico y seguridad comercial convincente.',
    descriptorNivel5: 'Realiza pitches comerciales de nivel profesional, cautivando a la audiencia y cerrando negociaciones.',
  },

  // --- EJE 3: HUMANO Y SOCIAL (20% PONDERACIÓN) ---
  {
    id: 'crit-h1',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H1',
    name: 'Ética Profesional y Respeto a Derechos de Autor',
    description: 'Uso de licencias Creative Commons/Copyright, citación de recursos tipográficos y rechazo total al plagio.',
    descriptorNivel1: 'Copia diseños o recursos protegidos sin atribución ni autorización de derechos.',
    descriptorNivel2: 'Utiliza recursos de bancos de imágenes sin verificar los términos de licencia comercial.',
    descriptorNivel3: 'Verifica licencias y atribuye fuentes con adecuada orientación del docente.',
    descriptorNivel4: 'Respeta rigurosamente la propiedad intelectual y produce piezas originales con licencias claras.',
    descriptorNivel5: 'Promueve activamente la cultura de la legalidad y el registro de marcas en el marco del CNR salvadoreño.',
  },
  {
    id: 'crit-h2',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H2',
    name: 'Trabajo Cooperativo y Corresponsabilidad',
    description: 'Colaboración activa en equipo, distribución equitativa de cargas y resolución pacífica de discrepancias.',
    descriptorNivel1: 'Muestra resistencia al trabajo en equipo o delega toda la carga en sus compañeros.',
    descriptorNivel2: 'Participa sólo en lo asignado sin mostrar interés por la integración global del proyecto.',
    descriptorNivel3: 'Colabora activamente en el grupo y apoya en la consecución de las metas colectivas.',
    descriptorNivel4: 'Demuestra liderazgo positivo, escucha activa y corresponsabilidad en el éxito del equipo.',
    descriptorNivel5: 'Facilita la cohesión grupal, media en desacuerdos y maximiza las fortalezas individuales del taller.',
  },
  {
    id: 'crit-h3',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H3',
    name: 'Vivencia del Carisma y Valores Salesianos',
    description: 'Amabilidad (Amorevolezza), respeto, solidaridad con los necesitados y espíritu de familia en el aula.',
    descriptorNivel1: 'Muestra actitudes displicentes o irrespetuosas hacia sus pares y docentes.',
    descriptorNivel2: 'Mantiene un comportamiento pasivo sin involucrarse en las dinámicas comunitarias del colegio.',
    descriptorNivel3: 'Practica la convivencia fraterna y el buen trato diario en todas las actividades escolares.',
    descriptorNivel4: 'Encarna el Sistema Preventivo de Don Bosco con alegría, laboriosidad y empatía constante.',
    descriptorNivel5: 'Es referente moral y salesiano para sus compañeros, animando siempre desde el servicio desinteresado.',
  },
  {
    id: 'crit-h4',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H4',
    name: 'Puntualidad y Cumplimiento Normativo CSSJ',
    description: 'Puntualidad en ingresos, cumplimiento del reglamento interno del Colegio Salesiano San José.',
    descriptorNivel1: 'Incurre en impuntualidades recurrentes y requiere recordatorios disciplinarios continuos.',
    descriptorNivel2: 'Llega a tiempo a clases pero presenta entregas al límite o con justificantes frecuentes.',
    descriptorNivel3: 'Cumple puntualmente con sus horarios y reglamentos en el 90% de las ocasiones.',
    descriptorNivel4: 'Es modelo de puntualidad, asistencia y cumplimiento ejemplar del manual de convivencia.',
    descriptorNivel5: 'Impulsa a su grupo al cumplimiento estricto y puntual de todos los compromisos formativos.',
  },
  {
    id: 'crit-h5',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H5',
    name: 'Seguridad Ocupacional y Ergonomía en Taller',
    description: 'Postura frente a la computadora, pausas activas, iluminación adecuada y prevención de lesiones posturales.',
    descriptorNivel1: 'Adopta malas posturas frente al monitor e ignora las normas de seguridad del laboratorio.',
    descriptorNivel2: 'Corrige la postura sólo cuando se le señala, sin interiorizar el hábito ergonómico.',
    descriptorNivel3: 'Mantiene una estación de trabajo ergonómica y realiza pausas activas durante jornadas largas.',
    descriptorNivel4: 'Aplica de forma autónoma principios de salud laboral, ergonomía y cuidado de la visión.',
    descriptorNivel5: 'Diseña y difunde campañas de prevención ergonómica y bienestar físico para el taller de diseño.',
  },
  {
    id: 'crit-h6',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H6',
    name: 'Orden, Limpieza y Cuidado de Equipos',
    description: 'Manipulación responsable de computadoras, tabletas gráficas, guillotinas, adhesivos y espacio común.',
    descriptorNivel1: 'Deja sucio su puesto de trabajo, manipula herramientas cortantes de forma descuidada.',
    descriptorNivel2: 'Limpia su área únicamente ante llamados de atención del encargado de taller.',
    descriptorNivel3: 'Mantiene su estación limpia y cuida los equipos informáticos asignados.',
    descriptorNivel4: 'Es sumamente ordenado(a) con sus herramientas, sustratos y periféricos en todo momento.',
    descriptorNivel5: 'Organiza y lidera jornadas de mantenimiento preventivo y limpieza general del taller de diseño.',
  },
  {
    id: 'crit-h7',
    axis: 'humano',
    axisLabel: 'Eje Humano y Social',
    weightPercentage: 20,
    code: 'H7',
    name: 'Sostenibilidad y Ecodiseño Responsable',
    description: 'Aprovechamiento de sustratos, reducción de mermas de papel, uso de tintas biodegradables y reciclaje.',
    descriptorNivel1: 'Desperdicia pliegos enteros de papel y desecha insumos reutilizables sin criterio.',
    descriptorNivel2: 'Recicla únicamente cuando el docente lo exige en tareas específicas.',
    descriptorNivel3: 'Optimiza el trazado de pliegos para minimizar el desperdicio de sustratos de impresión.',
    descriptorNivel4: 'Integra principios de ecodiseño y economía circular en el empaque y producción de sus piezas.',
    descriptorNivel5: 'Desarrolla proyectos con huella de carbono reducida y sustratos 100% ecológicos o reciclados.',
  },

  // --- EJE 4: ACADÉMICO APLICADO (20% PONDERACIÓN) ---
  {
    id: 'crit-a1',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A1',
    name: 'Ortografía, Redacción y Corrección de Estilo',
    description: 'Escritura impecable en piezas gráficas, acentuación, puntuación y coherencia en titulares y cuerpos de texto.',
    descriptorNivel1: 'Entrega piezas con faltas ortográficas graves en titulares y errores de concordancia.',
    descriptorNivel2: 'Presenta descuidos menores de puntuación o tildes que afectan la profesionalidad del texto.',
    descriptorNivel3: 'Redacta textos claros y correctamente puntuados con mínima corrección docente.',
    descriptorNivel4: 'Escribe copys y textos editoriales impecables gramaticalmente y con alto poder comunicativo.',
    descriptorNivel5: 'Ejerce funciones de corrección de estilo editorial para todas las publicaciones del grupo.',
  },
  {
    id: 'crit-a2',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A2',
    name: 'Semiótica, Retórica y Significación Visual',
    description: 'Uso consciente de metáforas, metonimias, signos, símbolos, denotación y connotación en el mensaje.',
    descriptorNivel1: 'Coloca elementos visuales sin justificación simbólica ni correspondencia con el mensaje.',
    descriptorNivel2: 'Utiliza símbolos muy obvios o clichés gráficos con escasa profundidad semiótica.',
    descriptorNivel3: 'Aplica figuras retóricas visuales coherentes con el concepto comunicacional.',
    descriptorNivel4: 'Construye metáforas visuales ricas y sofisticadas con alta pregnancia en el receptor.',
    descriptorNivel5: 'Realiza análisis semióticos profundos desglosando significantes, significados e ideologías visuales.',
  },
  {
    id: 'crit-a3',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A3',
    name: 'Geometría, Proporciones y Medidas Técnicas',
    description: 'Aplicación de la Proporción Áurea (Phi), regla de tercios, escalas, conversión de unidades (mm/pt/px).',
    descriptorNivel1: 'Ignora las proporciones matemáticas generando composiciones inestables y desequilibradas.',
    descriptorNivel2: 'Aplica la regla de tercios de forma rígida con problemas en la conversión de medidas reales.',
    descriptorNivel3: 'Utiliza retículas basadas en proporciones matemáticas con asistencia para cálculos complejos.',
    descriptorNivel4: 'Aplica con maestría la divina proporción, secuencias Fibonacci y cálculo métrico exacto.',
    descriptorNivel5: 'Diseña complejas geometrías sagradas y sistemas modulares armónicos con fundamento matemático riguroso.',
  },
  {
    id: 'crit-a4',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A4',
    name: 'Inglés Técnico Aplicado al Diseño Gráfico',
    description: 'Comprensión de terminología gráfica internacional (Bleed, Leading, Kerning, Vector, Tracking, Layers, DPI).',
    descriptorNivel1: 'Desconoce los términos en inglés de los menús y herramientas del software de diseño.',
    descriptorNivel2: 'Comprende comandos básicos de software pero le cuesta interpretar briefs o especificaciones en inglés.',
    descriptorNivel3: 'Maneja adecuadamente el vocabulario técnico estándar en la documentación de proyectos.',
    descriptorNivel4: 'Utiliza con fluidez la terminología técnica internacional en descripciones y reportes de diseño.',
    descriptorNivel5: 'Presenta conceptos y documentación bilingüe (español/inglés) adaptada a clientes internacionales.',
  },
  {
    id: 'crit-a5',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A5',
    name: 'Investigación y Rigor Bibliográfico (Normas APA 7)',
    description: 'Recopilación documental de fuentes científicas/artísticas fidedignas con citación y egrafía correcta.',
    descriptorNivel1: 'No incluye bibliografía o se limita a enlaces URL sueltos sin formato académico.',
    descriptorNivel2: 'Cita fuentes pero comete errores en la estructura de autores, fechas o formato APA.',
    descriptorNivel3: 'Estructura la bibliografía con normas APA 7ma edición con mínimas correcciones.',
    descriptorNivel4: 'Presenta marcos teóricos y egrafías impecables bajo norma APA 7 que sustentan el proyecto.',
    descriptorNivel5: 'Publica y sistematiza investigaciones teóricas de diseño con rigor académico universitario.',
  },
  {
    id: 'crit-a6',
    axis: 'academico',
    axisLabel: 'Eje Académico Aplicado',
    weightPercentage: 20,
    code: 'A6',
    name: 'Pensamiento Crítico y Metacognición',
    description: 'Autoevaluación honesta de logros, identificación de dificultades superadas y asimilación formativa del feedback.',
    descriptorNivel1: 'Rechaza la retroalimentación y no identifica sus propias oportunidades de mejora.',
    descriptorNivel2: 'Acepta las observaciones docentes pero le cuesta implementarlas en la siguiente iteración.',
    descriptorNivel3: 'Reflexiona sobre sus errores y ajusta sus procesos de aprendizaje con guía constructiva.',
    descriptorNivel4: 'Realiza autoevaluaciones lúcidas y aplica el feedback docente con madurez profesional.',
    descriptorNivel5: 'Desarrolla una cultura de mejora continua y coevaluación constructiva en todo su entorno formativo.',
  },
];

// ==========================================
// 2. CALENDARIO ACADÉMICO 2026 CSSJ
// ==========================================
export const DEFAULT_CSSJ_CALENDAR_PERIODS: CSSJCalendarPeriod[] = [
  {
    id: 'cal-p1',
    name: 'PRIMER PERIODO (19 enero – 20 marzo)',
    level: 'Media',
    fechaInicio: '2026-01-19',
    fechaCierre: '2026-03-20',
    ingresoTBox: '2026-04-08',
    diagnosticas: { inicio: '2026-01-19', fin: '2026-01-23' },
    actividad1_35: { inicio: '2026-01-19', fin: '2026-02-13', ingresoTBox: '2026-02-20' },
    actividad2_35: { inicio: '2026-02-16', fin: '2026-03-06', ingresoTBox: '2026-03-13' },
    refuerzo: { inicio: '2026-03-09', fin: '2026-03-13' },
    pruebaObjetiva_30: { inicio: '2026-03-16', fin: '2026-03-20', ingresoTBox: '2026-03-27' },
    pruebaExtraordinaria: { inicio: '2026-03-23', fin: '2026-03-27', ingresoTBox: '2026-03-27' },
    actividadesPendientes: { inicio: '2026-03-23', fin: '2026-03-25', ingresoTBox: '2026-04-01' },
    boletasCalificaciones: '2026-04-08',
    temariosCoordinacion: { inicio: '2026-02-23', fin: '2026-03-02' },
  },
  {
    id: 'cal-p2',
    name: 'SEGUNDO PERIODO (24 marzo – 05 junio)',
    level: 'Media',
    fechaInicio: '2026-03-24',
    fechaCierre: '2026-06-05',
    ingresoTBox: '2026-06-19',
    actividad1_35: { inicio: '2026-03-23', fin: '2026-04-24', ingresoTBox: '2026-03-04' },
    actividad2_35: { inicio: '2026-04-27', fin: '2026-05-22', ingresoTBox: '2026-05-29' },
    refuerzo: { inicio: '2026-05-25', fin: '2026-05-29' },
    pruebaObjetiva_30: { inicio: '2026-06-01', fin: '2026-06-05', ingresoTBox: '2026-06-12' },
    pruebaExtraordinaria: { inicio: '2026-06-08', fin: '2026-06-12', ingresoTBox: '2026-06-12' },
    actividadesPendientes: { inicio: '2026-06-08', fin: '2026-06-10', ingresoTBox: '2026-06-15' },
    boletasCalificaciones: '2026-06-19',
    temariosCoordinacion: { inicio: '2026-05-11', fin: '2026-05-18' },
  },
  {
    id: 'cal-p3',
    name: 'TERCER PERIODO (08 junio – 14 agosto)',
    level: 'Media',
    fechaInicio: '2026-06-08',
    fechaCierre: '2026-08-14',
    ingresoTBox: '2026-08-31',
    actividad1_35: { inicio: '2026-06-08', fin: '2026-06-30', ingresoTBox: '2026-07-07' },
    actividad2_35: { inicio: '2026-07-01', fin: '2026-07-23', ingresoTBox: '2026-07-30' },
    refuerzo: { inicio: '2026-07-27', fin: '2026-07-31' },
    pruebaObjetiva_30: { inicio: '2026-08-10', fin: '2026-08-13', ingresoTBox: '2026-08-20' },
    pruebaExtraordinaria: { inicio: '2026-08-18', fin: '2026-08-20', ingresoTBox: '2026-08-20' },
    actividadesPendientes: { inicio: '2026-08-18', fin: '2026-08-20', ingresoTBox: '2026-08-26' },
    boletasCalificaciones: '2026-08-31',
    temariosCoordinacion: { inicio: '2026-07-13', fin: '2026-07-27' },
  },
  {
    id: 'cal-p4',
    name: 'CUARTO PERIODO (17 agosto – 16 octubre)',
    level: 'Media',
    fechaInicio: '2026-08-17',
    fechaCierre: '2026-10-16',
    ingresoTBox: '2026-10-29',
    actividad1_35: { inicio: '2026-08-17', fin: '2026-09-11', ingresoTBox: '2026-09-18' },
    actividad2_35: { inicio: '2026-09-14', fin: '2026-10-02', ingresoTBox: '2026-10-09' },
    refuerzo: { inicio: '2026-10-05', fin: '2026-10-09' },
    pruebaObjetiva_30: { inicio: '2026-10-12', fin: '2026-10-16', ingresoTBox: '2026-10-23' },
    pruebaExtraordinaria: { inicio: '2026-10-19', fin: '2026-10-23', ingresoTBox: '2026-10-23' },
    actividadesPendientes: { inicio: '2026-10-19', fin: '2026-10-21', ingresoTBox: '2026-10-26' },
    boletasCalificaciones: '2026-10-29',
    temariosCoordinacion: { inicio: '2026-09-14', fin: '2026-09-28' },
  },
];

// Fechas Salesianas e Hitos Institucionales CSSJ 2026
export const CSSJ_IMPORTANT_DATES_2026 = [
  { mes: 'Enero', dia: '19', evento: 'Inicio del Año Escolar 2026 y 1ª Asamblea General de Padres (4:30 p.m.)' },
  { mes: 'Enero', dia: '30-31', evento: 'Solemnidad de San Juan Bosco' },
  { mes: 'Febrero', dia: '02', evento: 'Compensatorio Don Bosco' },
  { mes: 'Febrero', dia: '27', evento: 'Celebración Salesiana de la Amorevolezza' },
  { mes: 'Marzo', dia: '19', evento: 'Solemnidad de San José / Sport Fest Salesiano' },
  { mes: 'Marzo', dia: '30 al 05 Abr', evento: 'Semana Santa 2026' },
  { mes: 'Mayo', dia: '06', evento: 'Día de Santo Domingo Savio' },
  { mes: 'Mayo', dia: '22-24', evento: 'Fiesta de María Auxiliadora' },
  { mes: 'Junio', dia: '01', evento: 'Entrega de Ficha de Proyectos (Docentes a Estudiantes)' },
  { mes: 'Junio', dia: '08-15', evento: 'Recepción y Aprobación de Fichas de Proyectos' },
  { mes: 'Junio', dia: '22', evento: 'Día del Maestro' },
  { mes: 'Agosto', dia: '10-14', evento: 'Semana de la Juventud 2026' },
  { mes: 'Agosto', dia: '14-16', evento: 'Natalicio de San Juan Bosco' },
  { mes: 'Noviembre', dia: '03-05', evento: 'Proceso de Recuperación Extraordinaria (P.E.R. Guía 40% + Prueba 60%)' },
  { mes: 'Diciembre', dia: '02', evento: 'Graduación de Educación Media (Bachillerato Técnico y General)' },
];

// ==========================================
// 2.1 CATÁLOGO DE ASIGNATURAS ACADÉMICAS OFICIALES CSSJ POR GRADO
// ==========================================
export interface AcademicSubjectTemplate {
  id: string;
  name: string;
  level: 'Parvularia' | 'Básica I Ciclo' | 'Básica II Ciclo' | 'Básica III Ciclo' | 'Bachillerato General' | 'Bachillerato Técnico';
  grade: string;
  weeklyHours: number;
  annualHours: number;
  description: string;
  competenciaGeneral: string;
  defaultObjective: string;
  saberConocer: string[];
  saberHacer: string[];
  saberSer: string[];
  indicadoresLogro: string[];
  bibliografia: string[];
}

export const CSSJ_ACADEMIC_SUBJECTS_CATALOG: AcademicSubjectTemplate[] = [
  // --- EDUCACIÓN BÁSICA ---
  {
    id: 'subj-lenguaje-7',
    name: 'Lenguaje y Literatura',
    level: 'Básica III Ciclo',
    grade: '7° Grado (Secciones A, B y C)',
    weeklyHours: 5,
    annualHours: 200,
    description: 'Desarrollo de la comprensión lectora, producción de textos narrativos, poéticos y argumentativos, y dominio de la gramática normativa.',
    competenciaGeneral: 'Comunicarse eficazmente de forma oral y escrita mediante el análisis crítico y la producción de textos con intención estética y funcional.',
    defaultObjective: 'Analizar la estructura del cuento fantástico y aplicar figuras literarias en la producción de textos creativos propios.',
    saberConocer: [
      'Estructura del cuento fantástico y la novela de aventuras.',
      'Figuras literarias: metáfora, símil, hipérbole y personificación.',
      'Sintaxis oracional: sujeto, predicado y complementos verbales.',
    ],
    saberHacer: [
      'Redacción de relatos cortos aplicando coherencia, cohesión y signos de puntuación.',
      'Análisis sintáctico y morfológico de oraciones compuestas.',
      'Lectura dramatizada y declamación de poesía lírica cuscatleca.',
    ],
    saberSer: [
      'Apreciación del patrimonio literario y cultural salvadoreño.',
      'Hábito y disfrute de la lectura cotidiana.',
      'Respeto por la diversidad de opiniones en debates grupales.',
    ],
    indicadoresLogro: [
      'Identifica con claridad los elementos estructurales y personajes en cuentos fantásticos.',
      'Aplica correctamente las normas ortográficas y de puntuación en sus escritos.',
      'Expresa sus ideas con fluidez, respeto y elocuencia en exposiciones orales.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Programa de Estudio: Lenguaje y Literatura 7° Grado. San Salvador: MINED.',
      'Real Academia Española. (2020). Ortografía de la lengua española. Espasa.',
    ],
  },
  {
    id: 'subj-mate-7',
    name: 'Matemática (ESMATE)',
    level: 'Básica III Ciclo',
    grade: '7° Grado (Secciones A, B y C)',
    weeklyHours: 5,
    annualHours: 200,
    description: 'Números positivos y negativos, expresiones algebraicas, ecuaciones de primer grado y proporcionalidad bajo metodología ESMATE.',
    competenciaGeneral: 'Resolver situaciones problemáticas del entorno mediante el razonamiento lógico, el lenguaje algebraico y el pensamiento crítico.',
    defaultObjective: 'Resolver ecuaciones de primer grado con una incógnita y aplicarlas en la solución de problemas cotidianos de cálculo y presupuesto.',
    saberConocer: [
      'Números enteros, recta numérica y valor absoluto.',
      'Propiedades de las operaciones combinadas y jerarquía de operaciones.',
      'Ecuaciones lineales de la forma ax + b = c y proporcionalidad directa e inversa.',
    ],
    saberHacer: [
      'Planteamiento y resolución de ecuaciones lineales paso a paso.',
      'Construcción y lectura de gráficas de proporcionalidad en el plano cartesiano.',
      'Cálculo de porcentajes, interés simple y descuentos comerciales.',
    ],
    saberSer: [
      'Perseverancia y rigor lógico en la búsqueda de soluciones a problemas complejos.',
      'Honestidad y transparencia en el desarrollo de ejercicios evaluados.',
      'Colaboración fraterna en el trabajo cooperativo en equipo salesiano.',
    ],
    indicadoresLogro: [
      'Resuelve con precisión operaciones con números enteros y racionales.',
      'Despeja incógnitas en ecuaciones lineales justificando cada propiedad algebraica utilizada.',
      'Modela situaciones de la vida real mediante expresiones algebraicas sencillas.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Libro de Texto ESMATE 7° Grado. San Salvador: MINED.',
      'Stewart, J. (2020). Precálculo: Matemáticas para el cálculo. Cengage Learning.',
    ],
  },
  {
    id: 'subj-ciencias-8',
    name: 'Ciencias Naturales',
    level: 'Básica III Ciclo',
    grade: '8° Grado (Secciones A, B y C)',
    weeklyHours: 5,
    annualHours: 200,
    description: 'Física elemental, química inorgánica básica, sistemas biológicos y conservación de ecosistemas con prácticas de laboratorio.',
    competenciaGeneral: 'Explicar fenómenos del mundo natural a partir del método científico, promoviendo el cuidado de la casa común y la salud integral.',
    defaultObjective: 'Comprender las leyes del movimiento de Newton y la transformación de la energía a través de experimentos guiados en laboratorio.',
    saberConocer: [
      'Cinemática: velocidad, aceleración y leyes del movimiento de Newton.',
      'Estructura atómica, tabla periódica y enlaces químicos.',
      'Ecología, biodiversidad de El Salvador y sostenibilidad ambiental.',
    ],
    saberHacer: [
      'Manejo seguro de instrumental en el laboratorio de ciencias.',
      'Registro y análisis de datos experimentales en tablas y gráficas.',
      'Elaboración de informes de laboratorio con hipótesis y conclusiones.',
    ],
    saberSer: [
      'Conciencia ecológica y compromiso con el reciclaje y ahorro energético.',
      'Cuidado estricto de las normas de bioseguridad en el laboratorio.',
      'Curiosidad científica y asombro ante la naturaleza.',
    ],
    indicadoresLogro: [
      'Aplica las leyes de Newton para calcular fuerza, masa y aceleración en problemas prácticos.',
      'Diferencia elementos, compuestos y mezclas a partir de sus propiedades físico-químicas.',
      'Elabora proyectos científicos escolares con rigor metodológico.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Guías de Ciencia y Tecnología 8° Grado. San Salvador: MINED.',
      'Hewitt, P. (2018). Física Conceptual. Pearson Educación.',
    ],
  },
  {
    id: 'subj-sociales-9',
    name: 'Estudios Sociales y Cívica',
    level: 'Básica III Ciclo',
    grade: '9° Grado (Secciones A, B y C)',
    weeklyHours: 4,
    annualHours: 160,
    description: 'Historia contemporánea de El Salvador y Centroamérica, geografía física y humana, democracia, derechos humanos y educación cívica.',
    competenciaGeneral: 'Analizar críticamente la realidad histórica y social salvadoreña para actuar como ciudadanos comprometidos con la justicia y la paz.',
    defaultObjective: 'Investigar las causas y consecuencias de los Acuerdos de Paz de 1992 y su impacto en la institucionalidad democrática salvadoreña.',
    saberConocer: [
      'Geografía física y geopolítica de Centroamérica y el Caribe.',
      'Historia salvadoreña del siglo XX: crisis sociopolítica y Acuerdos de Paz.',
      'Estructura del Estado, Constitución de la República y Derechos Humanos.',
    ],
    saberHacer: [
      'Análisis de fuentes históricas primarias y secundarias con espíritu crítico.',
      'Elaboración de mapas temáticos, líneas de tiempo y ensayos reflexivos.',
      'Debates estructurados sobre problemáticas sociales juveniles actuales.',
    ],
    saberSer: [
      'Compromiso con la cultura de paz, diálogo y no violencia activa.',
      'Identidad nacional y valoración del patrimonio histórico cuscatleco.',
      'Solidaridad con los sectores más vulnerables de la comunidad.',
    ],
    indicadoresLogro: [
      'Explica con argumentos sólidos los procesos históricos que configuraron el El Salvador contemporáneo.',
      'Reconoce sus derechos y deberes ciudadanos contemplados en la Constitución.',
      'Propone acciones comunitarias para el fomento de la convivencia armónica.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Estudios Sociales y Cívica 9° Grado. San Salvador: MINED.',
      'Ministerio de Educación. (2022). Historia de El Salvador Tomos I y II.',
    ],
  },
  {
    id: 'subj-ingles-8',
    name: 'Inglés General',
    level: 'Básica III Ciclo',
    grade: '8° Grado (Secciones A, B y C)',
    weeklyHours: 3,
    annualHours: 120,
    description: 'Desarrollo de las 4 macrohabilidades lingüísticas (Listening, Speaking, Reading, Writing) alineadas al marco MCER A2.',
    competenciaGeneral: 'Interactuar en situaciones comunicativas cotidianas en idioma inglés con fluidez y precisión gramatical en nivel básico-intermedio.',
    defaultObjective: 'Narrar eventos pasados y planes a futuro utilizando Past Simple y Going to en conversaciones y redacción de correos informales.',
    saberConocer: [
      'Grammar structures: Past Simple (regular/irregular verbs), Present Continuous for future, Comparatives/Superlatives.',
      'Daily vocabulary: travel, technology, hobbies, feelings, and school routines.',
      'Phonetics: correct pronunciation of regular verb endings (-ed) and connected speech.',
    ],
    saberHacer: [
      'Short interactive dialogues and role-plays about everyday life situations.',
      'Reading comprehension of short articles, emails, and narratives.',
      'Writing structured paragraphs with topic sentence and supporting ideas.',
    ],
    saberSer: [
      'Confidence and willingness to speak in English without fear of making mistakes.',
      'Respect for cultural differences and global diversity.',
      'Active listening and collaborative teamwork in paired speaking tasks.',
    ],
    indicadoresLogro: [
      'Understands main ideas from audio tracks spoken at moderate speed.',
      'Speaks with intelligible pronunciation in 2-minute presentations.',
      'Writes coherent 80-word paragraphs using appropriate linking words.',
    ],
    bibliografia: [
      'Cambridge University Press. (2023). Prepare! Level 2 Student Book.',
      'MINEDUCYT. (2024). English Curriculum Guidelines for Basic Education.',
    ],
  },
  {
    id: 'subj-religion-all',
    name: 'Educación en la Fe / Formación Pastoral Salesiana',
    level: 'Básica III Ciclo',
    grade: '7°, 8° y 9° Grado / Educación Media',
    weeklyHours: 2,
    annualHours: 80,
    description: 'Vivencia del Evangelio, pedagogía del Sistema Preventivo de Don Bosco (Razón, Religión y Amor), carisma salesiano y compromiso solidario.',
    competenciaGeneral: 'Interiorizar los valores cristiano-salesianos para construir un proyecto de vida centrado en el servicio generoso al prójimo.',
    defaultObjective: 'Conocer y poner en práctica el Aguinaldo Salesiano 2026 y el carisma de Don Bosco en las relaciones cotidianas de aula y familia.',
    saberConocer: [
      'La persona de Jesucristo en los Evangelios y la Doctrina Social de la Iglesia.',
      'Vida de San Juan Bosco, Santa María Mazzarello y Santo Domingo Savio.',
      'Pilares del Sistema Preventivo: Razón, Religión y Amor (Amorevolezza).',
    ],
    saberHacer: [
      'Organización de momentos de oración de los Buenos Días y campañas solidarias.',
      'Reflexión guiada sobre dilemas éticos y proyecto de vida personal.',
      'Participación activa en el Movimiento Juvenil Salesiano (MJS).',
    ],
    saberSer: [
      'Alegría salesiana, espíritu de familia y amabilidad en el trato mutuo.',
      'Sensibilidad social y compromiso concreto con los más necesitados.',
      'Fidelidad y amor a María Auxiliadora y a la Iglesia.',
    ],
    indicadoresLogro: [
      'Explica el mensaje central del Evangelio y lo vincula con su vida diaria.',
      'Demuestra en su comportamiento los valores de la convivencia salesiana.',
      'Participa con devoción y respeto en las celebraciones litúrgicas colegiales.',
    ],
    bibliografia: [
      'Congregación Salesiana. (2026). Aguinaldo del Rector Mayor: El sueño que hace soñar.',
      'Braido, P. (2018). Prevenir, no reprimir: El sistema educativo de Don Bosco.',
    ],
  },
  {
    id: 'subj-edufisica-all',
    name: 'Educación Física y Deportes',
    level: 'Básica III Ciclo',
    grade: 'Educación Básica y Media (Todas las secciones)',
    weeklyHours: 2,
    annualHours: 80,
    description: 'Acondicionamiento físico, fundamentos técnicos de fútbol, baloncesto, voleibol, atletismo y promoción de hábitos de vida saludable.',
    competenciaGeneral: 'Desarrollar capacidades motrices, condicionales y coordinativas mediante la práctica deportiva y el juego limpio salesiano.',
    defaultObjective: 'Ejecutar circuitos de resistencia aeróbica y fundamentos de pases y lanzamientos en deportes de conjunto respetando las reglas.',
    saberConocer: [
      'Fisiología básica del ejercicio: frecuencia cardíaca, hidratación y nutrición deportiva.',
      'Reglamento oficial de Baloncesto, Voleibol, Fútbol Sala y Atletismo.',
      'Prevención de lesiones deportivas y primeros auxilios básicos.',
    ],
    saberHacer: [
      'Ejecución correcta de ejercicios de calentamiento, estiramiento y vuelta a la calma.',
      'Dominio técnico del balón (drible, pase, recepción, tiro al marco/canasta).',
      'Aplicación de tácticas y sistemas defensivos/ofensivos en partidos de clase.',
    ],
    saberSer: [
      'Juego limpio (Fair Play), compañerismo y respeto irrestricto al árbitro.',
      'Superación personal y esfuerzo constante ante la exigencia física.',
      'Cuidado y conservación del material deportivo y las canchas colegiales.',
    ],
    indicadoresLogro: [
      'Mejora sus marcas individuales en pruebas de resistencia y velocidad.',
      'Aplica las reglas oficiales en partidos recreativos y competitivos escolares.',
      'Adopta hábitos de higiene y alimentación saludable post-entrenamiento.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Programa de Educación Física Escolar.',
      'López Chicharro, J. (2020). Fisiología del Ejercicio Físico. Panamericana.',
    ],
  },
  {
    id: 'subj-informatica-all',
    name: 'Informática y Ciudadanía Digital (TBox)',
    level: 'Básica III Ciclo',
    grade: '7°, 8° y 9° Grado',
    weeklyHours: 2,
    annualHours: 80,
    description: 'Herramientas ofimáticas en la nube, programación por bloques, robótica educativa, seguridad digital y plataforma TBox Planet.',
    competenciaGeneral: 'Utilizar tecnologías digitales de información y comunicación de forma ética, productiva y segura para la solución de problemas.',
    defaultObjective: 'Diseñar algoritmos con estructuras condicionales y bucles en plataformas de programación visual y modelar hojas de cálculo avanzadas.',
    saberConocer: [
      'Lógica algorítmica: variables, condicionales, ciclos y funciones.',
      'Hojas de cálculo: fórmulas lógicas, estadísticas y gráficos dinámicos.',
      'Ciberseguridad: protección de datos personales y huella digital ética.',
    ],
    saberHacer: [
      'Programación de animaciones e historias interactivas en Scratch / Python básico.',
      'Diseño de bases de datos y tablas de cálculo para administración de datos.',
      'Producción de presentaciones interactivas con Canva y herramientas cloud.',
    ],
    saberSer: [
      'Responsabilidad ética en el uso de redes sociales e inteligencia artificial.',
      'Cuidado y uso responsable del laboratorio de cómputo del colegio.',
      'Pensamiento computacional crítico y resolución colaborativa de retos.',
    ],
    indicadoresLogro: [
      'Construye programas funcionales que resuelven retos matemáticos y lógicos.',
      'Utiliza fórmulas de hoja de cálculo con precisión para el análisis de datos.',
      'Aplica medidas de seguridad y privacidad en entornos virtuales.',
    ],
    bibliografia: [
      'TBox El Salvador. (2026). Currículo de Tecnología Educativa TBox Planet.',
      'Resnick, M. (2019). Cultivando la creatividad a través de proyectos de programación.',
    ],
  },

  // --- EDUCACIÓN MEDIA: BACHILLERATO GENERAL Y TÉCNICO (TRONCO COMÚN) ---
  {
    id: 'subj-mate-media-1',
    name: 'Matemática (Bachillerato)',
    level: 'Bachillerato General',
    grade: '1° y 2° Año de Bachillerato (General y Técnico)',
    weeklyHours: 5,
    annualHours: 200,
    description: 'Trigonometría, geometría analítica, funciones polinomiales, cónicas, cálculo diferencial básico y estadística descriptiva.',
    competenciaGeneral: 'Modelar y resolver problemas complejos de ciencias e ingeniería mediante funciones matemáticas, trigonometría y cálculo.',
    defaultObjective: 'Graficar y analizar funciones trigonométricas y aplicar las identidades fundamentales en la resolución de triángulos oblicuángulos.',
    saberConocer: [
      'Funciones trigonométricas (seno, coseno, tangente) y círculo unitario.',
      'Leyes de senos y cosenos para triángulos oblicuángulos.',
      'Geometría analítica de la recta, parábola, elipse y circunferencia.',
    ],
    saberHacer: [
      'Demostración rigurosa de identidades trigonométricas fundamentales.',
      'Cálculo de distancias, pendientes y ecuaciones de lugares geométricos.',
      'Uso de software matemático (GeoGebra) para la visualización gráfica.',
    ],
    saberSer: [
      'Rigor analítico y perseverancia en la resolución de problemas de cálculo.',
      'Disposición al trabajo colaborativo y respeto al razonamiento ajeno.',
      'Aplicación ética de las matemáticas en el análisis de datos sociales.',
    ],
    indicadoresLogro: [
      'Resuelve problemas de topografía y navegación aplicando leyes de senos y cosenos.',
      'Determina la ecuación canónica y general de las secciones cónicas.',
      'Interpreta modelos matemáticos en contextos físicos y económicos.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Libro de Texto ESMATE 1° y 2° Año de Bachillerato. San Salvador: MINED.',
      'Larson, R. (2021). Precálculo con límites. Cengage Learning.',
    ],
  },
  {
    id: 'subj-ciencias-media-1',
    name: 'Ciencias Naturales (Física y Química)',
    level: 'Bachillerato General',
    grade: '1° y 2° Año de Bachillerato (General y Técnico)',
    weeklyHours: 5,
    annualHours: 200,
    description: 'Mecánica clásica, termodinámica, electromagnetismo, estequiometría química y química orgánica con rigor experimental.',
    competenciaGeneral: 'Investigar y modelar fenómenos físicos y químicos mediante la experimentación de laboratorio y el análisis cuantitativo riguroso.',
    defaultObjective: 'Aplicar el principio de conservación de la energía y resolver problemas de estequiometría química en reacciones de óxido-reducción.',
    saberConocer: [
      'Termodinámica: calor, temperatura, leyes de la termodinámica y entropía.',
      'Electromagnetismo: ley de Coulomb, campo eléctrico y circuitos de corriente continua.',
      'Estequiometría: reactivo limitante, rendimiento porcentual y gases ideales.',
    ],
    saberHacer: [
      'Montaje de circuitos eléctricos en protoboard y medición con multímetro digital.',
      'Balanceo de ecuaciones químicas por el método redox e ion-electrón.',
      'Redacción de artículos científicos escolares en formato IMRyD.',
    ],
    saberSer: [
      'Ética científica, honestidad en el reporte de datos y bioseguridad.',
      'Compromiso con el desarrollo de energías limpias y renovables.',
      'Trabajo en equipo y liderazgo en proyectos de investigación aplicada.',
    ],
    indicadoresLogro: [
      'Calcula voltajes, corrientes y resistencias equivalentes en circuitos mixtos.',
      'Determina masas de productos y reactivos en cálculos estequiométricos de laboratorio.',
      'Sustenta proyectos científicos con solvencia teórica y experimental.',
    ],
    bibliografia: [
      'Serway, R. & Jewett, J. (2021). Física para ciencias e ingeniería (10ª ed.). Cengage.',
      'Chang, R. (2020). Química General (13ª ed.). McGraw-Hill Education.',
    ],
  },
  {
    id: 'subj-lenguaje-media-1',
    name: 'Lenguaje y Literatura (Bachillerato)',
    level: 'Bachillerato General',
    grade: '1° y 2° Año de Bachillerato (General y Técnico)',
    weeklyHours: 5,
    annualHours: 200,
    description: 'Literatura universal y latinoamericana, ensayo académico, comunicación corporativa, retórica y análisis del discurso crítico.',
    competenciaGeneral: 'Producir ensayos académicos y discursos persuasivos con rigor conceptual, corrección idiomática y pensamiento crítico.',
    defaultObjective: 'Elaborar un ensayo argumentativo con estructura académica formal sobre una obra emblemática del Boom Latinoamericano.',
    saberConocer: [
      'Literatura clásica grecolatina, del Siglo de Oro y el Realismo Mágico.',
      'Estructura del ensayo académico: tesis, argumentos, contraargumentos y citas APA 7.',
      'Análisis crítico del discurso en medios de comunicación y redes sociales.',
    ],
    saberHacer: [
      'Redacción de ensayos científicos y humanísticos con normas APA 7.',
      'Debate parlamentario y oratoria con técnicas de persuasión y elocuencia.',
      'Comentario crítico de textos literarios y filosóficos universales.',
    ],
    saberSer: [
      'Pensamiento crítico y defensa de la libertad de expresión responsable.',
      'Sensibilidad estética y aprecio por las bellas artes universales.',
      'Rigor intelectual y respeto por la propiedad intelectual evitando el plagio.',
    ],
    indicadoresLogro: [
      'Escribe ensayos coherentes con tesis delimitada y respaldo bibliográfico fidedigno.',
      'Defiende posturas en debates utilizando argumentos fundamentados sin falacias.',
      'Analiza las corrientes literarias y su relación con el contexto socio-histórico.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Lenguaje y Literatura: Bachillerato. San Salvador: MINED.',
      'Weston, A. (2020). Las claves de la argumentación. Editorial Ariel.',
    ],
  },
  {
    id: 'subj-sociales-media-1',
    name: 'Estudios Sociales y Cívica (Bachillerato)',
    level: 'Bachillerato General',
    grade: '1° y 2° Año de Bachillerato (General y Técnico)',
    weeklyHours: 4,
    annualHours: 160,
    description: 'Sociología, economía política, globalización, retos del desarrollo humano en El Salvador y legislación laboral y cívica.',
    competenciaGeneral: 'Analizar las dinámicas socioeconómicas y políticas del país para formular propuestas ciudadanas viables y solidarias.',
    defaultObjective: 'Formular un diagnóstico socioeconómico comunitario y proponer estrategias de desarrollo local sostenible para El Salvador.',
    saberConocer: [
      'Sociología de la realidad salvadoreña: empleo, migración y tejido social.',
      'Macroeconomía: inflación, balanza de pagos, remesas y tratados comerciales.',
      'Derecho laboral salvadoreño: Código de Trabajo, prestaciones y contratos.',
    ],
    saberHacer: [
      'Diseño y aplicación de encuestas de investigación social en la comunidad.',
      'Interpretación de indicadores de desarrollo humano (PNUD, CEPAL, BCR).',
      'Elaboración de proyectos de desarrollo social con matriz de marco lógico.',
    ],
    saberSer: [
      'Compromiso cívico con la justicia distributiva y la equidad social.',
      'Solidaridad activa con los sectores vulnerables y marginados.',
      'Respeto al estado de derecho y transparencia institucional.',
    ],
    indicadoresLogro: [
      'Explica la influencia de la globalización en la economía y cultura nacional.',
      'Conoce y defiende sus derechos laborales y ciudadanos fundamentales.',
      'Propone soluciones fundamentadas a problemáticas sociales locales.',
    ],
    bibliografia: [
      'MINEDUCYT. (2024). Estudios Sociales y Cívica Bachillerato. San Salvador: MINED.',
      'PNUD. (2023). Informe sobre Desarrollo Humano El Salvador.',
    ],
  },
  {
    id: 'subj-seminario-media-2',
    name: 'Seminario de Investigación / Proyecto de Graduación',
    level: 'Bachillerato General',
    grade: '2° Año General / 3° Año Técnico',
    weeklyHours: 3,
    annualHours: 120,
    description: 'Metodología de la investigación científica, formulación de tesis, marco teórico, diseño muestral y defensa oral de tesis.',
    competenciaGeneral: 'Desarrollar una investigación científica o proyecto técnico innovador aplicando las etapas del método científico y normas APA.',
    defaultObjective: 'Ejecutar el trabajo de campo de la investigación y defender los resultados y propuestas ante terna evaluadora colegial.',
    saberConocer: [
      'Metodología de la investigación cuantitativa, cualitativa y mixta.',
      'Diseño muestral, técnicas de recolección de datos y bioética en la investigación.',
      'Estructura de tesis de graduación bajo normas internacionales APA 7ma edición.',
    ],
    saberHacer: [
      'Redacción del planteamiento del problema, justificación y marco teórico.',
      'Procesamiento estadístico de datos con software analítico (Excel / SPSS).',
      'Defensa pública de tesis con presentación ejecutiva y prototipo funcional.',
    ],
    saberSer: [
      'Ética investigativa impecable, honestidad en los datos y rigor metodológico.',
      'Capacidad de trabajo autónomo, disciplina y resiliencia ante las correcciones.',
      'Orientación al impacto social y beneficio directo a la comunidad salesiana.',
    ],
    indicadoresLogro: [
      'Plantea problemas de investigación pertinentes con objetivos claros y medibles.',
      'Aplica instrumentos de recolección de datos con validez y confiabilidad demostrada.',
      'Sustenta su proyecto con excelente dominio técnico, oratoria y seguridad profesional.',
    ],
    bibliografia: [
      'Hernández Sampieri, R. & Mendoza, C. (2020). Metodología de la investigación: Las rutas cuantitativa, cualitativa y mixta. McGraw-Hill.',
      'Colegio Salesiano San José. (2026). Guía Oficial de Seminario y Tesis de Graduación.',
    ],
  },
];

// ==========================================
// 3. JORNALIZACIÓN ANUAL 2026 (EJEMPLOS OFICIALES)
// ==========================================
export const DEFAULT_CSSJ_JORNALIZACIONES: CSSJJornalizacion[] = [
  {
    id: 'jorn-btvdg-101',
    docente: 'Lic. Alexander Gómez / Especialidad Técnica',
    gradoSeccion: '1° Bachillerato Técnico Vocacional "A"',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    anioLectivo: 2026,
    totalSemanas: 40,
    totalDias: 200,
    horasSemanales: 18,
    horasAnuales: 720,
    trimestre1: { inicio: '2026-01-20', fin: '2026-04-11' },
    trimestre2: { inicio: '2026-04-22', fin: '2026-07-18' },
    trimestre3: { inicio: '2026-07-21', fin: '2026-10-17' },
    unidades: [
      { unitNumber: 1, title: 'Fundamentos de la Diagramación y Grillas Editoriales', totalObjectives: 3, classHours: 18, fechaInicio: '2026-01-20', fechaFin: '2026-02-13' },
      { unitNumber: 2, title: 'Anatomía de la Página y Familias Tipográficas', totalObjectives: 3, classHours: 18, fechaInicio: '2026-02-16', fechaFin: '2026-03-06' },
      { unitNumber: 3, title: 'Arquitectura de Folletos y Plegables Promocionales', totalObjectives: 4, classHours: 24, fechaInicio: '2026-03-09', fechaFin: '2026-04-11' },
      { unitNumber: 4, title: 'Maquetación de Revistas y Catálogos Modulares', totalObjectives: 4, classHours: 24, fechaInicio: '2026-04-22', fechaFin: '2026-05-22' },
      { unitNumber: 5, title: 'Diseño de Portadas y Encuadernación Artesanal', totalObjectives: 3, classHours: 18, fechaInicio: '2026-05-25', fechaFin: '2026-06-19' },
      { unitNumber: 6, title: 'Sustratos, Tintas y Acabados Especiales de Impresión', totalObjectives: 3, classHours: 18, fechaInicio: '2026-06-22', fechaFin: '2026-07-18' },
      { unitNumber: 7, title: 'Preprensa Digital, Sangrados y Separación CMYK', totalObjectives: 3, classHours: 18, fechaInicio: '2026-07-21', fechaFin: '2026-08-21' },
      { unitNumber: 8, title: 'Publicaciones Digitales Interactivas (EPUB / PDF)', totalObjectives: 3, classHours: 18, fechaInicio: '2026-08-24', fechaFin: '2026-09-18' },
      { unitNumber: 9, title: 'Proyecto Integrador Editorial y Dummies de Exposición', totalObjectives: 4, classHours: 24, fechaInicio: '2026-09-21', fechaFin: '2026-10-17' },
    ],
  },
  {
    id: 'jorn-basica-501',
    docente: 'Licda. María Eugenia Santos',
    gradoSeccion: 'Educación Básica – 5° “A”, “B” y “C”',
    asignatura: 'Lenguaje y Literatura',
    anioLectivo: 2026,
    totalSemanas: 40,
    totalDias: 200,
    horasSemanales: 5,
    horasAnuales: 200,
    trimestre1: { inicio: '2026-01-20', fin: '2026-04-11' },
    trimestre2: { inicio: '2026-04-22', fin: '2026-07-18' },
    trimestre3: { inicio: '2026-07-21', fin: '2026-10-17' },
    unidades: [
      { unitNumber: 1, title: 'La Crónica Periodística y el Texto Informativo', totalObjectives: 2, classHours: 20, fechaInicio: '2026-01-20', fechaFin: '2026-02-13' },
      { unitNumber: 2, title: 'El Esquema de Llaves y Organizadores Gráficos', totalObjectives: 2, classHours: 20, fechaInicio: '2026-02-16', fechaFin: '2026-03-06' },
      { unitNumber: 3, title: 'Lengua Náhuat y Emociones Ancestrales', totalObjectives: 2, classHours: 20, fechaInicio: '2026-03-09', fechaFin: '2026-04-11' },
      { unitNumber: 4, title: 'El Cuento Fantástico y la Narrativa Salvadoreña', totalObjectives: 2, classHours: 24, fechaInicio: '2026-04-22', fechaFin: '2026-05-22' },
      { unitNumber: 5, title: 'La Poesía Lírica y Figuras Retóricas', totalObjectives: 2, classHours: 20, fechaInicio: '2026-05-25', fechaFin: '2026-06-19' },
      { unitNumber: 6, title: 'El Teatro y la Expresión Escénica', totalObjectives: 2, classHours: 20, fechaInicio: '2026-06-22', fechaFin: '2026-07-18' },
      { unitNumber: 7, title: 'Mitos y Leyendas de Cuscatlán', totalObjectives: 2, classHours: 24, fechaInicio: '2026-07-21', fechaFin: '2026-08-21' },
      { unitNumber: 8, title: 'El Ensayo Infantil y la Argumentación', totalObjectives: 2, classHours: 24, fechaInicio: '2026-08-24', fechaFin: '2026-09-18' },
      { unitNumber: 9, title: 'Medios de Comunicación y Ética Digital', totalObjectives: 2, classHours: 28, fechaInicio: '2026-09-21', fechaFin: '2026-10-17' },
    ],
  },
  {
    id: 'jorn-mate-701',
    docente: 'Prof. Carlos Hernández',
    gradoSeccion: 'Tercer Ciclo – 7° Grado “A”, “B” y “C”',
    asignatura: 'Matemática (ESMATE)',
    anioLectivo: 2026,
    totalSemanas: 40,
    totalDias: 200,
    horasSemanales: 5,
    horasAnuales: 200,
    trimestre1: { inicio: '2026-01-20', fin: '2026-04-11' },
    trimestre2: { inicio: '2026-04-22', fin: '2026-07-18' },
    trimestre3: { inicio: '2026-07-21', fin: '2026-10-17' },
    unidades: [
      { unitNumber: 1, title: 'Números Positivos, Negativos y el Cero', totalObjectives: 4, classHours: 25, fechaInicio: '2026-01-20', fechaFin: '2026-02-13' },
      { unitNumber: 2, title: 'Patrones y Expresiones Algebraicas', totalObjectives: 4, classHours: 25, fechaInicio: '2026-02-16', fechaFin: '2026-03-06' },
      { unitNumber: 3, title: 'Ecuaciones de Primer Grado con una Incógnita', totalObjectives: 5, classHours: 30, fechaInicio: '2026-03-09', fechaFin: '2026-04-11' },
      { unitNumber: 4, title: 'Proporcionalidad Directa e Inversa', totalObjectives: 4, classHours: 25, fechaInicio: '2026-04-22', fechaFin: '2026-05-22' },
      { unitNumber: 5, title: 'Figuras Planas y Transformaciones Geométricas', totalObjectives: 3, classHours: 20, fechaInicio: '2026-05-25', fechaFin: '2026-06-19' },
      { unitNumber: 6, title: 'Áreas y Volúmenes de Cuerpos Geométricos', totalObjectives: 4, classHours: 25, fechaInicio: '2026-06-22', fechaFin: '2026-07-18' },
      { unitNumber: 7, title: 'Estadística y Tablas de Frecuencia', totalObjectives: 4, classHours: 25, fechaInicio: '2026-07-21', fechaFin: '2026-08-21' },
      { unitNumber: 8, title: 'Probabilidad y Toma de Decisiones', totalObjectives: 3, classHours: 25, fechaInicio: '2026-08-24', fechaFin: '2026-10-17' },
    ],
  },
];

// ==========================================
// 4. PLANIFICACIÓN DIDÁCTICA 2026 (OFICIAL CSSJ)
// ==========================================
export const DEFAULT_CSSJ_PLANES_DIDACTICOS: CSSJPlanDidactico[] = [
  {
    id: 'plan-btvdg-unit1',
    centroEducativo: 'Colegio Salesiano San José',
    docente: 'Lic. Alexander Gómez',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    grado: '1° Año Técnico',
    seccion: 'A y B',
    unidadNumero: 1,
    unidadNombre: 'Fundamentos de la Diagramación y Grillas Editoriales',
    trimestrePeriodo: 'Trimestre I',
    tiempoHoras: 18,
    fechas: '20 de enero al 13 de febrero de 2026',
    competenciasAsignatura: 'Estructurar publicaciones editoriales aplicando normas de jerarquía visual, retícula suiza y preimpresión con solvencia técnica.',
    competenciasUnidad: 'Diseñar retículas modulares de 6 y 12 columnas en software vectorial y de maquetación, optimizando el espacio gráfico.',
    contenidosConceptuales: [
      'Historia de la retícula editorial y el Estilo Tipográfico Internacional Suizo.',
      'Cálculo de márgenes, callejones, medianil y jerarquías de lectura.',
      'Software de diagramación (Adobe InDesign / Illustrator): páginas maestras y estilos de párrafo.',
    ],
    contenidosProcedimentales: [
      'Construcción de grillas modulares en software especializado respetando la proporción áurea.',
      'Bocetaje manual en retículas impresas con rotulador y escala milimétrica.',
      'Maquetación de un díptico editorial con colocación de texto falso (Lorem Ipsum) y cajas de imagen.',
    ],
    contenidosActitudinales: [
      'Rigor y meticulosidad en la precisión geométrica de márgenes y medianiles.',
      'Respeto a las normas de convivencia y cuidado del equipo informático del taller.',
      'Actitud crítica y constructiva al recibir retroalimentación docente en la mesa de luz.',
    ],
    metodologia: 'Metodología de Proyectos con Enfoque de Acción Completa (Informar, Planificar, Decidir, Ejecutar, Controlar, Valorar).',
    indicadoresLogro: [
      '1.1 Traza con precisión milimétrica la retícula editorial respetando los márgenes de seguridad para encuadernación.',
      '1.2 Aplica estilos de párrafo y jerarquías tipográficas legibles según el estándar editorial MINEDUCYT.',
      '1.3 Demuestra orden y limpieza en la entrega del dummy físico del díptico maquetado.',
    ],
    actividadesEvaluacion: [
      { no: 1, nombre: 'Matriz de Retículas y Guía de Bocetaje Manual', ponderacion: '35%', fechaRealizacion: '30 de enero de 2026' },
      { no: 2, nombre: 'Maquetación Digital del Díptico en InDesign', ponderacion: '35%', fechaRealizacion: '06 de febrero de 2026' },
      { no: 3, nombre: 'Prueba Objetiva Teórica de Tipometría y Márgenes', ponderacion: '30%', fechaRealizacion: '13 de febrero de 2026' },
    ],
    recursos: 'Computadoras con suite Adobe CC, papel bond de 90g, escalímetro, cuchillas olfa y base de corte.',
    tics: 'Plataforma LMS Campus Salesiano, repositorios Google Drive y bibliotecas de fuentes Adobe Fonts.',
    bibliografiaEgrafia: [
      'Müller-Brockmann, J. (2018). Sistemas de retículas: Un manual para diseñadores gráficos. Gustavo Gili.',
      'Bringhurst, R. (2019). Los elementos del estilo tipográfico (4ta ed.). Fondo de Cultura Económica.',
      'MINEDUCYT. (2025). Descriptor del Módulo BTVDG1.7 Diseño Editorial. San Salvador: MINED.',
    ],
  },
];

// ==========================================
// 5. GUIONES DE CLASE 2026 (OFICIAL CSSJ)
// ==========================================
export const DEFAULT_CSSJ_GUIONES: CSSJGuionClase[] = [
  {
    id: 'guion-clase-1',
    docente: 'Lic. Alexander Gómez',
    gradoSeccion: '1° Bachillerato Técnico "A"',
    trimestre: 'Trimestre I',
    fecha: '2026-01-26',
    unidad: 'Unidad 1: Fundamentos de la Diagramación',
    contenido: 'Cálculo de Grillas Modulares y Jerarquías de Párrafo en InDesign',
    tiempoMinutos: 90,
    objetivoClase: 'Calcular e implementar retículas de 12 columnas con páginas maestras para publicaciones de formato carta.',
    indicadorLogro: '1.2 Aplica estilos de párrafo y jerarquías tipográficas legibles según el estándar editorial.',
    competenciasEspecificas: 'Dominio de software editorial, configuración de márgenes y sangrado técnico.',
    ejeTransversal: 'Educación ambiental: optimización de pliegos y reducción de merma de sustratos en pruebas de impresión.',
    inicio: {
      situacion: 'Lluvia de ideas proyectando portadas de revistas icónicas (National Geographic, Vogue, Wired). Preguntas generadoras sobre ¿Por qué nuestros ojos viajan primero al titular?',
      tipoEvaluacion: 'Diagnóstica (sin valor numérico)',
      estrategia: 'Estrategia diagnóstica para identificar aprendizajes previos de composición y tipometría.',
    },
    desarrollo: {
      situacion: 'Demostración paso a paso en proyector de creación de documento en InDesign, configuración de márgenes (Superior: 20mm, Inferior: 25mm, Interior: 15mm, Exterior: 20mm, Sangrado: 3mm). Práctica guiada en laboratorio.',
      tipoEvaluacion: 'Formativa (sin valor numérico)',
      estrategia: 'Evaluación formativa mediante revisión individual en estación de trabajo para verificar si comprendieron el concepto de medianil y páginas enfrentadas.',
    },
    cierre: {
      situacion: 'Consolidación de dudas y exportación del primer pliego en PDF interactivo para revisión en el LMS.',
      tipoEvaluacion: 'Sumativa (con valor % en cuadro de actividades)',
      ponderacionPorcentaje: 10,
      propuestaActividades: 'Mini-entrega de avance de retícula en LMS con rúbrica técnica de 29 ítems.',
      analisisDesempeno: 'El 85% de los estudiantes asimiló con éxito la diferencia entre margen interior para lomo y margen exterior.',
    },
    adaptacionesCurriculares: 'Se proporciona guía impresa con atajos de teclado y contraste de interfaz aumentado para estudiantes con requerimientos visuales.',
    actividadesEvaluacion: [
      { no: 1, actividad: 'Avance de Maqueta con Retícula Suiza', ponderacion: '10%', fecha: '2026-01-26' },
    ],
    tarea: 'Investigar 3 ejemplos de retícula asimétrica y traerlos impresos o digitales en formato moodboard.',
    bibliografiaAPA7: 'Müller-Brockmann, J. (2018). Sistemas de retículas. Gustavo Gili.',
    recursosClase: 'Laboratorio Mac/PC con Adobe InDesign, proyector interactivo, reglas metálicas.',
    tics: 'Campus Virtual LMS Salesiano, atajos en PDF.',
  },
];

// ==========================================
// 6. CUADRO DE ACTIVIDADES (35% + 35% + 30%) CSSJ
// ==========================================
export const DEFAULT_CSSJ_CUADROS_ACTIVIDADES: CSSJCuadroActividades[] = [
  {
    id: 'cuadro-act-1',
    centroEducativo: 'Colegio Salesiano San José',
    nivelEducativo: 'Educación Media – 1° Bachillerato Técnico Vocacional',
    gradoSeccion: '1° "A" y "B"',
    docente: 'Lic. Alexander Gómez',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    trimestrePeriodo: 'Trimestre I',
    actividadTitulo: 'Actividad N° 01 – 35% (Proyecto Editorial Fase I)',
    fechaRango: '19 de enero al 13 de febrero de 2026',
    subactividades: [
      {
        no: 1,
        nombre: 'Matriz de Retículas y Guía de Bocetaje Manual',
        descripcion: 'Realizar 6 bocetos a mano alzada de doble página de revista aplicando retícula de 6 y 12 columnas. Entregar en folder con portada formal.',
        criteriosEvaluacion: 'Se adjunta rúbrica de evaluación oficial MINED (29 ítems). Entregar 2 rúbricas impresas (una para el alumno y otra para el docente).',
        formato: 'Entrega en físico',
        porcentaje: 35,
        fechaEntrega: '30 de enero de 2026',
        rubricaAdjuntaInfo: 'Rúbrica de 29 ítems BTV (Técnico 35%, Emprendedor 25%, Humano 20%, Académico 20%).',
      },
      {
        no: 2,
        nombre: 'Maquetación Digital del Díptico en InDesign',
        descripcion: 'Construir el archivo maestro `.indd` con páginas maestras, estilos de párrafo y colocación de imágenes en alta resolución con sangrado de 3mm.',
        criteriosEvaluacion: 'Cumplimiento de márgenes, empaquetado de fuentes y links, exportación en PDF/X-1a.',
        formato: 'Entrega en plataforma (LMS)',
        porcentaje: 35,
        fechaEntrega: '06 de febrero de 2026',
        rubricaAdjuntaInfo: 'Verificación técnica de artes finales y perfil CMYK.',
      },
      {
        no: 3,
        nombre: 'Dummy Físico y Sustentación de la Propuesta',
        descripcion: 'Armar la maqueta física impresa a doble cara en papel couché de 150g con corte y doblez exacto. Presentación en pareja.',
        criteriosEvaluacion: 'Acabado manual, precisión en el lomo, sustentación oral del concepto.',
        formato: 'Mixto (Físico + Digital)',
        porcentaje: 30,
        fechaEntrega: '13 de febrero de 2026',
        rubricaAdjuntaInfo: 'Rúbrica de Pitch y Dummy.',
      },
    ],
    indicacionesCoordinacion: {
      politicaRetraso: 'LA ENTREGA DE TRABAJOS FUERA DE LAS FECHAS SEÑALADAS SE RECIBIRÁ ÚNICAMENTE CON JUSTIFICACIÓN FORMAL Y LA NOTA DISMINUIRÁ SEGÚN LOS DÍAS DE RETRASO.',
      limiteDias: 'LAS ACTIVIDADES SERÁN RECIBIDAS HASTA DOS DÍAS DESPUÉS DE LA FECHA LÍMITE.',
      periodoExtraordinario: 'POSTERIOR A ESE PLAZO, EL ESTUDIANTE DEBERÁ ENTREGAR EN PERIODO EXTRAORDINARIO CON BASE MÁXIMA DE 5.0.',
      manualConvivencia: 'Si un estudiante incumple las normas del aula o taller, será notificado a sus responsables y se aplicará el Manual de Convivencia Institucional.',
    },
  },
];

// ==========================================
// 7. TEMARIO DE CONTENIDOS A EVALUAR (30%) CSSJ
// ==========================================
export const DEFAULT_CSSJ_TEMARIOS: CSSJTemarioEvaluacion[] = [
  {
    id: 'temario-1',
    docente: 'Lic. Alexander Gómez',
    asignatura: 'BTVDG1.7 Diseño y Producción Editorial',
    gradoSeccion: '1° Bachillerato Técnico "A"',
    periodoTrimestre: 'Primer Periodo / Trimestre I',
    porcentaje: '30%',
    periodoComprendido: '19 de enero al 20 de marzo de 2026 (Tomado de la Jornalización)',
    contenidosAEvaluar: [
      { contenido: 'Historia de la retícula y aportes de Josef Müller-Brockmann', paginaEspecificacion: 'Manual Guía págs. 14-22' },
      { contenido: 'Tipometría: cícero, puntos didot, puntos pica y cálculo milimétrico', paginaEspecificacion: 'Guía técnica 1, págs. 5-11' },
      { contenido: 'Anatomía de la tipografía (serif, sans serif, astas, remates, modulación)', paginaEspecificacion: 'Descriptor BTVDG, Unidad 1' },
      { contenido: 'Diferencias entre síntesis aditiva (RGB) y síntesis sustractiva (CMYK)', paginaEspecificacion: 'Módulo de Color, págs. 30-38' },
      { contenido: 'Parámetros técnicos de preprensa: sangrado, margen de seguridad y trapping', paginaEspecificacion: 'Rúbrica de taller, ítem T4' },
      { contenido: 'Normas de exportación PDF/X-1a y resolución óptima (300 DPI vs 72 DPI)', paginaEspecificacion: 'Guía de laboratorio InDesign' },
    ],
    indicadoresLogro: [
      'Identifica con certeza las partes anatómicas de la tipografía y calcula equivalencias en puntos.',
      'Diferencia los modos de color y resoluciones necesarias para impresión offset y pantalla digital.',
      'Calcula márgenes y medianiles para diversas piezas editoriales de alta foliación.',
    ],
    indicacionesGenerales: 'Traer lápiz, borrador, calculadora básica y escalímetro. No se permite el uso de teléfonos celulares durante la prueba objetiva ordinaria.',
  },
];

// ==========================================
// CLASE PRINCIPAL DEL SERVICIO DE DOCUMENTACIÓN CURRICULAR
// ==========================================
const STORAGE_KEY_CALENDAR = 'cssj_lms_calendar_2026';
const STORAGE_KEY_JORNAL = 'cssj_lms_jornalizaciones_2026';
const STORAGE_KEY_PLANES = 'cssj_lms_planes_didacticos_2026';
const STORAGE_KEY_GUIONES = 'cssj_lms_guiones_clase_2026';
const STORAGE_KEY_CUADROS = 'cssj_lms_cuadros_actividades_2026';
const STORAGE_KEY_TEMARIOS = 'cssj_lms_temarios_evaluacion_2026';
const STORAGE_KEY_RUBRIC_SCORES = 'cssj_lms_rubric_evaluations';

export class CurriculumDocsService {
  private calendarPeriods: CSSJCalendarPeriod[] = [];
  private jornalizaciones: CSSJJornalizacion[] = [];
  private planesDidacticos: CSSJPlanDidactico[] = [];
  private guionesClase: CSSJGuionClase[] = [];
  private cuadrosActividades: CSSJCuadroActividades[] = [];
  private temariosEvaluacion: CSSJTemarioEvaluacion[] = [];
  private listeners: (() => void)[] = [];

  constructor() {
    this.loadFromStorage();
  }

  private loadFromStorage() {
    try {
      const savedCal = localStorage.getItem(STORAGE_KEY_CALENDAR);
      this.calendarPeriods = savedCal ? JSON.parse(savedCal) : DEFAULT_CSSJ_CALENDAR_PERIODS;

      const savedJorn = localStorage.getItem(STORAGE_KEY_JORNAL);
      this.jornalizaciones = savedJorn ? JSON.parse(savedJorn) : DEFAULT_CSSJ_JORNALIZACIONES;

      const savedPlanes = localStorage.getItem(STORAGE_KEY_PLANES);
      this.planesDidacticos = savedPlanes ? JSON.parse(savedPlanes) : DEFAULT_CSSJ_PLANES_DIDACTICOS;

      const savedGuiones = localStorage.getItem(STORAGE_KEY_GUIONES);
      this.guionesClase = savedGuiones ? JSON.parse(savedGuiones) : DEFAULT_CSSJ_GUIONES;

      const savedCuadros = localStorage.getItem(STORAGE_KEY_CUADROS);
      this.cuadrosActividades = savedCuadros ? JSON.parse(savedCuadros) : DEFAULT_CSSJ_CUADROS_ACTIVIDADES;

      const savedTemarios = localStorage.getItem(STORAGE_KEY_TEMARIOS);
      this.temariosEvaluacion = savedTemarios ? JSON.parse(savedTemarios) : DEFAULT_CSSJ_TEMARIOS;
    } catch {
      this.calendarPeriods = DEFAULT_CSSJ_CALENDAR_PERIODS;
      this.jornalizaciones = DEFAULT_CSSJ_JORNALIZACIONES;
      this.planesDidacticos = DEFAULT_CSSJ_PLANES_DIDACTICOS;
      this.guionesClase = DEFAULT_CSSJ_GUIONES;
      this.cuadrosActividades = DEFAULT_CSSJ_CUADROS_ACTIVIDADES;
      this.temariosEvaluacion = DEFAULT_CSSJ_TEMARIOS;
    }
  }

  private saveToStorage() {
    try {
      localStorage.setItem(STORAGE_KEY_CALENDAR, JSON.stringify(this.calendarPeriods));
      localStorage.setItem(STORAGE_KEY_JORNAL, JSON.stringify(this.jornalizaciones));
      localStorage.setItem(STORAGE_KEY_PLANES, JSON.stringify(this.planesDidacticos));
      localStorage.setItem(STORAGE_KEY_GUIONES, JSON.stringify(this.guionesClase));
      localStorage.setItem(STORAGE_KEY_CUADROS, JSON.stringify(this.cuadrosActividades));
      localStorage.setItem(STORAGE_KEY_TEMARIOS, JSON.stringify(this.temariosEvaluacion));
    } catch (e) {
      console.warn('Storage save failed:', e);
    }
    this.notify();
  }

  public subscribe(fn: () => void) {
    this.listeners.push(fn);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== fn);
    };
  }

  private notify() {
    this.listeners.forEach((fn) => fn());
  }

  // --- CALENDARIO ACADÉMICO ---
  public getCalendarPeriods(): CSSJCalendarPeriod[] {
    return [...this.calendarPeriods];
  }

  public updateCalendarPeriod(period: CSSJCalendarPeriod) {
    const idx = this.calendarPeriods.findIndex((p) => p.id === period.id);
    if (idx >= 0) {
      this.calendarPeriods[idx] = period;
    } else {
      this.calendarPeriods.push(period);
    }
    this.saveToStorage();
  }

  public deleteCalendarPeriod(id: string) {
    this.calendarPeriods = this.calendarPeriods.filter((p) => p.id !== id);
    this.saveToStorage();
  }

  // --- JORNALIZACIÓN ---
  public getJornalizaciones(): CSSJJornalizacion[] {
    return [...this.jornalizaciones];
  }

  public saveJornalizacion(jorn: CSSJJornalizacion) {
    const idx = this.jornalizaciones.findIndex((j) => j.id === jorn.id);
    if (idx >= 0) {
      this.jornalizaciones[idx] = jorn;
    } else {
      this.jornalizaciones.push(jorn);
    }
    this.saveToStorage();
  }

  public deleteJornalizacion(id: string) {
    this.jornalizaciones = this.jornalizaciones.filter((j) => j.id !== id);
    this.saveToStorage();
  }

  // --- PLANIFICACIÓN DIDÁCTICA ---
  public getPlanesDidacticos(): CSSJPlanDidactico[] {
    return [...this.planesDidacticos];
  }

  public savePlanDidactico(plan: CSSJPlanDidactico) {
    const idx = this.planesDidacticos.findIndex((p) => p.id === plan.id);
    if (idx >= 0) {
      this.planesDidacticos[idx] = plan;
    } else {
      this.planesDidacticos.push(plan);
    }
    this.saveToStorage();
  }

  public deletePlanDidactico(id: string) {
    this.planesDidacticos = this.planesDidacticos.filter((p) => p.id !== id);
    this.saveToStorage();
  }

  // --- GUIONES DE CLASE ---
  public getGuionesClase(): CSSJGuionClase[] {
    return [...this.guionesClase];
  }

  public saveGuionClase(guion: CSSJGuionClase) {
    const idx = this.guionesClase.findIndex((g) => g.id === guion.id);
    if (idx >= 0) {
      this.guionesClase[idx] = guion;
    } else {
      this.guionesClase.push(guion);
    }
    this.saveToStorage();
  }

  public deleteGuionClase(id: string) {
    this.guionesClase = this.guionesClase.filter((g) => g.id !== id);
    this.saveToStorage();
  }

  // --- CUADROS DE ACTIVIDADES ---
  public getCuadrosActividades(): CSSJCuadroActividades[] {
    return [...this.cuadrosActividades];
  }

  public saveCuadroActividades(cuadro: CSSJCuadroActividades) {
    const idx = this.cuadrosActividades.findIndex((c) => c.id === cuadro.id);
    if (idx >= 0) {
      this.cuadrosActividades[idx] = cuadro;
    } else {
      this.cuadrosActividades.push(cuadro);
    }
    this.saveToStorage();
  }

  public deleteCuadroActividades(id: string) {
    this.cuadrosActividades = this.cuadrosActividades.filter((c) => c.id !== id);
    this.saveToStorage();
  }

  // --- TEMARIOS DE EVALUACIÓN ---
  public getTemariosEvaluacion(): CSSJTemarioEvaluacion[] {
    return [...this.temariosEvaluacion];
  }

  public saveTemarioEvaluacion(temario: CSSJTemarioEvaluacion) {
    const idx = this.temariosEvaluacion.findIndex((t) => t.id === temario.id);
    if (idx >= 0) {
      this.temariosEvaluacion[idx] = temario;
    } else {
      this.temariosEvaluacion.push(temario);
    }
    this.saveToStorage();
  }

  public deleteTemarioEvaluacion(id: string) {
    this.temariosEvaluacion = this.temariosEvaluacion.filter((t) => t.id !== id);
    this.saveToStorage();
  }

  // --- 29 ÍTEMS EVALUATION CALCULATOR ---
  public calculate29RubricGrade(scores: Record<string, MinedLevel>): {
    scoreTecnico: number;
    scoreEmprendedor: number;
    scoreHumano: number;
    scoreAcademico: number;
    weightedGrade: number;
    finalMinedLevel: MinedLevel;
    approved: boolean;
  } {
    const levelToScore = (lvl: MinedLevel) => {
      switch (lvl) {
        case 1: return 4.0;
        case 2: return 5.5;
        case 3: return 6.5;
        case 4: return 8.5;
        case 5: return 10.0;
        default: return 7.0;
      }
    };

    const getAxisAverage = (axis: 'tecnico' | 'emprendedor' | 'humano' | 'academico') => {
      const items = BTV_29_RUBRIC_ITEMS.filter((i) => i.axis === axis);
      let total = 0;
      let count = 0;
      items.forEach((i) => {
        const lvl = scores[i.id] || 4; // default to level 4
        total += levelToScore(lvl);
        count++;
      });
      return count > 0 ? +(total / count).toFixed(1) : 8.5;
    };

    const scoreTecnico = getAxisAverage('tecnico');
    const scoreEmprendedor = getAxisAverage('emprendedor');
    const scoreHumano = getAxisAverage('humano');
    const scoreAcademico = getAxisAverage('academico');

    const weightedGrade = +(
      scoreTecnico * 0.35 +
      scoreEmprendedor * 0.25 +
      scoreHumano * 0.20 +
      scoreAcademico * 0.20
    ).toFixed(1);

    const finalMinedLevel: MinedLevel =
      weightedGrade >= 9.6 ? 5 :
      weightedGrade >= 8.5 ? 4 :
      weightedGrade >= 7.0 ? 3 :
      weightedGrade >= 5.0 ? 2 : 1;

    return {
      scoreTecnico,
      scoreEmprendedor,
      scoreHumano,
      scoreAcademico,
      weightedGrade,
      finalMinedLevel,
      approved: weightedGrade >= 7.0,
    };
  }
}

export const curriculumDocsService = new CurriculumDocsService();
