// GENERATED BY GEMINI — Campus Salesiano San José
// Shared QuickStatsSidebar component (Right-side panel with User, Calendar & Next Events)

import React from 'react';
import { Calendar as CalendarIcon, ChevronLeft, ChevronRight, Clock, BookOpen } from 'lucide-react';
import { LMSActivity } from '../../types';

interface QuickStatsSidebarProps {
  userName?: string;
  userRole?: string;
  upcomingActivities?: LMSActivity[];
  onActivityClick?: (activityId: string) => void;
}

export const QuickStatsSidebar: React.FC<QuickStatsSidebarProps> = ({
  userName = 'Estudiante Salesiano',
  userRole = 'Alumno',
  upcomingActivities = [],
  onActivityClick,
}) => {
  const daysInMonth = 31;
  const startDayOffset = 6; // Saturday start for Aug 1, 2026
  const currentDay = 22;

  const daysOfWeek = ['DO', 'LU', 'MA', 'MI', 'JU', 'VI', 'SA'];

  return (
    <aside className="w-full xl:w-72 shrink-0 space-y-5">
      {/* User profile card */}
      <div className="card-crema p-4 flex items-center gap-3">
        <div className="w-11 h-11 rounded-2xl bg-[#25855A] text-white flex items-center justify-center font-display font-bold text-sm shadow-sm">
          {userName
            .split(' ')
            .map((n) => n[0])
            .slice(0, 2)
            .join('')}
        </div>
        <div className="min-w-0 flex-1">
          <h4 className="font-display font-bold text-slate-900 text-sm truncate">
            {userName}
          </h4>
          <div className="flex items-center gap-1.5 mt-0.5">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-xs font-semibold text-emerald-700">En línea</span>
            <span className="text-slate-300">•</span>
            <span className="text-xs text-slate-500">{userRole}</span>
          </div>
        </div>
      </div>

      {/* Mini Calendar widget */}
      <div className="card-crema p-4.5">
        <div className="flex items-center justify-between mb-3.5">
          <button
            type="button"
            className="p-1 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-colors"
          >
            <ChevronLeft className="w-4 h-4" />
          </button>
          <span className="font-display font-bold text-slate-800 text-xs">
            Agosto 2026
          </span>
          <button
            type="button"
            className="p-1 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-colors"
          >
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>

        {/* Days of week */}
        <div className="grid grid-cols-7 gap-1 text-center mb-2">
          {daysOfWeek.map((d) => (
            <span key={d} className="text-[10px] font-bold text-slate-400 uppercase">
              {d}
            </span>
          ))}
        </div>

        {/* Days numbers */}
        <div className="grid grid-cols-7 gap-1 text-center">
          {Array.from({ length: startDayOffset }).map((_, idx) => (
            <span key={`empty-${idx}`} className="h-6" />
          ))}
          {Array.from({ length: daysInMonth }).map((_, idx) => {
            const dayNum = idx + 1;
            const isToday = dayNum === currentDay;
            const hasEvent = dayNum === 26 || dayNum === 28;

            return (
              <div
                key={dayNum}
                className={`h-6 text-[11px] font-semibold flex items-center justify-center rounded-lg relative ${
                  isToday
                    ? 'bg-[#124D37] text-white font-bold shadow-sm'
                    : 'text-slate-700 hover:bg-slate-100'
                }`}
              >
                {dayNum}
                {hasEvent && !isToday && (
                  <span className="absolute bottom-0.5 w-1 h-1 rounded-full bg-amber-400" />
                )}
              </div>
            );
          })}
        </div>

        {/* Legend */}
        <div className="flex items-center justify-center gap-3 mt-3.5 pt-3 border-t border-slate-100 text-[10px] text-slate-500 font-medium">
          <span className="flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-amber-400" /> Asueto
          </span>
          <span className="flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#0D71B9]" /> Evento
          </span>
          <span className="flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#124D37]" /> Hoy
          </span>
        </div>
      </div>

      {/* Próximas Entregas LMS */}
      <div className="card-crema p-4.5 space-y-3">
        <div className="flex items-center justify-between">
          <h4 className="font-display font-bold text-slate-900 text-xs uppercase tracking-wider">
            Próximas Entregas
          </h4>
          <span className="text-[11px] font-bold text-[#25855A] bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200">
            LMS
          </span>
        </div>

        {upcomingActivities.length === 0 ? (
          <p className="text-xs text-slate-400 text-center py-4">Sin entregas pendientes</p>
        ) : (
          <div className="space-y-2.5">
            {upcomingActivities.slice(0, 3).map((act) => (
              <div
                key={act.id}
                onClick={() => onActivityClick?.(act.id)}
                className="p-2.5 rounded-xl bg-slate-50 border border-slate-200/70 hover:border-[#25855A]/50 transition-all cursor-pointer group"
              >
                <div className="flex items-center justify-between text-[10px] mb-1">
                  <span
                    className="font-bold truncate max-w-[130px]"
                    style={{ color: act.courseColor || '#0D71B9' }}
                  >
                    {act.courseName}
                  </span>
                  <span className="text-slate-500 flex items-center gap-1">
                    <Clock className="w-2.5 h-2.5" />
                    {new Date(act.dueDate).toLocaleDateString('es-SV', {
                      day: 'numeric',
                      month: 'short',
                    })}
                  </span>
                </div>
                <p className="text-xs font-semibold text-slate-800 line-clamp-1 group-hover:text-[#25855A] transition-colors">
                  {act.title}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>
    </aside>
  );
};

export default QuickStatsSidebar;
