// GENERATED BY GEMINI — Campus Salesiano San José
// Shared RoleLayout component (Sidebar + Header + Content Container + Role Switcher)

import React, { useState } from 'react';
import {
  BookOpen,
  ClipboardCheck,
  Calendar,
  Medal,
  LogOut,
  Bell,
  Search,
  ChevronDown,
  Layers,
  GraduationCap,
  Sparkles,
  Award,
  CheckCircle2,
  Menu,
  X,
  User,
  Shield,
  Settings,
} from 'lucide-react';
import { SystemModuleId } from '../../types';

interface NavItem {
  label: string;
  path: string;
  icon: React.ElementType;
  badge?: string;
}

interface RoleLayoutProps {
  children: React.ReactNode;
  activePath?: string;
  onNavigate?: (path: string) => void;
  currentRole?: 'alumno' | 'docente' | 'admin';
  onRoleChange?: (role: 'alumno' | 'docente' | 'admin') => void;
  studentName?: string;
}

export const RoleLayout: React.FC<RoleLayoutProps> = ({
  children,
  activePath = '/alumno/lms',
  onNavigate = (_path: string) => {},
  currentRole = 'alumno',
  onRoleChange,
  studentName = 'Estudiante Salesiano',
}) => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  // Role Navigation Items
  const studentNavItems: NavItem[] = [
    { label: 'Mi Aula Virtual (LMS)', path: '/alumno/lms', icon: BookOpen, badge: 'Nuevo' },
    { label: 'Mis Cursos', path: '/alumno/lms/cursos', icon: Layers },
    { label: 'Mis Actividades', path: '/alumno/lms/actividades', icon: ClipboardCheck },
    { label: 'Mi Progreso', path: '/alumno/lms/progreso', icon: Award },
    { label: 'Dashboard Principal', path: '/alumno', icon: GraduationCap },
  ];

  const adminNavItems: NavItem[] = [
    { label: 'Dashboard Admin', path: '/admin', icon: GraduationCap },
    { label: 'Gestión LMS & Cursos', path: '/admin/lms-config', icon: BookOpen, badge: 'LMS Config' },
    { label: 'Documentación Curricular', path: '/docente/curricular', icon: Calendar, badge: 'CSSJ 2026' },
    { label: 'Secciones y Aulas', path: '/admin/secciones', icon: Layers },
    { label: 'Coordinaciones', path: '/admin/coordinaciones', icon: Settings },
  ];

  const docenteNavItems: NavItem[] = [
    { label: 'Dashboard Docente', path: '/docente', icon: GraduationCap },
    { label: 'Documentación Curricular', path: '/docente/curricular', icon: Calendar, badge: 'CSSJ 2026' },
    { label: 'Calificar Actividades LMS', path: '/docente/lms', icon: BookOpen },
    { label: 'Rúbrica 29 Ítems BTV', path: '/docente/rubrica-29', icon: Award, badge: 'MINED' },
    { label: 'Gestión de Proyectos', path: '/docente/proyectos', icon: Medal },
  ];

  const navItems: NavItem[] =
    currentRole === 'admin'
      ? adminNavItems
      : currentRole === 'docente'
      ? docenteNavItems
      : studentNavItems;

  return (
    <div className="min-h-screen bg-[#F0F4F8] flex flex-col lg:flex-row text-slate-800">
      {/* ============================================================ */}
      {/* DESKTOP & MOBILE SIDEBAR */}
      {/* ============================================================ */}
      <aside
        className={`fixed lg:sticky top-0 left-0 h-screen z-50 w-64 bg-white border-r border-slate-200/80 flex flex-col justify-between p-4.5 transition-transform duration-200 lg:translate-x-0 ${
          mobileMenuOpen ? 'translate-x-0' : '-translate-x-full'
        }`}
      >
        <div>
          {/* Logo & Campus Branding */}
          <div className="flex items-center justify-between gap-3 px-2 py-2 mb-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-2xl bg-[#124D37] text-white flex items-center justify-center font-display font-extrabold text-base shadow-sm">
                CS
              </div>
              <div>
                <h2 className="font-display font-bold text-slate-900 text-sm leading-tight">
                  Campus
                </h2>
                <p className="text-[11px] text-slate-400 font-medium">Salesiano San José</p>
              </div>
            </div>

            <button
              type="button"
              onClick={() => setMobileMenuOpen(false)}
              className="lg:hidden p-1 rounded-lg hover:bg-slate-100 text-slate-400"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Navigation Section */}
          <div className="space-y-1">
            <p className="px-3 text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">
              {currentRole === 'alumno' ? 'AULA VIRTUAL' : 'MÓDULOS DEL SISTEMA'}
            </p>

            {navItems.map((item) => {
              const isActive =
                activePath === item.path ||
                (item.path !== '/alumno' &&
                  item.path !== '/admin' &&
                  item.path !== '/docente' &&
                  activePath.startsWith(item.path));
              const Icon = item.icon;

              return (
                <button
                  key={item.path}
                  type="button"
                  onClick={() => {
                    onNavigate(item.path);
                    setMobileMenuOpen(false);
                  }}
                  className={`w-full flex items-center justify-between px-3.5 py-2.5 rounded-xl text-xs font-semibold transition-all ${
                    isActive
                      ? 'bg-[#25855A]/10 text-[#25855A] font-bold border border-[#25855A]/25 shadow-xs'
                      : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <Icon
                      className={`w-4 h-4 ${
                        isActive ? 'text-[#25855A]' : 'text-slate-400'
                      }`}
                    />
                    <span>{item.label}</span>
                  </div>

                  {item.badge && (
                    <span className="text-[10px] font-bold px-1.5 py-0.5 rounded-md bg-[#25855A] text-white">
                      {item.badge}
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        </div>

        {/* Bottom user & role toggle */}
        <div className="pt-4 border-t border-slate-100 space-y-3">
          {/* Quick Role Switcher for Testability */}
          {onRoleChange && (
            <div className="p-2.5 rounded-2xl bg-slate-50 border border-slate-200/80">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1.5">
                Modo de Visualización:
              </span>
              <div className="grid grid-cols-3 gap-1">
                {(['alumno', 'docente', 'admin'] as const).map((r) => (
                  <button
                    key={r}
                    type="button"
                    onClick={() => {
                      onRoleChange(r);
                      if (r === 'alumno') onNavigate('/alumno/lms');
                      if (r === 'docente') onNavigate('/docente/lms');
                      if (r === 'admin') onNavigate('/admin/lms-config');
                    }}
                    className={`text-[10px] font-bold py-1 px-1 rounded-lg capitalize transition-all ${
                      currentRole === r
                        ? 'bg-[#25855A] text-white shadow-xs'
                        : 'bg-white text-slate-600 border border-slate-200/60 hover:bg-slate-100'
                    }`}
                  >
                    {r}
                  </button>
                ))}
              </div>
            </div>
          )}

          <div className="flex items-center justify-between px-2">
            <div className="flex items-center gap-2.5 min-w-0">
              <div className="w-8 h-8 rounded-xl bg-slate-100 text-slate-700 font-bold text-xs flex items-center justify-center">
                {currentRole === 'admin' ? (
                  <Shield className="w-4 h-4 text-emerald-700" />
                ) : (
                  <User className="w-4 h-4 text-slate-600" />
                )}
              </div>
              <div className="min-w-0">
                <p className="text-xs font-bold text-slate-900 truncate">
                  {currentRole === 'admin' ? 'Administrador General' : studentName}
                </p>
                <p className="text-[10px] text-slate-400 uppercase font-semibold">
                  {currentRole}
                </p>
              </div>
            </div>

            <button
              type="button"
              title="Cerrar Sesión"
              className="p-1.5 text-slate-400 hover:text-red-600 rounded-lg hover:bg-red-50 transition-colors"
            >
              <LogOut className="w-4 h-4" />
            </button>
          </div>
        </div>
      </aside>

      {/* Backdrop for mobile */}
      {mobileMenuOpen && (
        <div
          onClick={() => setMobileMenuOpen(false)}
          className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs z-40 lg:hidden"
        />
      )}

      {/* ============================================================ */}
      {/* MAIN CONTENT AREA */}
      {/* ============================================================ */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Top Header Bar */}
        <header className="sticky top-0 z-30 bg-white/90 backdrop-blur-md border-b border-slate-200/80 px-4 md:px-8 py-3.5 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3 flex-1 max-w-xl">
            <button
              type="button"
              onClick={() => setMobileMenuOpen(true)}
              className="lg:hidden p-2 rounded-xl text-slate-600 hover:bg-slate-100"
            >
              <Menu className="w-5 h-5" />
            </button>

            {/* Global Search Bar */}
            <div className="relative w-full">
              <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Buscar cursos, actividades, calificaciones, módulos..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-[#F8FAFC] border border-slate-200/80 rounded-full pl-9 pr-4 py-2 text-xs text-slate-800 placeholder-slate-400 focus:outline-none focus:border-[#25855A] focus:bg-white transition-all"
              />
            </div>
          </div>

          {/* Header Actions */}
          <div className="flex items-center gap-3">
            {/* Notification Center button */}
            <button
              type="button"
              className="relative p-2 rounded-full hover:bg-slate-100 text-slate-600 transition-colors"
            >
              <Bell className="w-4.5 h-4.5" />
              <span className="absolute top-1 right-1 w-4 h-4 bg-red-500 text-white rounded-full text-[9px] font-bold flex items-center justify-center">
                1
              </span>
            </button>

            {/* Institutional Palette Selector */}
            <div className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-slate-50 border border-slate-200 text-xs font-semibold text-slate-700">
              <span className="w-2.5 h-2.5 rounded-full bg-[#25855A]" />
              <span>Salesiano (Institucional)</span>
              <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
            </div>

            {/* Active role badge */}
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-[#124D37] text-white">
              {currentRole === 'alumno'
                ? 'Estudiante'
                : currentRole === 'docente'
                ? 'Docente'
                : 'Admin'}
            </span>
          </div>
        </header>

        {/* Page Content Body */}
        <main className="p-4 md:p-8 flex-1">{children}</main>
      </div>
    </div>
  );
};

export default RoleLayout;
