// GENERATED BY GEMINI — Campus Salesiano San José
// Shared WelcomeBanner component with contextual theme gradient

import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, ArrowRight, BookOpen } from 'lucide-react';

interface WelcomeBannerProps {
  title: string;
  subtitle: string;
  userRole?: string;
  userName?: string;
  tagText?: string;
  ctaText?: string;
  onCtaClick?: () => void;
  gradientFrom?: string;
  gradientTo?: string;
  illustrationType?: 'lms' | 'default' | 'projects' | 'admin';
}

export const WelcomeBanner: React.FC<WelcomeBannerProps> = ({
  title,
  subtitle,
  userRole = 'Estudiante',
  userName = 'Usuario',
  tagText = 'Sistema Integrado Salesiano • 2026',
  ctaText = 'Comenzar',
  onCtaClick,
  gradientFrom = '#0284c7', // Sky to Blue as in Image 1 screenshot
  gradientTo = '#0369a1',
  illustrationType = 'default',
}) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: -12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, ease: [0.23, 1, 0.32, 1] }}
      className="relative overflow-hidden rounded-[28px] p-7 md:p-9 text-white shadow-lg"
      style={{
        background: `linear-gradient(135deg, ${gradientFrom} 0%, ${gradientTo} 100%)`,
      }}
    >
      {/* Decorative Glow Circles */}
      <div className="absolute top-0 right-1/4 w-72 h-72 rounded-full bg-white/10 blur-3xl pointer-events-none" />
      <div className="absolute -bottom-10 right-0 w-80 h-80 rounded-full bg-amber-400/15 blur-2xl pointer-events-none" />

      {/* Decorative Line Icon */}
      <div className="absolute right-8 top-1/2 -translate-y-1/2 hidden md:block opacity-25">
        <svg width="140" height="140" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.2">
          <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
          <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
          <path d="M12 6v6" />
          <path d="M9 9h6" />
        </svg>
      </div>

      <div className="relative z-10 max-w-2xl">
        {/* Institutional Pill */}
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/15 backdrop-blur-md text-xs font-semibold text-white/90 mb-4 border border-white/20">
          <span className="w-2 h-2 rounded-full bg-amber-300 animate-pulse" />
          <span>{tagText}</span>
        </div>

        {/* Title */}
        <h1 className="font-display font-extrabold text-2xl md:text-3.5xl tracking-tight text-white mb-2 leading-tight">
          {title}
        </h1>

        {/* Subtitle */}
        <p className="text-white/85 text-sm md:text-base leading-relaxed mb-6 font-normal">
          {subtitle}
        </p>

        {/* User Card Tag & Action */}
        <div className="flex flex-wrap items-center gap-4">
          <div className="flex items-center gap-3 bg-white/15 backdrop-blur-md px-3.5 py-1.5 rounded-2xl border border-white/20">
            <div className="w-8 h-8 rounded-xl bg-white/25 flex items-center justify-center font-display font-bold text-xs text-white">
              {userName
                .split(' ')
                .map((n) => n[0])
                .slice(0, 2)
                .join('')}
            </div>
            <div>
              <p className="text-xs font-bold text-white leading-tight">{userName}</p>
              <p className="text-[11px] text-white/70">{userRole}</p>
            </div>
          </div>

          {onCtaClick && (
            <button
              id="banner-cta-btn"
              type="button"
              onClick={onCtaClick}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-full bg-white text-slate-900 font-display font-bold text-xs shadow-md hover:bg-slate-50 transition-all hover:scale-105 active:scale-95"
            >
              <span>{ctaText}</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          )}
        </div>
      </div>
    </motion.div>
  );
};

export default WelcomeBanner;
