// GENERATED BY GEMINI — Campus LMS Module
// Integration step: copy this file to src/components/admin/AdminLMSConfig.tsx
// Recommended admin panel for configuring LMS courses, units and activities via shared lmsService.

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  BookOpen,
  Plus,
  Edit2,
  Trash2,
  Lock,
  Unlock,
  Layers,
  Calendar,
  Award,
  Users,
  Search,
  CheckCircle2,
  X,
  Sparkles,
  Settings,
} from 'lucide-react';
import { lmsService } from '../../services/lmsService';
import { LMSCourse, LMSCourseModule, LMSActivity, CourseStatus } from '../../types';

export const AdminLMSConfig: React.FC = () => {
  const [courses, setCourses] = useState<LMSCourse[]>([]);
  const [selectedCourse, setSelectedCourse] = useState<LMSCourse | null>(null);
  const [courseModules, setCourseModules] = useState<LMSCourseModule[]>([]);
  const [courseActivities, setCourseActivities] = useState<LMSActivity[]>([]);
  const [searchQuery, setSearchQuery] = useState('');

  // Modals state
  const [showCourseModal, setShowCourseModal] = useState(false);
  const [showActivityModal, setShowActivityModal] = useState(false);
  const [showUnitModal, setShowUnitModal] = useState(false);

  // New Course Form State
  const [newCourseName, setNewCourseName] = useState('');
  const [newCourseCode, setNewCourseCode] = useState('');
  const [newCourseTeacher, setNewCourseTeacher] = useState('Ing. Giovanni Marquez');
  const [newCourseGrade, setNewCourseGrade] = useState('10');
  const [newCourseSection, setNewCourseSection] = useState('A');
  const [newCourseDesc, setNewCourseDesc] = useState('');
  const [newCourseColor, setNewCourseColor] = useState('#25855A');

  // New Unit Form State
  const [newUnitTitle, setNewUnitTitle] = useState('');
  const [newUnitDesc, setNewUnitDesc] = useState('');

  // New Activity Form State
  const [newActTitle, setNewActTitle] = useState('');
  const [newActType, setNewActType] = useState<'delivery' | 'rubric' | 'evaluated'>('delivery');
  const [newActMaxScore, setNewActMaxScore] = useState(10);
  const [newActDueDate, setNewActDueDate] = useState('2026-09-10');
  const [newActInstructions, setNewActInstructions] = useState('');

  useEffect(() => {
    const load = () => {
      const allCourses = lmsService.getCourses();
      setCourses(allCourses);
      if (allCourses.length > 0 && !selectedCourse) {
        setSelectedCourse(allCourses[0]);
      }
    };
    load();
    const unsub = lmsService.subscribe(load);
    return () => unsub();
  }, []);

  useEffect(() => {
    if (selectedCourse) {
      setCourseModules(lmsService.getModulesByCourse(selectedCourse.id));
      setCourseActivities(lmsService.getActivities(selectedCourse.id));
    }
  }, [selectedCourse, courses]);

  const handleCreateCourse = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newCourseName.trim()) return;

    const created = lmsService.addCourse({
      name: newCourseName,
      code: newCourseCode || `${newCourseName.slice(0, 3).toUpperCase()}-10`,
      description: newCourseDesc,
      teacherId: 'doc-auto',
      teacherName: newCourseTeacher,
      gradeId: newCourseGrade,
      gradeName: `${newCourseGrade}° Bachillerato`,
      sectionId: newCourseSection,
      sectionName: `Sección ${newCourseSection}`,
      subjectId: newCourseName.toLowerCase().replace(/\s+/g, '-'),
      icon: 'BookOpen',
      color: newCourseColor,
      status: 'active',
      schedule: 'Horario regular',
      classroom: 'Aula Asignada',
      unitsCount: 0,
      activitiesCount: 0,
    });

    setShowCourseModal(false);
    setSelectedCourse(created);
    setNewCourseName('');
    setNewCourseDesc('');
  };

  const handleCreateUnit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedCourse || !newUnitTitle.trim()) return;

    lmsService.addModule({
      courseId: selectedCourse.id,
      title: newUnitTitle,
      description: newUnitDesc,
    });
    setShowUnitModal(false);
    setNewUnitTitle('');
    setNewUnitDesc('');
  };

  const handleCreateActivity = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedCourse || !newActTitle.trim()) return;

    lmsService.addActivity({
      courseId: selectedCourse.id,
      title: newActTitle,
      type: newActType,
      maxScore: Number(newActMaxScore),
      dueDate: new Date(newActDueDate).toISOString(),
      instructions: newActInstructions,
      attachments: [],
      status: 'pendiente',
    });

    setShowActivityModal(false);
    setNewActTitle('');
    setNewActInstructions('');
  };

  const handleDeleteCourse = (courseId: string) => {
    if (confirm('¿Está seguro de eliminar este curso del LMS?')) {
      lmsService.deleteCourse(courseId);
      const remaining = lmsService.getCourses();
      setSelectedCourse(remaining.length > 0 ? remaining[0] : null);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-md bg-emerald-100 text-emerald-800 border border-emerald-200">
              CONFIGURACIÓN ADMINISTRATIVA
            </span>
          </div>
          <h1 className="font-display font-bold text-2xl text-slate-900 mt-1">
            Gestión Centralizada del Aula Virtual LMS
          </h1>
          <p className="text-xs text-slate-500">
            Administra cursos, asignación de docentes, unidades y actividades compartidas en tiempo real.
          </p>
        </div>

        <button
          type="button"
          onClick={() => setShowCourseModal(true)}
          className="btn-primary !px-5 gap-2 shrink-0 self-start sm:self-center"
        >
          <Plus className="w-4 h-4" />
          <span>Nuevo Curso LMS</span>
        </button>
      </div>

      {/* 2-Column Admin Grid: Courses List (Left) + Course Content Manager (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Courses Selector */}
        <div className="lg:col-span-5 space-y-4">
          <div className="card-crema p-4.5 space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="font-display font-bold text-slate-900 text-sm uppercase tracking-wider">
                Cursos Registrados ({courses.length})
              </h3>
            </div>

            <div className="relative">
              <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Filtrar cursos..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="input-crema !py-1.5 !pl-8 text-xs"
              />
            </div>

            <div className="space-y-2 max-h-[580px] overflow-y-auto pr-1">
              {courses
                .filter((c) => c.name.toLowerCase().includes(searchQuery.toLowerCase()))
                .map((c) => {
                  const isSelected = selectedCourse?.id === c.id;
                  return (
                    <div
                      key={c.id}
                      onClick={() => setSelectedCourse(c)}
                      className={`p-3.5 rounded-2xl border transition-all cursor-pointer flex items-center justify-between gap-3 ${
                        isSelected
                          ? 'bg-emerald-50/80 border-[#25855A] shadow-xs'
                          : 'bg-white border-slate-200/80 hover:bg-slate-50'
                      }`}
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <div
                          className="w-9 h-9 rounded-xl flex items-center justify-center font-bold text-xs shrink-0"
                          style={{
                            backgroundColor: `${c.color}20`,
                            color: c.color,
                          }}
                        >
                          {c.code.split('-')[0]}
                        </div>
                        <div className="min-w-0">
                          <p className="font-bold text-slate-900 text-xs truncate">
                            {c.name}
                          </p>
                          <p className="text-[11px] text-slate-500 truncate">
                            {c.teacherName} • {c.gradeName} {c.sectionName}
                          </p>
                        </div>
                      </div>

                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDeleteCourse(c.id);
                        }}
                        className="p-1.5 text-slate-300 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors shrink-0"
                        title="Eliminar curso"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  );
                })}
            </div>
          </div>
        </div>

        {/* Right Column: Selected Course Content Configuration */}
        <div className="lg:col-span-7 space-y-5">
          {selectedCourse ? (
            <>
              {/* Selected Course Header */}
              <div className="card-crema p-6 flex items-start justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-slate-100 text-slate-700">
                      {selectedCourse.code}
                    </span>
                    <span className="text-xs font-semibold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200">
                      {selectedCourse.status}
                    </span>
                  </div>
                  <h2 className="font-display font-bold text-xl text-slate-900 mt-1">
                    {selectedCourse.name}
                  </h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Docente titular: {selectedCourse.teacherName} | {selectedCourse.gradeName} {selectedCourse.sectionName}
                  </p>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setShowUnitModal(true)}
                    className="btn-secondary !py-1.5 !px-3 text-xs gap-1.5"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Agregar Unidad</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowActivityModal(true)}
                    className="btn-primary !py-1.5 !px-3 text-xs gap-1.5"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Crear Tarea</span>
                  </button>
                </div>
              </div>

              {/* Units Section */}
              <div className="card-crema p-6 space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="font-display font-bold text-slate-900 text-base">
                    Unidades Didácticas ({courseModules.length})
                  </h3>
                </div>

                {courseModules.length === 0 ? (
                  <p className="text-xs text-slate-400 py-3 text-center">
                    No hay unidades configuradas. Haz clic en "Agregar Unidad".
                  </p>
                ) : (
                  <div className="space-y-2.5">
                    {courseModules.map((mod) => (
                      <div
                        key={mod.id}
                        className="p-3 rounded-xl bg-slate-50 border border-slate-200 flex items-center justify-between gap-3 text-xs"
                      >
                        <div className="flex items-center gap-2.5 min-w-0">
                          <span className="w-6 h-6 rounded-lg bg-white border border-slate-200 font-bold text-slate-600 flex items-center justify-center shrink-0">
                            {mod.order}
                          </span>
                          <div className="min-w-0">
                            <p className="font-bold text-slate-800 truncate">{mod.title}</p>
                            {mod.description && (
                              <p className="text-[11px] text-slate-500 truncate">
                                {mod.description}
                              </p>
                            )}
                          </div>
                        </div>

                        <button
                          type="button"
                          onClick={() => lmsService.toggleModuleLock(mod.id)}
                          className={`p-1.5 rounded-lg border text-xs font-semibold flex items-center gap-1 ${
                            mod.locked
                              ? 'bg-red-50 text-red-700 border-red-200'
                              : 'bg-emerald-50 text-emerald-700 border-emerald-200'
                          }`}
                        >
                          {mod.locked ? <Lock className="w-3.5 h-3.5" /> : <Unlock className="w-3.5 h-3.5" />}
                          <span>{mod.locked ? 'Bloqueado' : 'Abierto'}</span>
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Activities Section */}
              <div className="card-crema p-6 space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="font-display font-bold text-slate-900 text-base">
                    Actividades y Evaluaciones ({courseActivities.length})
                  </h3>
                </div>

                {courseActivities.length === 0 ? (
                  <p className="text-xs text-slate-400 py-3 text-center">
                    No hay tareas en este curso. Haz clic en "Crear Tarea".
                  </p>
                ) : (
                  <div className="space-y-2.5">
                    {courseActivities.map((act) => (
                      <div
                        key={act.id}
                        className="p-3 rounded-xl bg-slate-50 border border-slate-200 flex items-center justify-between gap-3 text-xs"
                      >
                        <div>
                          <p className="font-bold text-slate-800">{act.title}</p>
                          <p className="text-[11px] text-slate-500">
                            Tipo: <span className="capitalize font-semibold">{act.type}</span> |
                            Puntaje máx: {act.maxScore} pts | Vence:{' '}
                            {new Date(act.dueDate).toLocaleDateString()}
                          </p>
                        </div>

                        <span className="px-2 py-0.5 rounded text-[11px] font-bold bg-amber-100 text-amber-800">
                          {act.status}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </>
          ) : (
            <div className="card-crema p-12 text-center text-slate-400 text-xs">
              Seleccione un curso del panel izquierdo para configurar sus contenidos.
            </div>
          )}
        </div>
      </div>

      {/* ============================================================ */}
      {/* MODAL: NUEVO CURSO (Matching Modal Design from Image 5) */}
      {/* ============================================================ */}
      <AnimatePresence>
        {showCourseModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/55 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-[28px] border border-slate-200 shadow-2xl max-w-lg w-full p-6 md:p-8 space-y-5"
            >
              <div className="flex items-center justify-between pb-3 border-b border-slate-100">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-xl bg-emerald-50 text-[#25855A] flex items-center justify-center">
                    <BookOpen className="w-4 h-4" />
                  </div>
                  <h3 className="font-display font-bold text-slate-900 text-lg">
                    Nuevo Curso LMS
                  </h3>
                </div>
                <button
                  type="button"
                  onClick={() => setShowCourseModal(false)}
                  className="p-1 rounded-lg text-slate-400 hover:text-slate-700"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleCreateCourse} className="space-y-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Nombre de la Asignatura *
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="Ej. Robótica y Sistemas Embebidos"
                    value={newCourseName}
                    onChange={(e) => setNewCourseName(e.target.value)}
                    className="input-crema"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Código de Curso
                    </label>
                    <input
                      type="text"
                      placeholder="ROB-10A"
                      value={newCourseCode}
                      onChange={(e) => setNewCourseCode(e.target.value)}
                      className="input-crema"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Docente Responsable
                    </label>
                    <input
                      type="text"
                      value={newCourseTeacher}
                      onChange={(e) => setNewCourseTeacher(e.target.value)}
                      className="input-crema"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Grado
                    </label>
                    <select
                      value={newCourseGrade}
                      onChange={(e) => setNewCourseGrade(e.target.value)}
                      className="input-crema"
                    >
                      <option value="10">10° Bachillerato</option>
                      <option value="11">11° Bachillerato</option>
                      <option value="9">9° Grado</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                      Sección
                    </label>
                    <select
                      value={newCourseSection}
                      onChange={(e) => setNewCourseSection(e.target.value)}
                      className="input-crema"
                    >
                      <option value="A">Sección A</option>
                      <option value="B">Sección B</option>
                      <option value="C">Sección C</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Descripción del Curso
                  </label>
                  <textarea
                    rows={3}
                    placeholder="Descripción curricular y objetivos..."
                    value={newCourseDesc}
                    onChange={(e) => setNewCourseDesc(e.target.value)}
                    className="input-crema resize-none"
                  />
                </div>

                <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-100">
                  <button
                    type="button"
                    onClick={() => setShowCourseModal(false)}
                    className="btn-secondary"
                  >
                    Cancelar
                  </button>
                  <button type="submit" className="btn-primary">
                    Guardar Curso
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* ============================================================ */}
      {/* MODAL: NUEVA UNIDAD */}
      {/* ============================================================ */}
      <AnimatePresence>
        {showUnitModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/55 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-[28px] border border-slate-200 shadow-2xl max-w-md w-full p-6 space-y-4"
            >
              <div className="flex items-center justify-between pb-2 border-b border-slate-100">
                <h3 className="font-display font-bold text-slate-900 text-base">
                  Nueva Unidad Didáctica
                </h3>
                <button
                  type="button"
                  onClick={() => setShowUnitModal(false)}
                  className="text-slate-400 hover:text-slate-700"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleCreateUnit} className="space-y-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    Título de la Unidad *
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="Ej. Unidad 1: Circuitos Lógicos"
                    value={newUnitTitle}
                    onChange={(e) => setNewUnitTitle(e.target.value)}
                    className="input-crema"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    Descripción / Temario
                  </label>
                  <textarea
                    rows={2}
                    value={newUnitDesc}
                    onChange={(e) => setNewUnitDesc(e.target.value)}
                    className="input-crema resize-none"
                  />
                </div>
                <div className="flex justify-end gap-2 pt-2">
                  <button
                    type="button"
                    onClick={() => setShowUnitModal(false)}
                    className="btn-secondary"
                  >
                    Cancelar
                  </button>
                  <button type="submit" className="btn-primary">
                    Agregar Unidad
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* ============================================================ */}
      {/* MODAL: NUEVA ACTIVIDAD */}
      {/* ============================================================ */}
      <AnimatePresence>
        {showActivityModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/55 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-[28px] border border-slate-200 shadow-2xl max-w-lg w-full p-6 space-y-4"
            >
              <div className="flex items-center justify-between pb-2 border-b border-slate-100">
                <h3 className="font-display font-bold text-slate-900 text-base">
                  Crear Actividad / Tarea
                </h3>
                <button
                  type="button"
                  onClick={() => setShowActivityModal(false)}
                  className="text-slate-400 hover:text-slate-700"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleCreateActivity} className="space-y-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    Título de la Tarea / Evaluación *
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="Ej. Taller Práctico de Microcontroladores"
                    value={newActTitle}
                    onChange={(e) => setNewActTitle(e.target.value)}
                    className="input-crema"
                  />
                </div>

                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Tipo</label>
                    <select
                      value={newActType}
                      onChange={(e: any) => setNewActType(e.target.value)}
                      className="input-crema"
                    >
                      <option value="delivery">Entrega de Archivo</option>
                      <option value="rubric">Con Rúbrica</option>
                      <option value="evaluated">Evaluada</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Puntaje</label>
                    <input
                      type="number"
                      value={newActMaxScore}
                      onChange={(e) => setNewActMaxScore(Number(e.target.value))}
                      className="input-crema"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">Vence</label>
                    <input
                      type="date"
                      value={newActDueDate}
                      onChange={(e) => setNewActDueDate(e.target.value)}
                      className="input-crema"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    Instrucciones
                  </label>
                  <textarea
                    rows={3}
                    placeholder="Detalles sobre entregables y criterios..."
                    value={newActInstructions}
                    onChange={(e) => setNewActInstructions(e.target.value)}
                    className="input-crema resize-none"
                  />
                </div>

                <div className="flex justify-end gap-2 pt-2 border-t border-slate-100">
                  <button
                    type="button"
                    onClick={() => setShowActivityModal(false)}
                    className="btn-secondary"
                  >
                    Cancelar
                  </button>
                  <button type="submit" className="btn-primary">
                    Publicar Tarea
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default AdminLMSConfig;
