// GENERATED BY GEMINI — Campus LMS Module
// Integration step: copy this file to src/components/lms/shared/ActivityItem.tsx

import React from 'react';
import { motion } from 'motion/react';
import {
  Calendar,
  FileText,
  Award,
  CheckCircle2,
  AlertCircle,
  Clock,
  ArrowRight,
  Sparkles,
} from 'lucide-react';
import { LMSActivity, ActivityStatus } from '../../../types';

interface ActivityItemProps {
  activity: LMSActivity;
  onSelect: () => void;
  index?: number;
}

export const getStatusBadgeConfig = (status: ActivityStatus = 'pendiente') => {
  switch (status) {
    case 'entregada':
      return {
        label: 'Entregada',
        classes: 'bg-sky-50 text-sky-700 border-sky-200',
        icon: CheckCircle2,
      };
    case 'calificada':
      return {
        label: 'Calificada',
        classes: 'bg-emerald-50 text-emerald-700 border-emerald-200',
        icon: Award,
      };
    case 'vencida':
      return {
        label: 'Vencida',
        classes: 'bg-red-50 text-red-700 border-red-200',
        icon: AlertCircle,
      };
    case 'pendiente':
    default:
      return {
        label: 'Pendiente',
        classes: 'bg-amber-50 text-amber-700 border-amber-200',
        icon: Clock,
      };
  }
};

const getTypeLabel = (type: string) => {
  switch (type) {
    case 'rubric':
      return { label: 'Con Rúbrica', color: 'bg-indigo-50 text-indigo-700 border-indigo-200' };
    case 'evaluated':
      return { label: 'Actividad Evaluada', color: 'bg-emerald-50 text-emerald-700 border-emerald-200' };
    case 'delivery':
      return { label: 'Entrega de Tarea', color: 'bg-sky-50 text-sky-700 border-sky-200' };
    case 'quiz':
      return { label: 'Cuestionario', color: 'bg-purple-50 text-purple-700 border-purple-200' };
    default:
      return { label: 'Actividad', color: 'bg-slate-100 text-slate-700 border-slate-200' };
  }
};

export const ActivityItem: React.FC<ActivityItemProps> = ({
  activity,
  onSelect,
  index = 0,
}) => {
  const statusConfig = getStatusBadgeConfig(activity.status);
  const typeConfig = getTypeLabel(activity.type);
  const StatusIcon = statusConfig.icon;

  const formatDate = (isoString: string) => {
    try {
      const d = new Date(isoString);
      return d.toLocaleDateString('es-SV', {
        day: 'numeric',
        month: 'short',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return isoString;
    }
  };

  return (
    <motion.div
      id={`activity-item-${activity.id}`}
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04, duration: 0.3, ease: [0.23, 1, 0.32, 1] }}
      onClick={onSelect}
      className="card-crema card-interactive flex flex-col md:flex-row md:items-center justify-between gap-4 p-5 group"
    >
      <div className="flex items-start gap-3.5 flex-1 min-w-0">
        <div
          className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 mt-0.5"
          style={{
            backgroundColor: `${activity.courseColor || '#25855A'}15`,
            color: activity.courseColor || '#25855A',
          }}
        >
          {activity.type === 'rubric' ? (
            <Award className="w-5 h-5" />
          ) : (
            <FileText className="w-5 h-5" />
          )}
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2 mb-1">
            <span
              className="text-xs font-semibold px-2 py-0.5 rounded-md border"
              style={{
                borderColor: `${activity.courseColor || '#64748b'}40`,
                color: activity.courseColor || '#334155',
                backgroundColor: `${activity.courseColor || '#64748b'}10`,
              }}
            >
              {activity.courseName || 'Curso'}
            </span>

            <span
              className={`text-[11px] font-semibold px-2 py-0.5 rounded-md border ${typeConfig.color}`}
            >
              {typeConfig.label}
            </span>

            <span
              className={`inline-flex items-center gap-1 text-[11px] font-semibold px-2 py-0.5 rounded-md border ${statusConfig.classes}`}
            >
              <StatusIcon className="w-3 h-3" />
              {statusConfig.label}
            </span>
          </div>

          <h4 className="font-display font-bold text-slate-900 text-base group-hover:text-[#25855A] transition-colors line-clamp-1">
            {activity.title}
          </h4>

          {activity.moduleTitle && (
            <p className="text-xs text-slate-500 line-clamp-1 mt-0.5">
              {activity.moduleTitle}
            </p>
          )}
        </div>
      </div>

      {/* Right meta details & button */}
      <div className="flex items-center justify-between md:justify-end gap-5 shrink-0 pt-2 md:pt-0 border-t md:border-t-0 border-slate-100">
        <div className="text-right">
          <div className="flex items-center gap-1.5 text-xs text-slate-500 font-medium justify-end">
            <Calendar className="w-3.5 h-3.5 text-slate-400" />
            <span>Vence: {formatDate(activity.dueDate)}</span>
          </div>

          {activity.status === 'calificada' && activity.submission?.grade !== undefined ? (
            <div className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded mt-1 border border-emerald-200">
              <Sparkles className="w-3 h-3" />
              <span>Nota: {activity.submission.grade.toFixed(1)} / {activity.maxScore}</span>
            </div>
          ) : (
            <span className="text-[11px] font-semibold text-slate-400 mt-0.5 block">
              Puntaje máx: {activity.maxScore} pts
            </span>
          )}
        </div>

        <button
          type="button"
          className="btn-secondary !py-2 !px-3 text-xs gap-1.5 group-hover:border-[#25855A] group-hover:text-[#25855A]"
        >
          <span>{activity.status === 'pendiente' ? 'Entregar' : 'Ver detalle'}</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>
    </motion.div>
  );
};

export default ActivityItem;
