// GENERATED BY GEMINI — Campus LMS Module
// Tarjeta de Módulo Técnico de Diseño Gráfico con Carga Horaria y Nivel MINED

import React from 'react';
import { motion } from 'motion/react';
import {
  Palette,
  Brush,
  PenTool,
  Feather,
  Layout,
  Box,
  Camera,
  Printer,
  Megaphone,
  Video,
  Radio,
  Image,
  Globe,
  Languages,
  Briefcase,
  TrendingUp,
  Coins,
  Presentation,
  Award,
  Compass,
  BookOpen,
  Users,
  Clock,
  ArrowRight,
  Sparkles,
  CheckCircle2,
} from 'lucide-react';
import { LMSCourse } from '../../../types';
import ProgressRing from './ProgressRing';

interface CourseCardProps {
  course: LMSCourse;
  onClick: () => void;
  index?: number;
}

const getCourseIcon = (iconName: string) => {
  switch (iconName) {
    case 'Palette':
      return Palette;
    case 'Brush':
      return Brush;
    case 'PenTool':
      return PenTool;
    case 'Feather':
      return Feather;
    case 'Layout':
      return Layout;
    case 'Box':
      return Box;
    case 'Camera':
      return Camera;
    case 'Printer':
      return Printer;
    case 'Megaphone':
      return Megaphone;
    case 'Video':
      return Video;
    case 'Radio':
      return Radio;
    case 'Image':
      return Image;
    case 'Globe':
      return Globe;
    case 'Languages':
      return Languages;
    case 'Briefcase':
      return Briefcase;
    case 'TrendingUp':
      return TrendingUp;
    case 'Coins':
      return Coins;
    case 'Presentation':
      return Presentation;
    case 'Award':
      return Award;
    case 'Compass':
      return Compass;
    default:
      return BookOpen;
  }
};

export const CourseCard: React.FC<CourseCardProps> = ({ course, onClick, index = 0 }) => {
  const IconComponent = getCourseIcon(course.icon);
  const progressVal = course.progress ?? 0;

  return (
    <motion.div
      id={`course-card-${course.id}`}
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04, duration: 0.35, ease: [0.23, 1, 0.32, 1] }}
      onClick={onClick}
      className="card-crema card-interactive relative flex flex-col justify-between overflow-hidden group p-6 border border-slate-200/80 hover:border-slate-300 transition-all hover:shadow-md"
    >
      {/* Top row: Icon + Code/Hours + Progress Ring */}
      <div>
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex items-center gap-3">
            <div
              className="w-12 h-12 rounded-2xl flex items-center justify-center transition-transform group-hover:scale-105 duration-200 shadow-sm"
              style={{
                backgroundColor: `${course.color}18`,
                color: course.color,
                border: `1.5px solid ${course.color}35`,
              }}
            >
              <IconComponent className="w-6 h-6" />
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-1.5">
                <span className="font-mono font-bold text-[11px] px-2 py-0.5 rounded-md bg-slate-900 text-white tracking-wide">
                  {course.code}
                </span>
                {course.hours && (
                  <span className="text-[11px] font-semibold px-2 py-0.5 rounded-md bg-amber-50 text-amber-800 border border-amber-200">
                    {course.hours}h • {course.weeks} {course.weeks === 1 ? 'sem' : 'sem.'}
                  </span>
                )}
              </div>
              <h3 className="font-display font-bold text-slate-900 text-base md:text-lg group-hover:text-[#0D71B9] transition-colors mt-1 line-clamp-1">
                {course.name}
              </h3>
            </div>
          </div>

          <ProgressRing
            progress={progressVal}
            size={48}
            strokeWidth={4.5}
            color={course.color || '#0D71B9'}
          />
        </div>

        {/* Affine area badge */}
        {course.affineArea && (
          <div className="mb-2">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
              {course.affineArea}
            </span>
          </div>
        )}

        {/* Course Description */}
        <p className="text-slate-600 text-xs leading-relaxed line-clamp-2 mb-3">
          {course.description}
        </p>

        {/* Project snippet if available */}
        {course.descriptor?.currentProject && (
          <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-200/60 mb-3 text-xs">
            <span className="text-[10px] font-bold text-indigo-700 uppercase tracking-wide flex items-center gap-1">
              <Sparkles className="w-3 h-3" /> Proyecto {course.descriptor.currentProject.academicYear}:
            </span>
            <p className="font-semibold text-slate-800 truncate mt-0.5">
              {course.descriptor.currentProject.title}
            </p>
          </div>
        )}

        {/* Meta badges: Teacher, Classroom */}
        <div className="space-y-1.5 pt-2 border-t border-slate-100 text-xs text-slate-600">
          <div className="flex items-center gap-2">
            <Users className="w-3.5 h-3.5 text-slate-400 shrink-0" />
            <span className="font-medium text-slate-700 truncate">{course.teacherName}</span>
          </div>
          {course.classroom && (
            <div className="flex items-center gap-2">
              <Clock className="w-3.5 h-3.5 text-slate-400 shrink-0" />
              <span className="text-slate-500 truncate">{course.classroom}</span>
            </div>
          )}
        </div>
      </div>

      {/* Footer bar: MINED Level + Action button */}
      <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs">
          {course.minedLevel ? (
            <span
              className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-bold ${
                course.minedLevel >= 4
                  ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                  : 'bg-amber-100 text-amber-800 border border-amber-300'
              }`}
            >
              <CheckCircle2 className="w-3 h-3" /> Nivel {course.minedLevel} MINED
            </span>
          ) : (
            <span className="text-slate-400 text-[11px]">En progreso</span>
          )}
        </div>

        <button
          id={`btn-open-course-${course.id}`}
          type="button"
          className="inline-flex items-center gap-1 text-xs font-bold text-[#0D71B9] group-hover:translate-x-0.5 transition-transform"
        >
          <span>Abrir Módulo</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>
    </motion.div>
  );
};

export default CourseCard;
