// GENERATED BY GEMINI — Campus LMS Module
// Integration step: copy this file to src/components/lms/shared/RubricView.tsx

import React from 'react';
import { Award, Info, CheckCircle2 } from 'lucide-react';
import { Rubric } from '../../../types';

interface RubricViewProps {
  rubric: Rubric;
  selectedScores?: Record<string, number>; // criterionId -> score (1-5)
  onScoreSelect?: (criterionId: string, score: number) => void;
  readOnly?: boolean;
  maxScore?: number;
}

export const RubricView: React.FC<RubricViewProps> = ({
  rubric,
  selectedScores = {},
  onScoreSelect,
  readOnly = false,
  maxScore = 10,
}) => {
  // Calculate calculated score based on weights
  const calculateTotal = () => {
    let totalWeighted = 0;
    let totalWeights = 0;

    rubric.criteria.forEach((crit) => {
      const score = selectedScores[crit.id] || 0;
      totalWeighted += (score / 5) * crit.weight;
      totalWeights += crit.weight;
    });

    if (totalWeights === 0) return 0;
    const normalized = (totalWeighted / totalWeights) * maxScore;
    return parseFloat(normalized.toFixed(1));
  };

  const calculatedScore = calculateTotal();

  return (
    <div className="card-crema p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 border border-indigo-200 flex items-center justify-center">
            <Award className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-display font-bold text-slate-900 text-base">
              {rubric.title}
            </h3>
            <p className="text-xs text-slate-500">
              {rubric.description || 'Evaluación cualitativa y cuantitativa por competencias'}
            </p>
          </div>
        </div>

        {selectedScores && Object.keys(selectedScores).length > 0 && (
          <div className="bg-emerald-50 border border-emerald-200 px-4 py-2 rounded-2xl flex items-center gap-3 shrink-0">
            <div className="text-right">
              <span className="text-[11px] font-semibold text-emerald-800 uppercase tracking-wider block">
                Calificación Rúbrica
              </span>
              <span className="font-display font-bold text-emerald-900 text-lg">
                {calculatedScore} / {maxScore} pts
              </span>
            </div>
          </div>
        )}
      </div>

      {/* Criteria Breakdown */}
      <div className="space-y-6">
        {rubric.criteria.map((criterion, critIdx) => {
          const currentScore = selectedScores[criterion.id];

          return (
            <div
              key={criterion.id}
              className="bg-slate-50/70 border border-slate-200/80 rounded-2xl p-4.5 space-y-3"
            >
              <div className="flex items-center justify-between gap-3">
                <div className="flex items-center gap-2">
                  <span className="w-6 h-6 rounded-full bg-white border border-slate-200 text-xs font-bold text-slate-700 flex items-center justify-center shrink-0">
                    {critIdx + 1}
                  </span>
                  <h4 className="font-display font-bold text-slate-800 text-sm">
                    {criterion.title}
                  </h4>
                </div>
                <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-indigo-100/70 text-indigo-700 border border-indigo-200">
                  Ponderación: {criterion.weight}%
                </span>
              </div>

              {/* Levels grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-2.5 pt-1">
                {criterion.levels.map((level) => {
                  const isSelected = currentScore === level.score;
                  const isClickable = !readOnly && onScoreSelect;

                  return (
                    <div
                      key={level.score}
                      onClick={() => isClickable && onScoreSelect(criterion.id, level.score)}
                      className={`p-3 rounded-xl border text-left transition-all relative flex flex-col justify-between ${
                        isSelected
                          ? 'bg-emerald-50/90 border-emerald-500 shadow-sm ring-1 ring-emerald-500'
                          : 'bg-white border-slate-200/80 hover:border-slate-300'
                      } ${isClickable ? 'cursor-pointer' : ''}`}
                    >
                      <div>
                        <div className="flex items-center justify-between mb-1.5">
                          <span
                            className={`text-xs font-bold ${
                              isSelected ? 'text-emerald-800' : 'text-slate-800'
                            }`}
                          >
                            {level.label}
                          </span>
                          <span
                            className={`text-xs font-mono font-bold px-1.5 py-0.2 rounded ${
                              isSelected
                                ? 'bg-emerald-200 text-emerald-900'
                                : 'bg-slate-100 text-slate-600'
                            }`}
                          >
                            {level.score} pts
                          </span>
                        </div>
                        <p className="text-[11px] text-slate-600 leading-relaxed">
                          {level.description}
                        </p>
                      </div>

                      {isSelected && (
                        <div className="flex items-center gap-1 text-[11px] font-semibold text-emerald-700 mt-2 pt-2 border-t border-emerald-200/60">
                          <CheckCircle2 className="w-3.5 h-3.5" />
                          <span>Seleccionado</span>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      {!readOnly && (
        <div className="flex items-center gap-2 text-xs text-slate-500 bg-white p-3 rounded-xl border border-slate-200">
          <Info className="w-4 h-4 text-slate-400 shrink-0" />
          <span>
            Haga clic en los niveles de cada criterio para calcular la puntuación estimada de la rúbrica.
          </span>
        </div>
      )}
    </div>
  );
};

export default RubricView;
