// GENERATED BY GEMINI — Campus LMS Module
// Main Application & Routing architecture for Campus Salesiano San José

import React, { useState } from 'react';
import { RoleLayout } from './components/shared/RoleLayout';
import { StudentDashboard } from './components/alumno/StudentDashboard';
import { LMSModule } from './components/lms/LMSModule';
import { LMSCourseList } from './components/lms/LMSCourseList';
import { LMSCourseDetail } from './components/lms/LMSCourseDetail';
import { LMSActivityList } from './components/lms/LMSActivityList';
import { LMSProgress } from './components/lms/LMSProgress';
import { LMSSubmissionForm } from './components/lms/LMSSubmissionForm';
import { AdminLMSConfig } from './components/admin/AdminLMSConfig';
import { DocenteLMSGrade } from './components/docente/DocenteLMSGrade';
import { CurricularDocsManager } from './components/docente/CurricularDocsManager';
import { SystemModuleId } from './types';

export default function App() {
  // Application role & routing state
  const [currentRole, setCurrentRole] = useState<'alumno' | 'docente' | 'admin'>('alumno');
  const [currentPath, setCurrentPath] = useState<string>('/alumno/lms');
  const [selectedCourseId, setSelectedCourseId] = useState<string>('course-inf-101');
  const [selectedActivityId, setSelectedActivityId] = useState<string>('act-inf-1');

  // Navigation handler
  const handleNavigate = (path: string) => {
    setCurrentPath(path);
  };

  const handleOpenCourse = (courseId: string) => {
    setSelectedCourseId(courseId);
    setCurrentPath(`/alumno/lms/cursos/${courseId}`);
  };

  const handleOpenActivity = (activityId: string) => {
    setSelectedActivityId(activityId);
    setCurrentPath(`/alumno/lms/entregas/${activityId}`);
  };

  const handleModuleClick = (moduleId: SystemModuleId) => {
    if (moduleId === 'lms') {
      setCurrentPath('/alumno/lms');
    } else if (moduleId === 'notas') {
      setCurrentPath('/alumno/lms/progreso');
    } else if (moduleId === 'clase') {
      setCurrentPath('/alumno/lms/cursos');
    } else {
      setCurrentPath('/alumno/lms');
    }
  };

  // Render view depending on path & role
  const renderCurrentView = () => {
    // Curricular Documentation Views for Docente or Admin
    if (currentPath === '/docente/curricular' || currentPath === '/docente/rubrica-29') {
      return <CurricularDocsManager />;
    }

    // Admin Views
    if (currentRole === 'admin') {
      if (currentPath === '/admin/curricular') {
        return <CurricularDocsManager />;
      }
      return <AdminLMSConfig />;
    }

    // Docente Views
    if (currentRole === 'docente') {
      return <DocenteLMSGrade onOpenCurricularDocs={() => setCurrentPath('/docente/curricular')} />;
    }

    // Student Views (Alumno)
    if (currentPath === '/alumno') {
      return (
        <StudentDashboard
          studentName="Estudiante Salesiano"
          onNavigateModule={handleModuleClick}
        />
      );
    }

    if (currentPath === '/alumno/lms/cursos') {
      return (
        <LMSCourseList
          onSelectCourse={handleOpenCourse}
          onBack={() => setCurrentPath('/alumno/lms')}
        />
      );
    }

    if (currentPath.startsWith('/alumno/lms/cursos/')) {
      return (
        <LMSCourseDetail
          courseId={selectedCourseId}
          onBack={() => setCurrentPath('/alumno/lms/cursos')}
          onSelectActivity={handleOpenActivity}
        />
      );
    }

    if (currentPath === '/alumno/lms/actividades') {
      return (
        <LMSActivityList
          onSelectActivity={handleOpenActivity}
          onBack={() => setCurrentPath('/alumno/lms')}
        />
      );
    }

    if (currentPath === '/alumno/lms/progreso') {
      return (
        <LMSProgress
          onBack={() => setCurrentPath('/alumno/lms')}
          onSelectCourse={handleOpenCourse}
        />
      );
    }

    if (currentPath.startsWith('/alumno/lms/entregas/')) {
      return (
        <LMSSubmissionForm
          activityId={selectedActivityId}
          onBack={() => setCurrentPath('/alumno/lms/actividades')}
          onSubmittedSuccess={() => {}}
        />
      );
    }

    // Default student LMS dashboard
    return (
      <LMSModule
        onNavigateCourse={handleOpenCourse}
        onNavigateActivity={handleOpenActivity}
        onViewAllCourses={() => setCurrentPath('/alumno/lms/cursos')}
        onViewAllActivities={() => setCurrentPath('/alumno/lms/actividades')}
        onViewProgress={() => setCurrentPath('/alumno/lms/progreso')}
      />
    );
  };

  return (
    <RoleLayout
      activePath={currentPath}
      onNavigate={handleNavigate}
      currentRole={currentRole}
      onRoleChange={setCurrentRole}
      studentName="Estudiante Salesiano"
    >
      {renderCurrentView()}
    </RoleLayout>
  );
}
